### ISSUE TITLE
Added interim help page to the Wiki section

### ISSUE THREAD

**Issue by pclaesvfx** [ChaosGroup/vray-for-houdini#102]
Hi all, 

I've added an interim help page to the wiki section that has a bunch of information about vray for houdini workflows.

I've been writing it as I learn new things as well as things are fixed or implemented. 
I hope it helps to get some of the other beta testers up to speed faster and do feel free to contribute to it as well if you find some useful info.
https://github.com/ChaosGroup/vray-for-houdini/wiki/Interim-help-docs 

Thanks,
Peter Claes

**Comment by sepux** [comment]
This is great! Thanks for this.
