### ISSUE TITLE
export .vrscene per frame

### ISSUE THREAD

**Issue by ultra-sonic** [ChaosGroup/vray-for-houdini#106]
Hi guys,

I know there is a related issue called "rendering file per frame" but I'm not sure if this relates to a different problem.

In my case when I export frame 1-20 I  can get a single vrscene per frame when using

```
$HIP/vrscenes/$HIPNAME.$F4.vrscene
```

but for some reason the previous frames seem to accumulate in the vrscene...i have a static scene and the frame.0001.vrscene is 9.7kB and frame.0020.vrscene has 43.0kB...see scene attached...

I also have another side-request on this: Can you please make a checkbox to "create intermediate directories" in case some folders do not exist in the path....this is very houdini specific since you very often use expressions within the filename-parms.

Simple file is here
[exportPerFrame.hiplc.zip](https://github.com/ChaosGroup/vray-for-houdini/files/342413/exportPerFrame.hiplc.zip)

thanks in advance
Oliver

**Comment by bdancer** [comment]
$F is supported now.
