### ISSUE TITLE
unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]

### ISSUE THREAD

**Issue by ultra-sonic** [ChaosGroup/vray-for-houdini#127]
hey guys,

I'm on Centos 7 using gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
and I am getting lots of those warnings all the time:

```
unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
```

Is there an easy fix for that?

**Comment by millag** [comment]
This comes from AppSDK header and most likely is compiler bug. You can try to comment out all preprocessor directives in this private section of the class leaving  `int version;` line untouched.
However, this requires change in AppSDK itself and we've already opened internal issue about it.

Hope this helps.

**Comment by millag** [comment]
This is now fixed
