### ISSUE TITLE
is there support for multiple uv-coords yet?

### ISSUE THREAD

**Issue by ultra-sonic** [ChaosGroup/vray-for-houdini#130]
Hi guys...just a quick questions. is there support for multiple uv-coords yet? If yes can you share a simple scene on how to use it? let's say i have an "vec UV" and one "vec UV2" attribute. Any hints? Userdata? VertexColors?
Thanks
Oli

**Comment by bdancer** [comment]
Use "Channel (named)" and enter desired uv attribute name.
