### ISSUE TITLE
V-Ray Renderer Output Typo

### ISSUE THREAD

**Issue by DoverStudios** [ChaosGroup/vray-for-houdini#133]
There is a small typo in the DR tab of the V-Ray Renderer Output window. The checkbox to enable a specific DR host has the word "enabled" misspelt as "Enanbled".

![vray-dr-enabled-typo](https://cloud.githubusercontent.com/assets/18605078/19017427/426ecb86-880f-11e6-841d-663b250f375f.png)

**Comment by poseidon4o** [comment]
This should be fixed with eba3d69a273e294e5be23e815397c63f37ec638c

**Comment by galagast** [comment]
I can confirm that the above is now fixed.

Here are a couple of other typo suggestions.

**Output:**
![image](https://cloud.githubusercontent.com/assets/16534677/20923806/314be1d2-bbe9-11e6-9f30-fd2dbf905313.png)

![image](https://cloud.githubusercontent.com/assets/16534677/20925270/ec550d12-bbf0-11e6-9257-8be3e57d2eb9.png)


Upper-casing of the ff:
* GI
* SSS
* FOV
* IOR
* EXR
* DMC
* ID
* VFB
* RT
* RGB

**Comment by LukeLetellier** [comment]
@galagast What version of Vray for Houdini are you using for the UI seen in your screenshots? I'm using the January 23rd build available on the ChaosGroup downloads page, but it looks much older & unrefined:

Screenshot: http://imgur.com/b07FgEL

I tried going to the Vray Nightlies link shared on the wiki, but that brings me to an almost empty page -  with the directories they provide on the left turning up with only Vray for Blender downloads...

Nightlies page that I get:
http://imgur.com/2jlRKSS

**Comment by galagast** [comment]
Hey Luke,
I'm using custom UI presets that I've built-up while testing VFH last year.
You can find them [here](54).

**Comment by LukeLetellier** [comment]
Thanks!
