### ISSUE TITLE
support for light point instancing 

### ISSUE THREAD

**Issue by headsmell** [ChaosGroup/vray-for-houdini#137]
It would be great to be able to point instance vray lights, like a mantra workflow:
[instanceLights.zip](https://github.com/ChaosGroup/vray-for-houdini/files/587978/instanceLights.zip)

Putting a vray light in place of the standard vray light causes extreme unsuitability in the scene. It will crashes the scene after a  few steps, seems to be random.

**Comment by bdancer** [comment]
> Putting a vray light in place of the standard vray light causes extreme unsuitability in the scene.

Could you pls explain what does this mean?

**Comment by bdancer** [comment]
@poseidon4o Could you pls check the scene?

**Comment by headsmell** [comment]
> Putting a vray light in place of the standard vray light causes extreme unsuitability in the scene

So if you open my scene and replace the standard houdini light with a vray light, on the instance1 node-instance tab -> instanced object, the scene crashes. 

Sometimes instantly, sometimes after a few clicks. Unfortunately its not consistent, but it does cause the scene to be unstable.

**Comment by galagast** [comment]
I'm currently not getting any crashes on Alex's scene.
But vray light instancing still does not seem to work.

[instancelights_vray.zip](https://github.com/ChaosGroup/vray-for-houdini/files/826696/instancelights_vray.zip) - Vfh 352 52e0576 H15.5.632

There's a thread [here](http://forums.odforce.net/topic/29123-rendering-many-lights-with-mantra-is-much-faster-in-160537/#comment-165280) where a significant speed improvement was made to mantra's light instancing for H16.
I would like to setup something similar and use vray lights instead. :)
