### ISSUE TITLE
Compile H 15.5.6

### ISSUE THREAD

**Issue by sepux** [ChaosGroup/vray-for-houdini#139]
Any chance that you guys can compile a version for Houdini 15.5.6 ? 

Thanks

**Comment by millag** [comment]
We've updated our automatic builds to use Houdini 15.5.632 HDK from now on for 15.5 version builds. Nightlies should be available.

However, I think there shouldn't be issues with using the older builds with newer minor versions of Houdini as HDK API is the same. The only thing you have to change is houdini full version in the startup script (i.e. hfs15.5.480.sh) like:
 HOUDINI_VER_FULL=${HOUDINI_VER_MAJOR}.632

Let us know if you experience any issues.
