### ISSUE TITLE
DSO Error; Can't locate libaurloader.so 

### ISSUE THREAD

**Issue by bravehamster** [ChaosGroup/vray-for-houdini#140]
I was thinking of tinkering with the volumetric shader but there's either an issue on my end or you guys have changed something in later builds which prevents Vray from locating the vfh/lib folder in the home directory.

[Screenshot - everything working fine on A19F141](https://drive.google.com/file/d/0B1YJxA06WbiZWXFiNHBDYzZQamM/view)

[Screenshot - latest build 83E9FFB - can't locate libaurloader.so](https://drive.google.com/file/d/0B1YJxA06WbiZcHZIZHR0ODl4X2s/view)

I apologize in advance if I'm wasting your time. 

Thanks.

edit: 

The vfh_lib folder in 

>export VRAY_FOR_HOUDINI_AURA_LOADERS=${LAUNCHER_LOCATION}/vfh_home/vfh_lib

is missing entirely. 

I copied the lib folder from Homedir/houdini15.5/vfh/lib to ${LAUNCHER_LOCATION}/vfh_home/ and renamed it to vfh_lib. 

Seems to work.

**Comment by millag** [comment]
Hey @bravehamster ,

Yes we changed several things in the newer builds.
One change we've made is how the dso is loaded. Previously some of the necessary files (dso, startup scripts, shelves, etc.) were copied to Houdini user folder in order for Houdini to discover them. However we found this wasn't really necessary, so now nothing is copied but HOUDINI_PATH gets extended with vfh_home location.
With regards to how we represent and handle volumes. The PhxShaderCache node was split into 2 nodes - PhxShaderCache SOP for importing volume caches and PhxShaderSim VOP for shading volumes. The latter should be available in V-Ray material context and can be used for shading Houdini volumes as well.  There should be example scene in the nightlies  for the new setup, with more to be uploaded.
From the screenshot seems like those 2 nodes are not registered at all by the plugin, so problem is definitely on our side. We are looking into fixing the build missing those node and necessary loaders...

**Comment by millag** [comment]
Hi there,
We've updated nightly builds and example volume scene. This issue has been fixed  for all builds except for vfh for Houdini15.5-Windows. Assuming you are running on Linux you should be good to go.

NOTE integration for volumes still won't work in vfh for Houdini15.5-Windows as we are pending on vc14 update of Phoenix SDK which is a project dependency.

**Comment by bravehamster** [comment]
Awesome, big thanks!

**Comment by StrobFX** [comment]
Is this fixed now?
