### ISSUE TITLE
Vray Launcher

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#142]
Previous installs were copying files directly to the user directory: (_in Windows_)
![image](https://cloud.githubusercontent.com/assets/16534677/20905521/1f029440-bb7f-11e6-9a1e-a0fb5ebf2465.png)

Looking at the newer batch files _(currently using vfh-42-cf0202a)_, they now seem to reside under `vfh_home`. This is great as it can keep the home folder cleaner.

Is it safe to say that we can now delete those older files found in the Houdini home directory?

**Comment by bdancer** [comment]
> Is it safe to say that we can now delete those older files found in the Houdini home directory?

Yep.

**Comment by galagast** [comment]
Cool, roger that.

Just to confirm, I deleted the files. No errors after running the launcher. 👍
