### ISSUE TITLE
Nightlies Updating Daily?

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#143]
Looking at the nightly release dates, they seem to be updating each day since Nov 23 _(the latest commit as of this writing)_, but the contents are always the same. All of which are showing `vfh-42-cf0202a`.

Previous other dates before that seems to also exhibit the same behavior between commits. It is filling up the nightlies with redundant folders. 😅

**Comment by bdancer** [comment]
Well, yes, it's kinda just builds stuff that is in git...
