### ISSUE TITLE
vray object properties

### ISSUE THREAD

**Issue by sepux** [ChaosGroup/vray-for-houdini#145]
Hi I was wondering if Houdini will support or already support the vray object properties? I have not been able to find it in Houdini. Any ETA for that? 
Thanks.

**Comment by bdancer** [comment]
You could use Mtl Wrapper for that for now.

**Comment by StrobFX** [comment]
Ok. You mean the node called: "Wrapper" with that Mtl Wrapper, we can create matte objects, but does the subdiv multiplier of the mtl wrapper has the same effect as the one from the vray object property in max?

And where and how do we plug the Wrapper ?

**Comment by bdancer** [comment]
> but does the subdiv multiplier of the mtl wrapper has the same effect as the one from the vray object property in max?

Yes, those properties are exported internally as MtlWrapper.

> And where and how do we plug the Wrapper ?

You could plug it as material.

Anyway, there is a toolbar button for adding object properties now.
