### ISSUE TITLE
V-Ray Proxy ROP fails when using a $F for the filename

### ISSUE THREAD

**Issue by dgsantana** [ChaosGroup/vray-for-houdini#146]
When trying to export a animated obj as vrmesh, if we try to save each frame using the $F variable ($HIP/vrmesh/$HIPNAME$F4.vrmesh), it fails on second frame. If you let it overwrite each file it (without using the $F), it works, but of course is useless, since you lost the animation :).

**Comment by millag** [comment]
Actually proxy ROP can save out animation to a single file, but there was a bug when exporting the animation offset to V-Ray. This is now fixed. I'm attaching example [scene](https://github.com/ChaosGroup/vray-for-houdini/files/663918/rop_vrayproxy_animation.zip)

**Comment by dgsantana** [comment]
Cool, thanks.

millag <notifications@github.com> escreveu no dia terça, 20/12/2016 às
14:27:
