### ISSUE TITLE
Vray Material Parameters

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#147]
1. There seems to be two inputs for Fog. `Fog Color` & `Fog Color Texture`. Comparing it to parameters like Diffuse. It should probably only expose Fog Color as a parameter, 
![image](https://cloud.githubusercontent.com/assets/16534677/21341911/ee280f48-c6c9-11e6-8f13-87111037af2c.png)
Then only when a connection is made to the input Fog Color of the node shell we use a texture.
![image](https://cloud.githubusercontent.com/assets/16534677/21341938/192a165a-c6ca-11e6-9ed8-d8bcc843b7e4.png)
2. Self-Illumination Multiplier parameter is missing.
![image](https://cloud.githubusercontent.com/assets/16534677/21341976/5f5e512c-c6ca-11e6-8464-454e3f32b3c1.png)
Although we could probably just do a math multiply ourselves in the VOP network.
3. Options > Opacity Mode parameter is missing.
![image](https://cloud.githubusercontent.com/assets/16534677/21342079/eda0a0e8-c6ca-11e6-877f-8d851891c398.png)

_* VFH 42 Build 6980893_
_* V-Ray for 3dsmax screenshots are from V-Ray DEMO 3.40.03_

**Comment by bdancer** [comment]
3. Afair this one is only implemented in 3dsmax, will check it it's ported to the Standalone / AppSDK.
