### ISSUE TITLE
How Far is Vray for Houdini

### ISSUE THREAD

**Issue by sepux** [ChaosGroup/vray-for-houdini#148]
Hi, 
Im just wondering how far in development is Vray for Houdini? Is it coming early this year or later?
I usually do not know what has change on the nightly builds, I see that they are coming everyday but there isn't changes for what I can tell. Also it would be nice to have more documentation about how to use it for H.

**Comment by bdancer** [comment]
You could track changes in [commits](https://github.com/ChaosGroup/vray-for-houdini/commits/master).
I'm not sure what you mean about completing as every product constantly evolves and adds new features / adds user requested stuff etc.
If you are missing some functionality just lets us know.

**Comment by StrobFX** [comment]
Cold we at least have an idea of what percentage of V-Ray for 3ds Max's features are now implemented and working in V-Ray for Houdini?
