### ISSUE TITLE
LightDome texture without shop network

### ISSUE THREAD

**Issue by Eiken** [ChaosGroup/vray-for-houdini#150]
For a lot of nodes (LightDome for example) a workflow that would make more sense is to be able to directly pick texture files in the parameters. Having to create and pick a shop network is kinda confusing.

Will this change?

**Comment by sepux** [comment]
Agree it should just work as how it works in other apps or have the option to do that.
Also there is a way to export images created from COPs?

**Comment by bdancer** [comment]
> Will this change?

Well I guess it'll work for image files, but for procedural textures not sure...

> Also there is a way to export images created from COPs?

Could you, pls, make a separate issue for that?

**Comment by Eiken** [comment]
In a perfect world it would work directly for image files and if you create procedural textures you would use
op:/ as it works with mantra. It would make getting artists going much easier.

**Comment by Eiken** [comment]
Any news on this? It confuses both the maya guys coming over and the regular houdini users.

**Comment by bdancer** [comment]
Sure, we could change this, but no progress on this currently.

**Comment by Eiken** [comment]
Any update on this? Everything is coming together really nicely but this is really confusing for new artists.

**Comment by sepux** [comment]
Agree with Eiken we need this, is very confusing.

**Comment by dominik2608** [comment]
+1

**Comment by bdancer** [comment]
Changes pushed. Will be available in the next build. Dome light texture paths are supporting file path and IMG nodes.

**Comment by dominik2608** [comment]
Cool thx! Will it be available also in the area lights ?

**Comment by bdancer** [comment]
@dominik2608 not yet.

**Comment by dominik2608** [comment]
ok

**Comment by Eiken** [comment]
Awesome but yeah it needs to be available in all places where it makes sense to pick a texture directly

**Comment by Eiken** [comment]
Not complaining btw. Just want everything fixed so I can throw Maya out the window for everything but animation.

**Comment by bdancer** [comment]
Texture path now supports both "op:" and file path.
