### ISSUE TITLE
Is this code "open"

### ISSUE THREAD

**Issue by varomix** [ChaosGroup/vray-for-houdini#151]
Hey guys

could I use this code to write my own integration for Houdini?

the license doesn't mention the actual code here in github, I think.

thank you

**Comment by bdancer** [comment]
> Is this code "open" 

If by "open" you mean "open source" then yes, it's open under https://github.com/ChaosGroup/vray-for-houdini/blob/master/LICENSE, if you mean "free software" (like GNU) then no and will never be.

> the license doesn't mention the actual code here in github, I think.

License covers V-RAY TRANSLATOR FOR HOUDINI which is exactly this repository.

> could I use this code to write my own integration for Houdini?

Yes, you could reuse this code, as long as you are not sharing your integration in any way (code or binary).
If you want to share your integration you'll have to write it from scratch (using this code only as an example of AppSDK usage).

Btw, we are open for collaboration and accepting patches.

**Comment by varomix** [comment]
Thanks Andrei
I do want to distribute my integration so I'll have to write my own then

I would love to help, not an expert but would do what I can, don't have VRay

thanks for the answers

**Comment by bdancer** [comment]
> I do want to distribute my integration so I'll have to write my own then

Then you'll have to write at email to support@chaosgroup.com and they'll provide you additional info.
