### ISSUE TITLE
Vray Shelf

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#152]
I'm currently using the January 23rd build of VtoH for 632, but I must be missing part of my installation -  as I don't have a Vray shelf as part of my  UI (currently using the technical desktop). I looked on the wiki, and there's no mention of how to create or initialize the shelf, so I must be simply missing it?

I did notice that my VforH directory is different than the one described in the Wiki, as I don't have the 'deploy' or 'dso' folders, but I do have folders named 'ui' and 'vfh_home'. Wasn't sure if that was the reason, or if the wiki is just outdated. 

Thanks,
Luke

**Comment by millag** [comment]
I've updated the wiki page. Take a look and tell us if this was the problem.
https://github.com/ChaosGroup/vray-for-houdini/wiki.

**Comment by LukeLetellier** [comment]
Thank you! Got it working now.

Perhaps in the future someone could write down instructions for the correct environment setup so that we don't need to worry about using the batch file. It's very easy to launch right now though, so I'm not complaining! :)
