### ISSUE TITLE
VrayPhyCam F-Number/ShutterSpeed Parameters & Image Brightness

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#154]
The VrayPhysCam F-Number & Shutter Speed parameters do not appear to have any effect on the brightness of the image. In the C4D version of Vray these do effect image brightness (as would happen in a physical camera) so  wasn't sure if this was intentional or a bug.

Both workflows have pros & cons;  the current setup makes it easier to work with motion blur & DOF, as you don't have to worry about finessing your lighting at the same time - but you also need to set your light intensities much higher in general.

**Comment by galagast** [comment]
None of the parameters created by the ff seems to have any effect on the render:
**Physical Camera Shelf Tools:**
![image](https://cloud.githubusercontent.com/assets/16534677/22823471/c479be76-efbe-11e6-857a-4aa567041e46.png)
**Edit Parameter Interface > Render Properties > Vray > Physical Camera:**
![image](https://cloud.githubusercontent.com/assets/16534677/22823533/0af48016-efbf-11e6-83c3-be23ca5c2bc5.png)
[dof.zip - H15.5.632](https://github.com/ChaosGroup/vray-for-houdini/files/766396/dof.zip)

**Comment by millag** [comment]
@LukeLetellier You should use the shelf tool to add spare  Physical Camera rendering parameters. There is a toggle on the bottom called 'Use' to quickly turn on/off the physical camera which annoyingly is disabled by default.

@galagast  Parameters added through 'Edit Parameter Interface > Render Properties > Vray > Physical Camera' don't seem work at all. We will fix this and remove the shelf tool as it gets quite confusing.

**Comment by galagast** [comment]
Thanks Mila 😄 
I suppose the shelf tool can always be re-created later by a user using python.

**Comment by LukeLetellier** [comment]
Ah, thank you for sharing about the 'Use' button, that is a bit sneaky. :)

**Comment by StrobFX** [comment]
My god it's a luck I found this issue! I was going nut trying to adjust the cam setting! :O
