### ISSUE TITLE
Vray renders hidden cube within flipfluidobject Node

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#156]
When a FLIP fluid node is created, it contains a hidden cube inside it's network (Flipfluidobject --> Particlefluidobject -->Defaultfluid-->cube). It's invisible to the viewport, but Vray renders it in every image. 

The cube cannot be hidden from the render using the traditional means of disabling or hiding the master node; instead one has to dive in and delete in manually. 

Sample scene:
https://www.dropbox.com/s/rer4rifob1npqui/Vray_FLIP_Cube.hiplc?dl=0

**Comment by varomix** [comment]
you can get rid of it by using force objects in the VRAY ROP
but yeah, that shouldn't be rendered

**Comment by galagast** [comment]
Confirmed, the box is now hidden from the render. Thanks for the fix!
