### ISSUE TITLE
Point Rendering

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#158]
Is there a current workflow for point/particle rendering, or has it not been implemented yet? I looked through the interim help documentation & the threads, but couldn't find any references to it. 

If I really needed to I could copy spheres/cubes to the points in question & use a very small pscale, but that only goes so far before it gets impractical.

Thanks,
Luke

**Comment by millag** [comment]
No the point/particle export isn't implemented yet. We do plan to do this in near future. Until then you can pack the geometry you want to instance and use copy/stamp workflow.

**Comment by LukeLetellier** [comment]
Thanks for the info - will do!
