### ISSUE TITLE
Setting up Environment Variables

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#159]
I like to use HQueue for cooking geometry - especially when you've got 2000+ frames to bake - as it allows me to use all of my machines to speed up the process. However, with a scene that contains Vray nodes, I'm unable to do so - as HQueue gives me several errors regarding said nodes: 

`.........................
             Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Low/VRayNodeBRDFVRayMtl1.chn.
             Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Low/VRayNodeBRDFVRayMtl1.parm.
             Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Low/VRayNodeBRDFVRayMtl1.userdata.
             Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Low/meshvertexchannel.init.
             Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Low/meshvertexchannel.def.
             Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Low/meshvertexchannel.parm.
             Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Low/meshvertexchannel.userdata.
Warning:     Bad node type found: vray_material in /obj/shopnet1.
Error:       Bad parent found (parent is not a network): obj/shopnet1/Water_Coil_Secondary/vray_material_output1.init.
-------------------` 

I'd like to work around this by setting up my environment variables correctly on my machines so that they contain all the needed Vray information when HQueue launches the program remotely.

Theoretically, this would also have the side benefit of allowing us to render Vray scenes through HQueue, which would also be very helpful on said 2000+ frame animations, as it would save a lot of time that would otherwise be spent generating & transferring the vrscene files over the network using DR. 

Would it be possible to create a short guide for the wiki describing how to setup those environment variables? I know that several other 3rd party render engines use this route for plugin integration instead of a bat launcher. The latter is much easier to use (which I definitely appreciate!) but it does have this limitation, which is rather unfortunate, as baking meshes for large scenes becomes rather tedius on a single machine. 

Thanks!
Luke

**Comment by millag** [comment]
I've updated the wiki. Let me know if that works for you...

**Comment by LukeLetellier** [comment]
Thanks for sharing!

I've set things up as follows:
[img]http://i.imgur.com/7WVZNRV.jpg[/img]

But have received two error messages:
[img]http://i.imgur.com/pvvrZey.jpg[/img]
[img]http://i.imgur.com/pvvrZey.jpg[/img]

Thoughts as to what I've typed incorrectly?

Thanks!
Luke

**Comment by millag** [comment]
@LukeLetellier Thanks for sharing. Might be better to place this info on the wiki page since I don't think many people are looking at closed issues.
