### ISSUE TITLE
Cent OS for testing V-Ray for Houdini?

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#161]
Hi,

I wanted to know if you recommend installing Cent os in order to be able to better test V-Ray for Houdini? I see that the vray dev who work on Vray for houdini seems to be working on linux instead of windows. There is some folder missing for volume rendering in the windows versin since months so my guess is that no one is testing vray for H in windows? Are you all on cent os? I never installed cent os and I still need windows for zbrush and many other apps. So I would need to do a dual boot. What do you suggest in that matter? Thanks.

**Comment by photomg** [comment]
well I'm waiting patiently for these issues to be resolved on windows ......... hope that's very soon!

**Comment by sepux** [comment]
Im testing Houdini in Windows. Im also hoping that the issues get solve soon as well.

**Comment by LukeLetellier** [comment]
I'm another Windows user that's waiting for these issues to be resolved.

**Comment by millag** [comment]
Refer to volume scene in nightlies for rendering volumes
