### ISSUE TITLE
DR Errors

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#162]
I've used Vray-DR with C4D for several years now, so I'm quite familiar with the general process, but every time I try DR rendering in H, I'm getting black buckets from my render slave. 

On the slave, I have:
- A dongle with a Vray Standalone render license & V to H license
- Vray License server installed as a service & running
- Vray standalone running in server mode

When I hit render in H, I can see all the correct entries appearing on the Vray standalone console on my slave machine as it receives the signal and goes about rendering; no errors appear of any kind - but all the buckets that it attempts to render come back black immediately in my Vray Frame Buffer. 

Not sure if this is a bug or user error. Thoughts?

Scene File: https://www.dropbox.com/s/z5zdi7bav45wsyb/DR_Debug.hiplc?dl=0

Thanks!
Luke

**Comment by LukeLetellier** [comment]
I've confirmed that it's **not** a network issue: I can render Vray lights via DR, but geometry is invisible/completely transparent. 

Result with DR **ON** : https://www.dropbox.com/s/9fx5ga157by11gk/DR_ON.jpg?dl=0
Result with DR **OFF** : https://www.dropbox.com/s/sn3wug1m4ux96w5/DR_OFF.jpg?dl=0

Test Scene: https://www.dropbox.com/s/t3k43mqi4q933ok/DR_Debug_V2.hiplc?dl=0

Thoughts?

Thanks,
Luke

**Comment by LukeLetellier** [comment]
(Closed the issue by mistake)

**Comment by LukeLetellier** [comment]
Any idea what might be causing this?

**Comment by millag** [comment]
Updated AppSDK - this should be fixed now.
