### ISSUE TITLE
Image File will not save if File Format is not appended to file name

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#164]
This will render out, but will not save to disk:
<a href="http://imgur.com/fQqn7Bz"><img src="http://i.imgur.com/fQqn7Bz.jpg" title="source: imgur.com" /></a>

This will render out, and will save to disk:
<a href="http://imgur.com/vxopDIS"><img src="http://i.imgur.com/vxopDIS.jpg" title="source: imgur.com" /></a>

It's a very easy typo to make, and without any warning at the beginning of the render, it can become a very costly mistake when you discover X hours later that you have to start all over again.

**Comment by bdancer** [comment]
This is reworked now.
