### ISSUE TITLE
MAT Context Shaders

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#166]
Hi, I just wanted to confirm that shaders created in the new /mat context in H16 does not seem to work yet.
Good thing H16 has not removed the /shop context yet, v-ray currently seems to only work there.
[H16_mat_shaders.zip](https://github.com/ChaosGroup/vray-for-houdini/files/851648/H16_mat_shaders.zip)

**Comment by Eiken** [comment]
MAT shaders would be so nice. Most artists here love the new workflow. Took barely no time at all to get some maya people going.

**Comment by Eiken** [comment]
Any news on this?

**Comment by bdancer** [comment]
@Eiken we be cool if you could send me some example scene and I'll make it work.

**Comment by Eiken** [comment]
Here is a simple hip showing how it works with mantra vs vray

With mantra both spheres render red but with vray the mat assigned shader is not used.
[vraymatexample.hip.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1060750/vraymatexample.hip.zip)

**Comment by bdancer** [comment]
@Eiken tnx!

**Comment by bdancer** [comment]
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/29f084019b5c16054a43bf4c8c5d1e7a0af18008. Will be available in the next nightly.

**Comment by Eiken** [comment]
Very nice! I'll give it a spin tomorrows
