### ISSUE TITLE
alSurface shader please!

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#168]
Could you please add the alsurface shader in Vray for houdini? Now that houdini has amazing tools character work it would add a huge wow factor when you release it to have some character render with amazing skin using alSurface and also alHair if possible. I know Vlado is working on alHair so maybe you can add it at the same time! That would be fantastic!

**Comment by StrobFX** [comment]
I see it in thee commit does it mean it's already added in the latest version? I see add: AlHair & AlSurface nodes registration?

By the way Vlado is working on a better shader for hair and will not port the AlHair in max finally. So I guess it will be better to sdo the same for V for H! 

See: https://forums.chaosgroup.com/showthread.php?87304-skin-shader-a-la-Alsurface-pleaseeee&p=731740#post731740

**Comment by bdancer** [comment]
> I see it in thee commit does it mean it's already added in the latest version?
Yes, if the build hash is equal or more the the top commit hash in the commit list.

> So I guess it will be better to do the same for V for H!
Sure, as soon as it'll be available as V-Ray Standalone plugin.

**Comment by StrobFX** [comment]
Wow ! great! it will  rock big time!

**Comment by StrobFX** [comment]
Alsurface shader in VfH it works!!!
![image](https://cloud.githubusercontent.com/assets/12475879/24386118/d0ff9224-133b-11e7-87fb-3cb3d0f9f37c.png)
