### ISSUE TITLE
Vray advanced?

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#169]
Hi, when adding a V-Ray renderer in output, in the globals I see only a "Render RT" button. Does that mean there no V-Ray advanced yet in V-Ray for Houdini?

**Comment by bdancer** [comment]
That's very strange that you see only this button, standard ROP buttons should also present there.

**Comment by bdancer** [comment]
There is also a V-Ray shelf.

**Comment by StrobFX** [comment]
Hi Andrei, I am using nightly version from 2017-03-17 on windows 7.  It seems I can render with adv when I press the shelf button "Render" but it then renders 2 times: first one with adv and a second time in rt mode it seems...

I also get a lot of crashes when trying to render. Houdini crashes as soon as I press render.

Here is how my globals look like
![vrayhglobals](https://cloud.githubusercontent.com/assets/12475879/24306652/abfca792-1097-11e7-95d3-266ad24d5783.jpg)

**Comment by StrobFX** [comment]
Also if I press the render button in the shelf it will render corectly sometime on ly one time. But then if I make changes to my render setting and I press the blue teapot in the vray frame buffer, it will rerender but without taking into account the new settings that I changed. To make it take them into account I need to click the shelf button again.

**Comment by StrobFX** [comment]
That's what I get all the time (maybe 1 time out of 5) when I press the render button in the shelf.
![greencap_000723](https://cloud.githubusercontent.com/assets/12475879/24307745/b6e49b7a-109b-11e7-9fab-1b798bd31f3a.jpg)

**Comment by StrobFX** [comment]
![greencap_000724](https://cloud.githubusercontent.com/assets/12475879/24307771/cbcfaee4-109b-11e7-97a6-5f91541f3b05.jpg)

**Comment by StrobFX** [comment]
And what do you mean by "standard rop buttons"?

**Comment by dgsantana** [comment]
Its the "display/template" that in the rop node starts the render.

Jocelyn Strob Simard <notifications@github.com> escreveu no dia sexta,
24/03/2017 às 18:25:

**Comment by StrobFX** [comment]
Ah ok sorry so there is nor render button in the globals normally.
