### ISSUE TITLE
How can we do network rendering (not DR)?

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#170]
I saw other issues here talking a bit about DR but could someone explain step by step how can we do network rendering with V-ray for Houdini. It seems it's via V-Ray standalone. Can it be done with Deadline?

**Comment by mangopipeline** [comment]
Deadline has a vray standalone plugin.
You should be able to plug it all in...

Have you tried the deadline submitter for Houdini?
I've be very surprised if you couldn't render directly through the Houdini plugin in deadline, just like Maya or max...

**Comment by StrobFX** [comment]
Ok yes at least I know I am able to submit the vrscene from the monitor. I just need to know how to output the vrscene is houdini. Is it better to output a vrscene for every frame or a sinlge vrscene for all the frames? And how?

**Comment by bdancer** [comment]
@StrobFX,  use $F in the export file name and it'll export files per-frame.
