### ISSUE TITLE
Material in viewport

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#171]
Is there a way to show material, textures and env background in viewport yet?

**Comment by hypotheticalinc** [comment]
Any news on this? I'm still very new to Houdini so not sure if I'm making a mistake or it's not implemented yet.

**Comment by bravehamster** [comment]
The Viewport in Houdini uses the OpenGL rendering engine which is completely decoupled from Mantra or any 3-rd party rendering solutions. 
You could easily add the necessary parameters to get a basic preview of your materials. 

Once you've setup a scene with a V-Ray Renderer, a light and a camera, drop a V-Ray Material in the SHOP context and apply it to your object.
Then, open the **Parameter Interface** menu.
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25700887/6af186ea-30d2-11e7-954d-162d2dab1d0d.png)

Inside, go to the **Render Properties** tab and search for Diffuse in the Filter box. Add all the parameters under the **OpenGL** tab:
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25700894/704e5fb4-30d2-11e7-8f05-778c372a1ec3.png)

There are plenty of other parameters to play with, too. I've added Specular and Displacement in addition to Diffuse.
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25700896/743f14e2-30d2-11e7-980d-ea4591437872.png)

You can then link the parameters on your V-Ray VOPs to the OpenGL parameters using relative references. 
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25700899/7856ef6e-30d2-11e7-9e34-e535d60cf1fc.png)
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25700903/7d4433b0-30d2-11e7-9a32-2451e9912aae.png)


And so on ...

It's not that convenient but you only have to do this once and you can copy the material around. I've tried making a digital asset out of it but sadly, that causes Houdini to crash. 
Keep in mind that the mapping is not 1 to 1. For instance, with OpenGL the colour texture is multiplied by the Diffuse Color parameter but with V-ray you'd need to use a Color Operations VOP with the Output Mode set to Product to get the same result.

**Comment by hypotheticalinc** [comment]
That's a great explanation, thanks for taking the time to write it out so clearly and include the screen captures!

Houdini is so powerful but at the same time makes so many simple things complicated (as a long-time 3ds Max user considering how much I can move to Houdini). I'll have a play around and see if there's some way to make this a little more automated too.

**Comment by millag** [comment]
I'm afraid our SHOP should generate opneGL shader string from the VOP network inside in order to be rendered in houdini viewport but this has not been done yet.

**Comment by hypotheticalinc** [comment]
That's great, I'll keep an eye out for that in the future releases
