### ISSUE TITLE
Gamma problem

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#172]
There seems to be something weird with the gamma in V-Ray for Houdini.
I created a scene with the same settings in max and houdini but see the results: max on top and Houdini at the bottom.
![image](https://cloud.githubusercontent.com/assets/12475879/24320052/26646838-1103-11e7-8939-9862716ce45a.png)

**Comment by StrobFX** [comment]
I found the problem: the color mapping mode is set to Color Mapping & Gamma by default, but it should be set to Color Mapping Only (no Gamma).

**Comment by StrobFX** [comment]
It's better like this! But now I wonder why Vray is faster in houdini??? :+1: 
![image](https://cloud.githubusercontent.com/assets/12475879/24320300/f3908fee-1108-11e7-8995-24ce55d52f02.png)

**Comment by StrobFX** [comment]
One thing I notice also is that in Houdini the rectangular spot (I placed it approximatively to the same place) seem to be more directional. In max I scale up the scene a lot to make it more consistent with max default units. The Rubber toy is darker and the light on the red sphere is more diffuse in max. Is there any difference in the rectangular V-ray light in max and houdini?  Or I have to check if it could be the different scale.

**Comment by Hexarage** [comment]
Colour mapping default should be ok now.
