### ISSUE TITLE
Wrong defaults in render settings

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#173]
Hi,

In the render settings I think those should be set by default:
color mapping=>adaptive threshold: 0.005
GI: brute force+light cache
Raycaster: use embree on
Bucket image sampler=> min1; max24; nt0.01

And the most important (or else the result is completely wrong):
Color Mapping=>Mode: Color Mapping only

And in the camera V-Ray Physical camera settings, please set the "use" setting to on by default too.

thanks.

**Comment by bdancer** [comment]
> color mapping=>adaptive threshold: 0.005
> GI: brute force+light cache
> Raycaster: use embree on
> Bucket image sampler=> min1;  nt0.01

This is already fixed like a week ago.

> Bucket image sampler=>  max24

Fixed with https://github.com/bdancer/plugins_desc/commit/dee2a90a214a509fbab8ba590e0a2ad952205cc5.

> And in the camera V-Ray Physical camera settings, please set the "use" setting to on by default too.

Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/c53944ba8a312922385452530f415685fa65545a.

**Comment by StrobFX** [comment]
I installed yesterday version and it was still using the old defaults. Maybe I should have uninstall everything before?

**Comment by bdancer** [comment]
Houdini doesn't reset values to defaults automatically. Try on a new scene.

**Comment by bdancer** [comment]
You should not reinstall anything, I'll check the nightly build scripts anyway.

**Comment by StrobFX** [comment]
Ok thanks. Now I saved my setting to the factory default so I would need to find how to erase that and revert.. So I can't confirm immediately.

**Comment by Mokikii** [comment]
If it helps I just installed vray for houdini  (c53944b) for the first time and I also get very weird default settings irradiance map / brute force  + image sampler 1/4.
Just out of curiosity does vray for houdini use same sampler method as vray for 3ds max since 3.3? (I think)

**Comment by bdancer** [comment]
Ok, tnx, I'll check this.

**Comment by bdancer** [comment]
I hope I've synced all the changes: https://github.com/ChaosGroup/vray-for-houdini/commit/1d63a5826bb80edc09917093458ce69f05cda210. Could you pls check some recent build?

**Comment by Mokikii** [comment]
I am not near my usual workstation so I don't have the qt4 version installed for houdini and under sidefx's daily builds I don't see 16.0.504.20 available anymore. Any chance you guys still have a downloadlink for that build Build?

**Comment by Mokikii** [comment]
Just tested the new version. The settings line up for the most part with the 3ds max default. Only differences are: Animated Noise (Lock Noise pattern) is off and under progressive the noise threshold is 0.005 in 3ds max.

**Comment by bdancer** [comment]
Should be fine in the next build: https://github.com/ChaosGroup/vray-for-houdini/commit/cbaad933d1a6b33c28a617fc00e12769d44920e7.
