### ISSUE TITLE
installation - Couldn't load DLL on Indie

### ISSUE THREAD

**Issue by hypotheticalinc** [ChaosGroup/vray-for-houdini#174]
Is Vray working on Houdini 16 Indie? I saw references on forums that it was coming but those are from a while back.

I tried running it from the latest nightlies (from March 30, 2017) 16.0.504.20 Indie. I confirmed my version of Houdini is the 16.0.504.20. I'm running the .bat file from the unzipped folder from the binaries site.

Am I doing something wrong or is this not supported?

**Comment by millag** [comment]
Are you using Houdini 16 Qt4 build?

**Comment by hypotheticalinc** [comment]
I was using the Qt5 build, and now I see that SideFX has released a new version so I can't get 504.20 in Qt4. I didn't see a place on SideFX's site to download older versions, only dailies. Is there a backlog of versions?

If not it's ok, I can wait for the plugin to get upgraded.
