### ISSUE TITLE
DR Workflow

### ISSUE THREAD

**Issue by Mokikii** [ChaosGroup/vray-for-houdini#178]
I only have experience with 3ds max DR setup so I kinda feel lost on what to do exactly to get the nodes joining my houdini renders.
What would be the steps to get the render nodes ready for DR?
I figure I have to place the vfh-###### folder onto the nodes but I also need a sdk license which I have to contact support about? (1 for every node?)
If somebody could give me a short step by step guide that would be amazing. :)

**Comment by bdancer** [comment]
@Mokikii you need to setup DR nodes in Maya way, you'll need V-Ray Standalone, then it's just "vray -server" and we also have some init scripts afair.

**Comment by Mokikii** [comment]
It's probably not the vray standalone version downloadable on the chaosgroup.com website?

**Comment by bdancer** [comment]
Exactly that one.

**Comment by Mokikii** [comment]
I am currently trying to use that one and it says that it's now in server mode waiting for requests on the same port that is set inside the vray render settings inside houdini, but the node is not joining.

**Comment by bdancer** [comment]
Check firewall.

**Comment by Mokikii** [comment]
Thanks Andrei, have it working now. 
The final issue was me being and idiot and trying to connect to the wrong node. Mixed two numbers :/
It's working now the node is joining and happily moving along. :)

**Comment by bdancer** [comment]
> If a newer standalone version is needed will that be mentioned on github?

I'll try to check for the incompatible changes, but I guess you'll figure it out faster with the error messages =)

**Comment by Mokikii** [comment]
That is most likely true :P. Still thank you again for the quick help! :)
