### ISSUE TITLE
Selfillumination Pass 

### ISSUE THREAD

**Issue by Mokikii** [ChaosGroup/vray-for-houdini#181]
I am running into some problems with the selfillumination pass.
It shows a much brighter and blown out version of the color I am using. This does for the selfillumnation inside the vraymtl and vraylightmtl
Tried fiddling with the camera but no change in the behavior.

**Comment by bdancer** [comment]
Could you post some scenes? Have you tried the same in Maya for example? Or 3ds max?

**Comment by Mokikii** [comment]
The plan was to render it in max but I prior iterations of the scene were problematic to export and those attempts that did work took really long to even begin render (spent 20min+ in updating objects via proxy).

The newer version is lighter so I could probably try it again but if possible I'd like to send you the scene via email?

**Comment by bdancer** [comment]
andrei.izrantcev@chaosgroup.com

**Comment by bdancer** [comment]
Tnx, I've received the scene, will look into it on Monday.

**Comment by Mokikii** [comment]
Thank you. :)

**Comment by Mokikii** [comment]
After disabling the denoiser render channel the self illumination pass shows correctly.

**Comment by bdancer** [comment]
Tnx, we'll check why this happening.
