### ISSUE TITLE
V-Ray for Houdini forum on forums.chaosgroup.com

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#182]
Hi,
I asked for it a long time ago but why don't you create a V4H forum on forums.chaosgroup.com? I think many people don't even know about V4H existence so it's not helping to develop it I think...

**Comment by LukeLetellier** [comment]
Agreed.

**Comment by Dentzz1** [comment]
Second on a forum would be nice.

**Comment by bdancer** [comment]
We are working on this...
