### ISSUE TITLE
Render region only from the V-Ray FB

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#185]
The render region workflow is a bit broken (I guess probably by the fact V4H must rely on V-Ray standalone). If I draw a render region and I launch the render from the shelf or the vray_renderer node, it will not take the region into account and just render the full frame.

**Comment by bdancer** [comment]
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/81cc494e9e7b146b93dbe18189486a66efeb63ac.
