### ISSUE TITLE
Problem with opacity when trying to render a frame range of smoke with phxshadersim

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#187]
When I render a single frame the smoke opacity is correct (trying to use 0.03 for example) but when I try to render a frame sequence, it renders like if the smoke opacity was set to 1.

Can I send you a test scene if you can check it up?

If I render the current frame I get this:
![image](https://cloud.githubusercontent.com/assets/12475879/24843255/1b56b3ce-1d6f-11e7-8626-e101bd2b89a8.png)
But rendering the frame range will give this:
![image](https://cloud.githubusercontent.com/assets/12475879/24843261/287c1440-1d6f-11e7-9b76-a0ef5f740f75.png)

**Comment by Hexarage** [comment]
Could you please provide the test scene you mentioned?

**Comment by StrobFX** [comment]
Here it is (with 3 frames of the cache: http://www.phylacterecola.com/strob/chaosgroupV4Hgithub/VrayPyro/

**Comment by StrobFX** [comment]
Any update on this?

**Comment by bdancer** [comment]
Not yet, sorry.

**Comment by poseidon4o** [comment]
@StrobFX this should be fixed with next nightly build.

**Comment by StrobFX** [comment]
Great thanks!!!!
