### ISSUE TITLE
Loading VDB with the VRayNodePhxShaderCache is very slow.

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#188]
When I load a VDB in houdini with the VRayNodePhxShaderCache, it takes a lot of time (up to one hour). loading the same VDB with the vray volume grid in max is very fast (1 or 2 sec). Rendering is also a bit slower (35 sec in houdini instead of 21 sec in max. with the same setting for VRay as well as the smoke shader)

**Comment by bdancer** [comment]
Any chance to see the scene with the vdb file?

**Comment by StrobFX** [comment]
Hi bdancer, yes it's over there: http://www.phylacterecola.com/strob/chaosgroupV4Hgithub/VrayPyro/
I uploaded 3 frame of the VDB. but you could also simulate it by just switching the right nodes.

**Comment by bdancer** [comment]
Tnx!

**Comment by StrobFX** [comment]
And sorry if I bring up so many issues, you are probably already aware of many of them. But just trying to pinpoint everything that is stopping me in my tests.

**Comment by bdancer** [comment]
@StrobFX, that's perfectly fine - thanks for the testing!
