### ISSUE TITLE
Vray PhysicalCam settings not working

### ISSUE THREAD

**Issue by Mokikii** [ChaosGroup/vray-for-houdini#189]
When creating a camera and using the VrayPhysicalCam shelf tool on it, changing vraycam settings won't do anything at least I can't see any noticeable change. No matter if I change the focal length or shutter speed.
"Use" checkbox is ticked by default.

**Comment by bravehamster** [comment]
Hey there, there's a tickbox at the bottom of the parameters pane that you need to click in order to enable the physical cam properties. Cheers!
