### ISSUE TITLE
New versions in the nightlies sections won't load

### ISSUE THREAD

**Issue by Mokikii** [ChaosGroup/vray-for-houdini#191]
Noticed that when I try to try out one of the newer version (currently: e0ae8d2) I get an error saying: "Couldn't load .../dso/vray_for_houdini.dll. This is probably because this file was intended for use with a different version of Houdini."

Version number (16.0.557) is the same and it happens with the QT4 and QT5 version.

**Comment by bdancer** [comment]
Try the solution from here https://github.com/ChaosGroup/vray-for-houdini/issues/160 (about removing dbghelp.dll):

> can you try renaming/moving C:\Program Files\Side Effects Software\Houdini 16.0.584\bin\dbghelp.dll

**Comment by Mokikii** [comment]
That fixed it. Sorry I was searching through the github issues but somehow ignored this thread.
