### ISSUE TITLE
Phoenix shader tutorial

### ISSUE THREAD

**Issue by bravehamster** [ChaosGroup/vray-for-houdini#192]
After having a bit of trouble figuring things out, I decided to create a short tutorial on rendering Houdini volume sims using Vray and the Vray Phx shader. 
I've tried using the Houdini Fire/Smoke preset on the Phx Shader node and this is the result : 
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538577/f26ccce6-2c4b-11e7-84d2-9ce368377e59.png)

I'm going to assume that you have a simulation already prepared and only import/export and material setup will be discussed.

It's a good idea to let the DOP Import Fields SOP calculate the min/max values for your fields. You are going to need those in the shader.
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538608/144a97b2-2c4c-11e7-967e-3eda4040b17d.png)

Converting to VDB and exporting is straightforward

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538615/1d115566-2c4c-11e7-8d12-514879acf653.png)
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538617/1ebef166-2c4c-11e7-82a4-5f52a7a81036.png)

The VDBs can be imported using a V-Ray PhxShaderCache SOP. 
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538624/229937b0-2c4c-11e7-8c3e-fe1642e3318b.png)

Note the Temperature mapping.
As you may already know, Houdini's Pyro solver uses the fuel and temperature to produce a burn field, the result of which is a heat field. The heat is, presumably, the actual fire/flames.
Of course, there's nothing stopping you from using the temperature to represent the fire.
Here's a couple of screenshots to illustrate the difference (heat and temperature respectively, visualized as density) :

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538631/2921cd04-2c4c-11e7-8e5e-23454d016f09.png)

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538636/2ae25b90-2c4c-11e7-8e4a-02f606912dad.png)

Back on topic, set the display and render flags to the V-Ray PhxShaderCache SOP. 
In the SHOP context, create a V-Ray Material.
Inside, replace the VRayNodeBRDFVRayMtl1 with a Phoenix Shader Sim VOP.
In OBJ, set the material parameter on your Geometry node to point to the material we just created.

If you were to try to render now (assuming that you already have a V-Ray render node and a camera set up), you'll realize that the render view is empty.
The reason being the defaults on the PhxShaderSim VOP.
By default, the opacity is set to 0. Set it to 1. 

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538640/2f06f1b8-2c4c-11e7-9415-e1d56f2465d9.png)

You'll now find out that the smoke is blue for no apparent reason. This is most likely a bug, and will hopefully be resolved in the near future.
For now, the way to deal with this is to go to the Smoke Color tab, and set the Diffuse Input to Smoke (or any other option that allows you to edit the Color Gradient Ramp).

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538643/3229b808-2c4c-11e7-8572-89b8a820c036.png)

Now click on the Color Gradient button at the bottom and set it to whatever suits your needs. I will go with a simple gray-to-white gradient. 
You need to do that even if you only want to use the Constant Color option in the Diffuse Input parameter. What happens in that case is the color at x=0 from the Gradient Graph is used as the color for the entire volume. The Constant Color parameter seems to be doing nothing. 

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538656/379cb6c8-2c4c-11e7-9388-8e7beacf5e86.png)

The Shadow Strength parameter controls the opacity of the shadows cast by the volume. Screenshots below:

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538703/6d8499d6-2c4c-11e7-9a72-bd54487e03eb.png)
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538705/6f7527a6-2c4c-11e7-9d15-f6d1e6ce4857.png)

The Own Light Scatter Mult and External Scatter Mult control the internal light scattering of the volume from the illumination produced by the fire and external light sources (such as the lights in your scene) respectively. You'd likely want lower scattering values and higher smoke opacity for thick smoke filled with particulates, and higher scattering + lower opacity for thin smoke.
There seem to be no forward/backwards scattering controls at the time of writing this.
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538708/72e0ba90-2c4c-11e7-8ae3-9399ba578403.png)
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538714/74074088-2c4c-11e7-80e5-31033c2d8ddd.png)
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538716/758fcf06-2c4c-11e7-858f-2436eb39f751.png)

The Master Multiplier parameter is an overall multiplier for the color of the smoke.

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538723/7c26d602-2c4c-11e7-8b22-e2747ba65669.png)

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538724/7eac4c68-2c4c-11e7-9043-308458764077.png)

Let's go to the Fire tab. 
The reason you see nothing resembling fire in your render is once again the default values that come with the PhxShader VOP. While suitable for rendering PhoenixFD simulations, we need to remap them to get our Pyro sims to render properly. 
The parameters we're most interested in are the Base On dropdown, the Fire Opacity and the Fire Luminance button.

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538726/84e77bc0-2c4c-11e7-9ece-b9abd78501d8.png)

The Base On Temperature option is referring to the temperature field on the PhoenixShaderSimCache SOP. Recall that we remapped the heat field to be used as temperature by the shader.
Remember those min/max values that we asked the DOP Import Fields SOP to calculate for us ? We're going to make use of them now.
I brought in my VDBs in SOPs using a File SOP and scrubbed through the timeline, taking note of the values for my heat field in the Geometry Spreadsheet under the Primitives tab.

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538730/8d10781a-2c4c-11e7-9748-d228a24684be.png)

In my case the max value is around 2 so I will go with that.

Click on the Fire Luminance button. It should open a Ramp that is set by default to output [0-1] for x [800-3000]. The x is our heat field values which are in the range of 0-2. Had we opted in for using Temperature from the Pyro sim instead, the values would likely be in the [0-20] range but still nowhere near 800, or 3000 for that matter.

Left-click on the first point and set it to x=0, y=0
Set the other point to x=2 , y=1
Don't forget to move the color ticks at the top as well. Those determine the color of your fire based on value of the heat field.
To scale the graph up-down and left-to-right, press Shift + Middle mouse button and drag.

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538741/961e4d92-2c4c-11e7-89e5-79d2726dc812.png)

You should now have something along the lines of this : 

![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538750/9a088292-2c4c-11e7-858a-80ea3f98132a.png)

Make sure to play with the Opacity mode and the two multipliers - those tend to change the look of the volume substantially.

The physically based option is unfortunately not available to us when using this workflow. I'm going to assume it uses real world temperature values, and if we wanted to use that, we would have to scale the heat field in SOPs by multiplying it * 2000 in a Volume Wrangle SOP, for example. 

The Light tab contains controls for the self-illumination of the volume, and the illumination in your scene caused by the fire. Setting the Light Power on Self to 5 gives us this result.
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538755/9ef3fd5e-2c4c-11e7-82a6-a979a1797dfc.png)

The Light Power on Scene controls the intensity of the light cast into your scene, similar to the the intensity controls on regular V-Ray lights. The same goes for the Decay Type parameter.
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538760/a3a9e106-2c4c-11e7-9bd7-36e1375c1dae.png)
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538767/a635d5ba-2c4c-11e7-9cec-2169e4e2eeba.png)

The Subdivs parameter controls the amount of AA / Shading rays and if your volume renders noisy, you may want to consider increasing those. 
To render an animation make sure to enable the Img File Needframenumber option on the V-Ray ROP. 
This will append the frame number before the file extension, with four zeroes of padding (by default). If you don't do that you'll end up with subsequent frames overwriting each-other.
Make sure to set the Dir Name properly as well.
![screenclip](https://cloud.githubusercontent.com/assets/20627168/25538771/aa7bd926-2c4c-11e7-88bb-ba3a577fae67.png)

That's it. Hit render and go grab a cup of tea.

**Comment by bdancer** [comment]
Great stuff!
I've copy-pasted it here https://github.com/ChaosGroup/vray-for-houdini/wiki/Tutorials, feel free to edit it there.

**Comment by galagast** [comment]
Thank you for such a detailed tutorial!
