### ISSUE TITLE
Packed Primitives: Random Colors

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#194]
Hi, anyone knows the proper workflow for vray to render packed primitves, but use custom attributes, for example to randomize diffuse colors?
In Mantra, there's a Render State VOP which would let me do this. It also means that I only need to assign a single shader.

Although I'm able to assign shaders per pack packed primitve, it means that I would need to build multiple shaders for each variation.

**Comment by galagast** [comment]
Nevermind, got something working using just the Material Overrides 👍 

![image](https://cloud.githubusercontent.com/assets/16534677/25772300/7090d71c-329a-11e7-806c-dd8f392d92a7.png)
Attaching the file in case anyone wants to check it out.
H16.0.557 Indie - [packed_geos_random_color.zip](https://github.com/ChaosGroup/vray-for-houdini/files/980908/packed_geos_random_color.zip)

**Comment by blented** [comment]
This issue has a fair bit of info about how attributes on packed geo work:
https://github.com/ChaosGroup/vray-for-houdini/issues/204
