### ISSUE TITLE
 help with the install

### ISSUE THREAD

**Issue by debneyink** [ChaosGroup/vray-for-houdini#197]
so chaos kindly gave me the stuff i need for H16 and vray, I'm not a coder but I'm pretty good at 3D so bare with me!

 I followed this:
My installation goes like this (Windows 10):
Download the latest nightly build.
Extract the file to any location.
Inside the extracted file, locate the batch file and execute it.
I've got the right build but when hitting the batch file it tells me its not the right version (which it is) 

so houdini loads up and there's a vray shelf (just the rendering stuff top right) but if i click on it i then get this: no attribute instances

AttributeError: 'NoneType' object has no attribute 'instances'

anyone know what this means? 

I really want to get this going!

**Comment by bdancer** [comment]
How have you solved this? What was the reason?

**Comment by debneyink** [comment]
Well i think its the type of install i had it needs QT4? am in the middle of a reformat back to windows 7...so hopefully ill get things moving...

**Comment by bdancer** [comment]
Since some time we only ship Qt5 builds for Houdini 16.

**Comment by debneyink** [comment]
ah yes i meant qt5 havent looked at houdini for a while

**Comment by bdancer** [comment]
> I've got the right build but when hitting the batch file it tells me its not the right version (which it is)

Could you show the exact message?
Also please check this issue and dbghelp.dll fix: https://github.com/ChaosGroup/vray-for-houdini/issues/160#issuecomment-295802493

**Comment by debneyink** [comment]
I can't now, I've reinstalled windows 7. 10 was driving me nuts, so am starting fresh...

**Comment by debneyink** [comment]
so which do i get I'm guessing the one that doesn't say QT is QT5?

https://www.sidefx.com/download/daily-builds/#category-gold

https://www.sidefx.com/download/houdini-qt4-for-win/


i just tried to install a version in windows 7 but it wont run due to not 'the program cant start because api-ms-win-crt-runtime-L1-1-0.dll is missing....ive tried googling every possible scenario and downloaded every C++,  vc_redist 64, x86 etc etc but nothings working....  i cant even get a splash page now :(

I'm sure you got better things to do!

**Comment by bdancer** [comment]
Well, yeh, better write to sidefx about Houdini installation =)

**Comment by debneyink** [comment]
does the vray plugin work with houdini indie?

**Comment by dgsantana** [comment]
Yes. With the Indie limitations.

A quinta, 11/05/2017, 23:26, debneyink <notifications@github.com> escreveu:

**Comment by debneyink** [comment]
so yeah back to where i started, latest version of vray houdini the same...

(127) couldnt load
points to my vray4 hnon file 

this is probably because this file was intended for use with a different version of houdini

**Comment by debneyink** [comment]
so i just click ok and houdini loads...
then im in houdini and i can find one shelf... 

with Render, REnder RT, VFB...etc on the top

click on the Render tool 'Nonetype' object has no attribute 'instances'

**Comment by bdancer** [comment]
Could you pls write the exact Houdini build version? May be some API has changed and we need to recompile.

**Comment by debneyink** [comment]
so finally got it all working...houdini indie 16.0.557 with vray sdk and running the plugin on houdini...i think
![vrayhoudini_](https://cloud.githubusercontent.com/assets/25094141/26039387/c522dbf8-395d-11e7-9c41-879fc3a66c8c.JPG)

but all I'm seeing are the two shelves?  (see image) i was assuming there'd be materials lights all the goodies? also when i hit the render button all i get is what you can see on the houdini console
What am i doing wrong?
thanks..

**Comment by debneyink** [comment]
ok so I've figured out where everything is!! :) only problem seems to be i cant render anything...

**Comment by bdancer** [comment]
Well check the full log, that's just the end of it. Probably the license is not found.

**Comment by simonreeves** [comment]
So what steps did you take to get it to work?

**Comment by debneyink** [comment]
I haven't yet! spent nearly a week reinstalling windows 7 and getting houdini to work...

**Comment by debneyink** [comment]
ok so I'm now working from my laptop on my holiday. I don't have a license for vray on it but I have the sdk (valid till oct) from chaosgroup can I use vray for houdini without the license or dongle? I'm pretty soon not going to have internet either. if not then ill wait till i get back to the office :)

**Comment by bdancer** [comment]
@debneyink You'll need V-Ray licenses.
