### ISSUE TITLE
Volumes // Smoke Always Blue

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#198]
When rendering smoke from both the example volume scene and a fresh Houdini 16 scene the smoke is always blue.  I've attempted setting smoke color to constant w/ a bright green color and still get blue smoke.  Tested in Houdini 15 and 16.

Houdini 16.557, Windows 10
Scene:
https://drive.google.com/file/d/0B-R03L35FWUScVJUeWtnbzFvZ0k/view?usp=sharing

Single frame of the cache:
https://drive.google.com/file/d/0B-R03L35FWUSb0hpNVpXT1ZhTmc/view?usp=sharing

Render:
<img width="461" alt="bluesmoke" src="https://cloud.githubusercontent.com/assets/1403171/26318197/37847c80-3ecf-11e7-934b-38dc58a7a4f4.png">

**Comment by bravehamster** [comment]
Hey!
Please check this out: https://github.com/ChaosGroup/vray-for-houdini/wiki/Phoenix-Shader

You need to set the smoke color to gradient and edit the ramp.

**Comment by blented** [comment]
Fantastic! Thanks for the detailed write-up, answered several of the other questions I had as well.

Gonna leave the issue open as it seems like it still should be fixed, but appreciate the workaround.

Cheers :)

**Comment by Hexarage** [comment]
It has been fixed in the latest builds.
