### ISSUE TITLE
Particle Support

### ISSUE THREAD

**Issue by sepux** [ChaosGroup/vray-for-houdini#200]
Hi, 
I was wondering if you guys will support point particle? without have to copy. Just like Mantra or now Redshift does?

Thank You.

**Comment by bdancer** [comment]
@sepux pls upload some sample scene and I'll check why it's not rendered properly.

**Comment by sepux** [comment]
Here is a very simple scene, but as you can see Redshift already support this. Im not copying spheres into the points.
I use the same scene in Redshift.

https://drive.google.com/open?id=0B6eO2VWNirUTQ0FLNXI3OVVScVE

![csssam](https://user-images.githubusercontent.com/20706047/27067601-8bc86200-4fc0-11e7-8177-7916803b431a.gif)

**Comment by bdancer** [comment]
@sepux try today's nightly.

**Comment by bravehamster** [comment]
To avoid opening a new issue, as of now there seems to be no way to control the color, pscale or opacity of the particles on a per-point basis using user attributes in the V-Ray Material.
http://i.imgur.com/UBTppJ1.png

It'd be really cool if you guys could add that functionality in the near future.

**Comment by bdancer** [comment]
@bravehamster could you send me this scene?

**Comment by bdancer** [comment]
I've [added](https://github.com/ChaosGroup/vray-for-houdini/commit/0a649d0c1271232ac6d36b03a40cbac621f7d72c) export of Cd, Alpha and pscale attributes, but instead of TexUserColor you'll need to use TexParticleSampler.

**Comment by bravehamster** [comment]
Sadly, the particle render color doesn't make sense. 
![particleshadervray](https://user-images.githubusercontent.com/20627168/27259673-38d7ff78-5421-11e7-8988-3017b8c3536b.jpg)

I went though the code quickly and I think the issue might be here:

>if (cdHndl.isValid()) {
 				const UT_Vector3F &cd = cdHndl.get(ptOff);
 				color[positionsIdx].r = cd.x();
 				color[positionsIdx].g = cd.y();
 				**color[positionsIdx].g = cd.z();**
 			}


Scene file:  https://drive.google.com/open?id=0B1YJxA06WbiZbkxzYlJ5Q1pSVnM

**Comment by bdancer** [comment]
@bravehamster I've pushed this yesterday https://github.com/ChaosGroup/vray-for-houdini/commit/9129ec21275cc76c1e15c0febe8191e0c5e6355d

**Comment by bdancer** [comment]
@bravehamster I've updated the nightly builds.

**Comment by tinyhawkus** [comment]
Has anyone tried caching out to disk as Alembic and loading in via Vray proxy? I can't get it to work.
Alembic loader will render fine, but not as delayed load, so Vray Proxy loader is what I need to use.
We do this at work into Vray for Maya, so I know it's possible.

**Comment by bdancer** [comment]
@tinyhawkus is this related to particles? Or it's a separate issue? Could you pls make a separate issue and update a scene there?

**Comment by tinyhawkus** [comment]
I think it's part of the general particles rendering side of things.
Supporting point rendering is only part of it, being able to delayed load (Vray proxy) points
that will have pscale, opactity, and color picked up are crucial. 
Currently it works fine picking up these attrs if the data is live in the scene. But delayed load Alembic
doesn't work, hence needing to use Vray proxy. None of us are going to want to have to load the whole
cache live. Would you like me to make a new issue?

**Comment by bdancer** [comment]
@tinyhawkus well, I have this scene which seems to work for me:
![vfh_alembic_particles](https://user-images.githubusercontent.com/319784/27831322-d56e26c4-60d2-11e7-9432-0ce031d683bc.png)
If you need smth else then a separate issue with scene attached is much appreciated.

**Comment by sepux** [comment]
Is it possible to add more primitives to the particle tech, not just spheres. Like a box, tubes, etc. So the user can choose in case that something other than a sphere is needed, for example sugar, grain, etc.

**Comment by bdancer** [comment]
@sepux there are no plans this,  but you could use point instancing with any mesh you like.
