### ISSUE TITLE
VDB rendering not working at all in H16.0.600

### ISSUE THREAD

**Issue by tinyhawkus** [ChaosGroup/vray-for-houdini#201]
Hello,

I cannot seem to get any volumes rendering, using the latest build (17th June).
Either using the phx shader in the mat context, or in shops inside a material wired
into a material output. I can see the preview volume in the viewport using the phx 
shader cache. I've followed all the settings as outlined on here, but still nothing volume-wise
is rendering. Using: vfh-744-c326ff3-hfs16.0.600-qt5-windows. 
Do you guys have a working H16.0.600 volume test scene?

**Comment by bdancer** [comment]
Check this https://github.com/ChaosGroup/vray-for-houdini/wiki/Phoenix-Shader and check for errors in console.

**Comment by bravehamster** [comment]
I've tested the builds from June 15th and June 17th - both have issues with rendering volumes just as @tinyhawkus  has described.

The build from June 12th works fine.

I can use the build from June 12th to render a scene made with the build from June 15th and the volume renders fine. The other way around doesn't work. Not sure what to make out of this but thought it might save you a minute or two.

Files here: https://drive.google.com/open?id=0B1YJxA06WbiZWjMtVWhNZXNkSkU

(using $HIP doesn't work for me, you'll need to point the VolumeShaderCache SOP to the .vdb file in the geo folder)

Here is the full output of the console:

> V-Ray For Houdini|    Info| Loading Phoenix cache loader plugins from "C:\Program Files\Chaos Group\V-Ray\vfh-5fd0343\\vfh_home\vfh_lib"...
V-Ray For Houdini|    Info| Build 5fd0343 from Jun 15 2017, 18:57:37
V-Ray For Houdini|    Info| Parse plugin description data...
V-Ray For Houdini|   Debug| VRayPluginRenderer()
V-Ray For Houdini|   Debug| VRayExporter()
V-Ray For Houdini|   Debug| VRayRendererNode()
V-Ray For Houdini|    Info| phoenixcache cookMySop(0.000)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
V-Ray For Houdini|    Info| Loading cache took 174ms
V-Ray For Houdini|    Info| Expanding channel 'Smoke' took 0ms, extracting took 6ms
V-Ray For Houdini|    Info| Expanding channel 'Temperature' took 0ms, extracting took 5ms
V-Ray For Houdini|    Info| Expanding channel 'Velocity X' took 0ms, extracting took 3ms
V-Ray For Houdini|    Info| Expanding channel 'Velocity Y' took 0ms, extracting took 2ms
V-Ray For Houdini|    Info| Expanding channel 'Velocity Z' took 0ms, extracting took 2ms
V-Ray For Houdini|    Info| Generating packed prim 21ms
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
V-Ray For Houdini|   Debug| VRayRendererNode::startRender(1, 0.000, 0.000)
V-Ray For Houdini|   Debug| VRayRendererNode::initSession(0, 1, 0.000f, 0.000)
V-Ray For Houdini|    Info| Using V-Ray AppSDK 1.21.00 0c26175 [Adv dev] Jun  7 2017 18:54:41
V-Ray For Houdini|    Info| Using V-Ray 3.57.01 d0d1f31 Jun  7 2017 18:54:41
V-Ray For Houdini|   Debug| VRayExporter::setAnimation(0)
V-Ray For Houdini|   Debug| VRayRendererNode::renderFrame(0.000)
V-Ray For Houdini|   Debug| VRayExporter::exportFrame(1.000)
V-Ray For Houdini|   Debug| VRayExporter::clearKeyFrames(1.000)
V-Ray For Houdini|   Debug| VRayExporter::exportScene(1.000)
V-Ray For Houdini|   Debug| VRayExporter::exportView()
V-Ray For Houdini| Warning| VRayExporter::exportView: Reseting view plugins...
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "settingsCamera" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "settingsCameraDof" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "stereoSettings" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "cameraPhysical" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "cameraDefault" is not found!
V-Ray For Houdini|    Info| VRayExporter::setRenderSize(1280, 720)
V-Ray For Houdini|    Info|   Render SOP: VRayNodePhxShaderCache:"volume"
**V-Ray For Houdini|   Error| Can'f find shop node for Cache@/obj/volume/phoenixcache|VRayVolumeGridRef.0**
V-Ray For Houdini|    Info| Exporting material output "vray_material_output1"...
V-Ray For Houdini|   Debug| VRayExporter::renderFrame(1.000)
V-Ray For Houdini|    Info| Starting render for frame 1.000...
V-Ray For Houdini|   Debug| VRayRendererNode::endRender()
V-Ray For Houdini|   Debug| VRayExporter::exportEnd()
V-Ray For Houdini|    Info| V-Ray: Preparing renderer...
V-Ray For Houdini|    Info| V-Ray: Using Intel Embree ray server
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 3.8% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 69.2% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 100.0% 
V-Ray For Houdini|    Info| V-Ray: 1 lights found.
V-Ray For Houdini|    Info| V-Ray: Using adaptive light evaluation with 8 lights.
V-Ray For Houdini|    Info| V-Ray: Max ray intensity is enabled: rendered result may have incorrect brightness.
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 0.0% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 76.9% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 84.6% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 92.3% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 100.0% 
V-Ray For Houdini|Progress| V-Ray: Compiling geometry... 0.0% 
V-Ray For Houdini|Progress| V-Ray: Compiling geometry... 100.0% 
V-Ray For Houdini|    Info| V-Ray: Using embree ray tracing.
V-Ray For Houdini|    Info| V-Ray: Building embree static trees took 0 milliseconds
V-Ray For Houdini|    Info| V-Ray: Embree dynamic geometry tree contains 0 primitives.
V-Ray For Houdini|    Info| V-Ray: Embree dynamic geometry tree built in 0.83 ms.
V-Ray For Houdini|    Info| V-Ray: Embree dynamic geometry tree takes 0.00 MB.
V-Ray For Houdini|    Info| V-Ray: Using 0.53 MB for adaptive lights buffer
V-Ray For Houdini|    Info| V-Ray: Tracing 1000000 image samples for light cache in 64 passes.
V-Ray For Houdini|    Info| V-Ray: Using 35.16 MB for light cache preview buffer
V-Ray For Houdini|Progress| V-Ray: Building light cache... 12.1% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 24.6% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 36.3% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 49.9% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 62.0% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 74.7% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 87.8% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 100.0% 
V-Ray For Houdini|Progress| V-Ray: Merging light cache passes... 100.0% 
V-Ray For Houdini|    Info| V-Ray: Light cache contains 0 samples.
V-Ray For Houdini|    Info| V-Ray: Light cache base memory usage is 0.0 MB.
V-Ray For Houdini|Progress| V-Ray: Prefiltering light cache... -nan(ind)% 
V-Ray For Houdini|    Info| V-Ray: Average rays per light cache sample: -nan(ind) (min 2147483647, max 0)
V-Ray For Houdini|Progress| V-Ray: Rendering image... 0.0% 
V-Ray For Houdini|    Info| V-Ray: Start progressive rendering, server mode 0, perform rendering 1
V-Ray For Houdini|    Info| V-Ray: Progressive sampling base buffer memory usage: 81.13 MB
V-Ray For Houdini|Progress| V-Ray: Rendering image (pass 0) 1.0% 
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.142857 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.090909 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.052632 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.028571 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.014925 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.007634 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Final noise threshold set: 0.005000
V-Ray For Houdini|    Info| V-Ray: Progressive rendering finished: specified noise level reached
V-Ray For Houdini|Progress| V-Ray: Rendering image (pass 1) 70.0% 
V-Ray For Houdini|    Info| V-Ray: Sampling level reached: 1.00 subdivs (1 passes)
V-Ray For Houdini|Progress| V-Ray: Rendering image (pass 1) 100.0% 
V-Ray For Houdini|    Info| V-Ray: Number of raycasts: 2126426 (2.31 per pixel)
V-Ray For Houdini|    Info| V-Ray: Camera rays: 2126426 (2.31 per pixel)
V-Ray For Houdini|    Info| V-Ray: Shadow rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: GI rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Reflection rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Refraction rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Unshaded rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Number of light evaluations: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Maximum memory usage for resman: 0.00 MB
V-Ray For Houdini|    Info| V-Ray: Number of intersectable primitives: 2
V-Ray For Houdini|    Info| V-Ray: SD triangles: 2
V-Ray For Houdini|    Info| V-Ray: MB triangles: 0
V-Ray For Houdini|    Info| V-Ray: Static primitives: 0
V-Ray For Houdini|    Info| V-Ray: Moving primitives: 0
V-Ray For Houdini|    Info| V-Ray: Infinite primitives: 0
V-Ray For Houdini|    Info| V-Ray: Static hair segments: 0
V-Ray For Houdini|    Info| V-Ray: Moving hair segments: 0

**Comment by tinyhawkus** [comment]
Interesting. I had used that example guide to build my scene, that's what is driving me nuts.
I tried the June 12th build, but I get the (127) couldn't load... This is probably because this file was
intended for use with a different version of Houdini.

I have H16.0.600 with the qt5 build of vfh. vfh-711-e7afb81-hfs16.0.600-qt5-windows.zip
I actually had to go through a few builds to find one that didn't cause that error.

**Comment by tinyhawkus** [comment]
I've had to go to May 31st build for H16.0.557 to get your test scene working.
My observations;
The lack of forward/backward scattering control is not good.
There isn't control for self shadowing density, just the shadows cast by the volume.
No density remapping range option, and the opacity curve UI is very simplistic.

In the Mantra pyro shader, those features mentioned above pretty much drive the
look of the volume, so at this stage, I'm not very confident of being able to come 
anywhere near matching the look generated by Mantra. 

Are there plans to extend the volume shader with features like I've mentioned?

**Comment by bdancer** [comment]
```
V-Ray For Houdini| Error| Can'f find shop node for Cache@/obj/volume/phoenixcache|VRayVolumeGridRef.0
```

This probably comes from my changes to support MAT context, I'll fix this on Monday.

> Are there plans to extend the volume shader with features like I've mentioned?

I'm utilizing [volume rendering plugins from the Phoenix project](https://docs.chaosgroup.com/display/VRAY3MAYA/Volumetric+Grid+%7C+VRayVolumeGrid), so I'll have to ask Phoenix devs about this.

**Comment by bdancer** [comment]
```
V-Ray For Houdini| Error| Can'f find shop node for Cache@/obj/volume/phoenixcache|VRayVolumeGridRef.0
```
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/10c998d4ba7937051af35ee7bf39a04f5cb61b42. Nightlies are rebuilding.

**Comment by tinyhawkus** [comment]
It's working now with today's build. In SHOP's context, but not MAT context. I'm still getting the unsupported VDB file format (expected version 223 or earlier, got version 224). It's rendering fine though.
A thought going forward; You are going to have to add a viewport reduction or delayed load option
as having a high voxel count volume being drawn in the viewport is murder. 
Thanks for fixing that issue!!!

**Comment by bdancer** [comment]
> In SHOP's context, but not MAT context. 

There are no plans to support MAX context for Phoenix atm.

> I'm still getting the unsupported VDB file format (expected version 223 or earlier, got version 224).

This probably comes from Phoenix plugins, I'll ask Phoenix devs.

> You are going to have to add a viewport reduction or delayed load option
> as having a high voxel count volume being drawn in the viewport is murder.

This could be done.

**Comment by StrobFX** [comment]
So what was the solution to get something rendering. I can't render volume right now. I could before and I also double check with the tutorial you linked just in case, but still nothing.

**Comment by bdancer** [comment]
@StrobFX what does the render log says?

**Comment by bdancer** [comment]
Btw, MAT context is supported now.

**Comment by tinyhawkus** [comment]
@StrobFX what build are you using? I'll check the current nightly and see if I have the same issue.
Great that MAT context is supported! Any news on viewport display options and delayed load?

**Comment by StrobFX** [comment]
I use vfh-4b70a9c from 2017-07-15

and here is the output from the console:
V-Ray For Houdini|   Debug| VRayRendererNode::startRender(1, 1.958, 1.958)
V-Ray For Houdini|   Debug| VRayRendererNode::initSession(0, 1, 1.958f, 1.958)
V-Ray For Houdini|   Debug| newVRayInit()
V-Ray For Houdini|   Debug| VRayExporter::setAnimation(0)
V-Ray For Houdini|   Debug| VRayRendererNode::renderFrame(1.958)
V-Ray For Houdini|   Debug| VRayExporter::exportFrame(48.000)
V-Ray For Houdini|   Debug| VRayExporter::clearKeyFrames(48.000)
V-Ray For Houdini|   Debug| VRayExporter::exportScene(48.000)
V-Ray For Houdini|   Debug| VRayExporter::exportView()
V-Ray For Houdini| Warning| VRayExporter::exportView: Reseting view plugins...
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "settingsCamera" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "settingsCameraDof" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "stereoSettings" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "cameraPhysical" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "cameraDefault" is not found!
V-Ray For Houdini|    Info| VRayExporter::setRenderSize(1280, 720)
V-Ray For Houdini|   Debug| Exporting OBJ: sphere_object1_source [geo]
V-Ray For Houdini|   Debug| Exporting OBJ: pyro_import [geo]
V-Ray For Houdini|   Debug| Exporting OBJ: vraylightrectangle [VRayNodeLightRectangle]
V-Ray For Houdini|   Debug| VRayExporter::renderFrame(48.000)
V-Ray For Houdini|    Info| Starting render for frame 48.000...
V-Ray For Houdini|   Debug| VRayRendererNode::endRender()
V-Ray For Houdini|   Debug| VRayExporter::exportEnd()
V-Ray For Houdini|    Info| V-Ray: Preparing renderer...
V-Ray For Houdini|    Info| V-Ray: Using Intel Embree ray server
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 0.0% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 70.8% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 87.5% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 91.7% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for rendering... 100.0% 

V-Ray For Houdini|    Info| V-Ray: 1 lights found.
V-Ray For Houdini|    Info| V-Ray: Using adaptive light evaluation with 8 lights.
V-Ray For Houdini|    Info| V-Ray: Max ray intensity is enabled: rendered result may have incorrect brightness.
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 0.0% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 37.5% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 70.8% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 91.7% 
V-Ray For Houdini|Progress| V-Ray: Preparing scene for frame... 100.0% 

V-Ray For Houdini|Progress| V-Ray: Compiling geometry... 4.2% 
V-Ray For Houdini|Progress| V-Ray: Compiling geometry... 100.0% 

V-Ray For Houdini|    Info| V-Ray: Using embree ray tracing.
V-Ray For Houdini|    Info| V-Ray: Building embree static trees took 99 milliseconds
V-Ray For Houdini|    Info| V-Ray: Embree dynamic geometry tree contains 0 primitives.
V-Ray For Houdini|    Info| V-Ray: Embree dynamic geometry tree built in 103.19 ms.
V-Ray For Houdini|    Info| V-Ray: Embree dynamic geometry tree takes 0.00 MB.
V-Ray For Houdini|    Info| V-Ray: Using 0.53 MB for adaptive lights buffer
V-Ray For Houdini|    Info| V-Ray: Tracing 1000000 image samples for light cache in 64 passes.
V-Ray For Houdini|    Info| V-Ray: Using 35.16 MB for light cache preview buffer
V-Ray For Houdini|Progress| V-Ray: Building light cache... 0.0% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 5.3% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 14.4% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 25.3% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 35.5% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 43.3% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 44.6% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 55.8% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 59.6% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 67.3% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 59.6% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 54.2% 
V-Ray For Houdini|Progress| V-Ray: Building light cache... 100.0% 

V-Ray For Houdini|Progress| V-Ray: Merging light cache passes... 100.0% 

V-Ray For Houdini|    Info| V-Ray: Light cache contains 0 samples.
V-Ray For Houdini|    Info| V-Ray: Light cache base memory usage is 0.0 MB.
V-Ray For Houdini|Progress| V-Ray: Prefiltering light cache... -nan(ind)% 

V-Ray For Houdini|    Info| V-Ray: Average rays per light cache sample: -nan(ind) (min 2147483647, max 0)
V-Ray For Houdini|Progress| V-Ray: Rendering image... 0.0% 
V-Ray For Houdini|    Info| V-Ray: Start progressive rendering, server mode 0, perform rendering 1
V-Ray For Houdini|    Info| V-Ray: Progressive sampling base buffer memory usage: 81.75 MB
V-Ray For Houdini|Progress| V-Ray: Rendering image (pass 0) 0.0% 
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.142857 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.090909 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.052632 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.028571 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.014925 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Noise threshold lowered to 0.007634 with 0.0 percent active pixels.
V-Ray For Houdini|    Info| V-Ray: Final noise threshold set: 0.005000
V-Ray For Houdini|    Info| V-Ray: Progressive rendering finished: specified noise level reached
V-Ray For Houdini|Progress| V-Ray: Rendering image (pass 1) 100.0% 

V-Ray For Houdini|    Info| V-Ray: Sampling level reached: 1.00 subdivs (2 passes)
V-Ray For Houdini|    Info| V-Ray: Number of raycasts: 4551258 (4.94 per pixel)
V-Ray For Houdini|    Info| V-Ray: Camera rays: 4551258 (4.94 per pixel)
V-Ray For Houdini|    Info| V-Ray: Shadow rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: GI rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Reflection rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Refraction rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Unshaded rays: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Number of light evaluations: 0 (0.00 per pixel)
V-Ray For Houdini|    Info| V-Ray: Maximum memory usage for resman: 0.00 MB
V-Ray For Houdini|    Info| V-Ray: Number of intersectable primitives: 2
V-Ray For Houdini|    Info| V-Ray: SD triangles: 2
V-Ray For Houdini|    Info| V-Ray: MB triangles: 0
V-Ray For Houdini|    Info| V-Ray: Static primitives: 0
V-Ray For Houdini|    Info| V-Ray: Moving primitives: 0
V-Ray For Houdini|    Info| V-Ray: Infinite primitives: 0
V-Ray For Houdini|    Info| V-Ray: Static hair segments: 0
V-Ray For Houdini|    Info| V-Ray: Moving hair segments: 0
V-Ray For Houdini|    Info| V-Ray: Successfully written image file "F:/Projets 3D/STROB/STROB_houdiniTest/houdini/vrayForHoudini/render/testPyroVray_003.exr"

**Comment by tinyhawkus** [comment]
I just checked with this build. If I load a previously built scene, using a build from a couple week ago, it
throws a lot of errors on load, and doesn't render the volume. If I re-build the scene it works.
The Vray ROP is neater too, good going guys!

**Comment by bdancer** [comment]
@StrobFX my test scene seems to work fine, may be your setup is different and may be it's not supported yet, could you send me your scene?

**Comment by StrobFX** [comment]
It's the most simple setup just for testing rebuilt from scracth in latest version. Here is my scene:

[testPyroVray_003.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1152673/testPyroVray_003.zip)

**Comment by StrobFX** [comment]
Should I update phoenixFD too maybe?

**Comment by StrobFX** [comment]
It's the most simple setup just for testing rebuilt from scratch in latest version. Here is my scene:

[testPyroVray_003.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1152685/testPyroVray_003.zip)

**Comment by StrobFX** [comment]
By your test file, you mean the one in the daylies?

**Comment by bdancer** [comment]
> Or it uses only the one included with the bat?

It uses **only** the included one.

> By your "test scene", you mean the one in the nightlies?

No.

**Comment by StrobFX** [comment]
I tried many times to rebuild the scene from scratch but I got many crashes and now nothing renders (before it was rendering a black frame) and now I get these errors (I also tried with today's nightlies and I got the same result):
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
V-Ray For Houdini|    Info| Evicting "F:\Projets 3D\STROB\STROB_houdiniTest\houdini\vrayForHoudini/vdb/testPyro3_77.vdb" from cache
unsupported VDB file format (expected version 223 or earlier, got version 224)
V-Ray For Houdini|    Info| Loading cache took 6ms
V-Ray For Houdini|    Info| Expanding channel 'Smoke' took 0ms, extracting took 1ms
V-Ray For Houdini|    Info| Expanding channel 'Temperature' took 0ms, extracting took 1ms
V-Ray For Houdini|    Info| phoenixcache cookMySop(2.708)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
unsupported VDB file format (expected version 223 or earlier, got version 224)
V-Ray For Houdini|    Info| Evicting "F:\Projets 3D\STROB\STROB_houdiniTest\houdini\vrayForHoudini/vdb/testPyro3_76.vdb" from cache
unsupported VDB file format (expected version 223 or earlier, got version 224)
V-Ray For Houdini|    Info| Loading cache took 6ms
V-Ray For Houdini|    Info| Expanding channel 'Smoke' took 0ms, extracting took 1ms
V-Ray For Houdini|    Info| Expanding channel 'Temperature' took 0ms, extracting took 1ms
V-Ray For Houdini|   Debug| VRayPluginRenderer()
V-Ray For Houdini|   Debug| VRayExporter()
V-Ray For Houdini|   Debug| VRayRendererNode()
V-Ray For Houdini|   Debug| VRayRendererNode::startRender(1, 2.708, 2.708)
V-Ray For Houdini|   Debug| VRayRendererNode::initSession(0, 1, 2.708f, 2.708)
V-Ray For Houdini|   Debug| newVRayInit()
V-Ray For Houdini|   Debug| InstancesStorage: "VRayInstances10652"
V-Ray For Houdini|    Info| Using V-Ray AppSDK 1.21.00 24dfe2f [ houdini] Jul 13 2017 11:20:22
V-Ray For Houdini|   Debug| newVRayRenderer()
V-Ray For Houdini|    Info| Using V-Ray 3.57.01 f2a21ff Jul 13 2017 11:20:22
V-Ray For Houdini|   Debug| newVRayRenderer()
V-Ray For Houdini|   Debug| VRayExporter::setAnimation(0)
V-Ray For Houdini|   Debug| VRayRendererNode::renderFrame(2.708)
V-Ray For Houdini|   Debug| VRayExporter::exportFrame(66.000)
V-Ray For Houdini|   Debug| VRayExporter::clearKeyFrames(66.000)
V-Ray For Houdini|   Debug| VRayExporter::exportScene(66.000)
V-Ray For Houdini|   Debug| VRayExporter::exportView()
V-Ray For Houdini| Warning| VRayExporter::exportView: Reseting view plugins...
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "settingsCamera" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "settingsCameraDof" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "stereoSettings" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "cameraPhysical" is not found!
V-Ray For Houdini| Warning| VRayPluginRenderer::removePlugin: Plugin "cameraDefault" is not found!
V-Ray For Houdini|    Info| VRayExporter::setRenderSize(1280, 720)
V-Ray For Houdini|   Error| Can't find PhxShaderSim node for geo1
V-Ray For Houdini|   Debug| Exporting OBJ: geo1 [geo]
V-Ray For Houdini|   Debug| VRayExporter::renderFrame(66.000)
V-Ray For Houdini|    Info| Starting render for frame 66.000...
V-Ray For Houdini|   Debug| VRayRendererNode::endRender()
V-Ray For Houdini|   Debug| VRayExporter::exportEnd()
Qt Warn: QCoreApplication::postEvent: Unexpected null receiver

**Comment by bdancer** [comment]
@StrobFX 
Here is your error:
```V-Ray For Houdini|   Error| Can't find PhxShaderSim node for geo1```
Check the material, may be you need to reconnect your Sim node, also MAT context is supported now.

**Comment by StrobFX** [comment]
Ha yes while rebuilding my scene I forgot the shader. But even if I add it and link it correctly houdini just freeze when trying to render.

**Comment by StrobFX** [comment]
I also gwet thiese:
unsupported VDB file format (expected version 223 or earlier, got version 224)

**Comment by bdancer** [comment]
```unsupported VDB file format (expected version 223 or earlier, got version 224)```
This is not a error.

**Comment by bravehamster** [comment]
Hey Strob, I don't have an indie license to test your scene with and the commercial one won't allow me to start a new scene in Indie mode.
Would you mind uploading a scene that only has : 
-Geometry SOP with a Volume Grid Cache inside
-Vray Omni Light 
-Vray material SHOP with a VolumeGrid Shader
-camera with Vray physical camera parameters
-Vray Renderer ROP

Please don't edit any of the default values. 

I'm also uploading the exact same setup built with the latest nightly from 17.07 which works for me.

https://drive.google.com/file/d/0B1YJxA06WbiZWkktOVJpRjBBejg/view?usp=sharing


![forstrobfx_screencap](https://user-images.githubusercontent.com/20627168/28276392-770cccb4-6b1f-11e7-8d9b-3c57fd31ae61.jpg)

**Comment by bdancer** [comment]
@StrobFX it actually appears to work for me, try this setup: [testPyroVray_004.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1153248/testPyroVray_004.zip)

**Comment by StrobFX** [comment]
Ok thanks you both. 
@bravehamster I just tried in 16.0.633 and I just got the same result. I will reaintall 16.0.600 and send you the file you asked.

**Comment by StrobFX** [comment]
@bdancer ok I'll try this too! thanks

**Comment by StrobFX** [comment]
Ok it's working!!! I found out what my mistake was! I was trying to link my material to the geo this wrong way:
![image](https://user-images.githubusercontent.com/12475879/28283835-074eedb6-6afd-11e7-9c7c-d81e3a97e251.png)

**Comment by bdancer** [comment]
Yeh, this attr is a bit misleading, we'll fix that.

**Comment by bravehamster** [comment]
Hey Strob, I derped and completely missed the fact that you had your render flag on the import pyrofields SOP - that's the reason you had empty renders.

**Comment by StrobFX** [comment]
Yes bravehamster, but when I did that I had a vray volume cache in the import pyrofield. Anyway even when putting it in its own geo node it was not working because of my bad material linking.

**Comment by tinyhawkus** [comment]
Any progress on a viewport reduction or delayed load option for VDB?
Having a high voxel count volume being drawn in the viewport is murder.
