### ISSUE TITLE
Multimatte?

### ISSUE THREAD

**Issue by postcontrol** [ChaosGroup/vray-for-houdini#202]
Sorry, I don't know is this right place to ask but where can I find multimatte render channel? I have tried to find it everywhere but no luck. Also if its implemented how can I control of it (assigning object ids etc)? 

I'm using Houdini 16.0.633 with vfh-749-c326ff3-hfs16.0.600-qt5-windows, in Win10.

Cheers,
.m

**Comment by bdancer** [comment]
@postcontrol it's exactly the right place to ask. I'll implement this asap.

**Comment by bdancer** [comment]
I've added some basic support for object id and MultiMatte render channel.

![vfh_objectid](https://user-images.githubusercontent.com/319784/27484223-183d1e38-5831-11e7-8f41-4cead9084242.png)

**Comment by postcontrol** [comment]
That was quick! Thank you very much!

.m

**Comment by Eiken** [comment]
Since cryptomatte is in vray 3.6 for 3dsmax any chance of seeing it in the houdini version any time soon?

**Comment by bdancer** [comment]
V-Ray for 3dsmax is a bit different from all other V-Rays, we'll add cryptomatte to Houdini as soon as it'll be available in Maya (Standalone). I'll check if there is any progress for that.

**Comment by sepux** [comment]
Hi @bdancer, 
I saw the release notes for Maya 3.6 nightly stables 
(*) Add CryptoMatte render element

So hopefully we can see soon on a Houdini nightly as well??
Thanks

**Comment by bdancer** [comment]
@sepux sure, next week I'll add it.

**Comment by bdancer** [comment]
@sepux I've added Cryptomatte node https://github.com/ChaosGroup/vray-for-houdini/commit/0e8ff7965260e63a8601ea3e408f3c9906db7d98.
