### ISSUE TITLE
VRay for Houdini won't load via hbatch

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#203]
Tested on Linux and Windows

Steps:
- Modify the last line of the .bat or .sh file to run hbatch instead
```
replace:
::start "V-Ray For Houdini" /D "%USERPROFILE%\Desktop\" "%HFS%\bin\hbatch.exe" -foreground %*

with:
"%HFS%\bin\hbatch.exe"
```
- Run the .bat or .sh file

Result:
- On Windows, the command just hangs after loading Phoenix cache loader plugins
- On Linux I get the following error, which is a better clue:
```
Houdini DSO error on '/usr/ChaosGroup/V-Ray/Houdini16.0-x64/vfh_home/dso/vray_for_houdini.so'
    libHoudiniUI.so: cannot open shared object file: No such file or directory
```

hbatch is used for command line operation and has no GUI, so the Linux .so error at least seems to offer a clue.

**Comment by bdancer** [comment]
@blented both seems to work for me, could you pls check again?

**Comment by bdancer** [comment]
Should work fine in today's nightly, I've added a separate script for batch.

**Comment by blented** [comment]
The QT5 HBatch works fine, but for both regular houdini and hbatch builds using QT4 I get this error:
![image](https://user-images.githubusercontent.com/1403171/28217680-d905881e-686a-11e7-9af5-57623d51f73a.png)

Windows 10, Houdini 16.0.600 QT4 vc 14, QT5 w/ the QT5 build runs fine.

Not the end of the world, we've kind of accepted that we're going to have to support both QT versions and are sorting it out in tools but figured I'd give a heads up.  Thanks for the hbatch file!

**Comment by bdancer** [comment]
I'll check why Qt4 fails, tnx.

**Comment by bdancer** [comment]
@blented adjust HFS path in hbatch.bat to point to the Qt4 version of Houdini and it'll work.
