### ISSUE TITLE
vraystd version ?

### ISSUE THREAD

**Issue by StrobFX** [ChaosGroup/vray-for-houdini#205]
I want to get back testing v4h but last time I tried I had problem getting my install to work. So i would like to clear a point:

Which version of vraystd_adv is better to install for vray for houdini to work?

vc91, 14, 11, 101?  (I guess it's vc14 since houdini installer has vc14 in its name...
hwlic or swlic? there is also a swlic-utf8

**Comment by bdancer** [comment]
You don't need to install anything, everything is included in the archive. You need to install stuff mentioned in the README.md only if you need to *compile* the project from sources.

**Comment by StrobFX** [comment]
Ok now I know! thanks!

**Comment by StrobFX** [comment]
Bt if I want to render on a farm, then do i need vray standalone?

**Comment by bdancer** [comment]
You need V-Ray Standalone only if you will render the *.vrscene files.
If you'll render from Houdini "You don't need to install anything, everything is included in the archive." and you'll need to use the provided batch file or setup environment variables yourself.

**Comment by StrobFX** [comment]
But what about licensing when rendering on my farm with v4h? You wrote I can render from Houdini, does that mean I would need houdini licenses on each slave? I only have 1 indie (and the free engine licenses).

**Comment by bdancer** [comment]
Indie version has limitations for third party renderers - you can't export *.vrscene files, so Standalone is not an option.
I'm not aware of Indie limitations for render farms, it's better to contact SideFX.

**Comment by dgsantana** [comment]
You can render with the Engine licenses, but no IFD (mantra case), or
vrscene (VRay case). You can use atleast 3 render nodes to render.

Best regards,
Daniel

Andrei Izrantcev <notifications@github.com> escreveu no dia sábado,
15/07/2017 às 20:24:

**Comment by StrobFX** [comment]
Ok that's weird cause with max I don't need max licenses to render with my vray network licenses...

**Comment by simonreeves** [comment]
The difference there is that in 3dsmax you get unlimited batch licensees, in Houdini you don't!

**Comment by StrobFX** [comment]
So financially it makes more sens to use something like Nyx to convert houdini scene to 3ds max and then render from there with unlimited license and even resolution.

On the other hand if I buy a houdini fx full license instead of indie, will I get unlimited batch? I know I get unlimited mantra token, but what about those batch licences?

**Comment by StrobFX** [comment]
Ok I found the answer: houdini batch license (that I didn't know of) will be replaced entirely by houdini engine license which cost 500$/year each. And if we need then to render with vray that makes using vray with houdini a lot more expensive than with houdini. Unless you don't have more than 6 computers in you render farm (I have 12!)

Another thing to consider i that I could render a scene using 6 computers with an indie setup for not too much for stuff that can't be easily converted to max and use my 6 other computer to render some stuff that can be easily converted via Nyx sidekick in max.

**Comment by StrobFX** [comment]
I just remembered though that with the full Houdini fx license, no one use batch license to render if I understand correctly, they generate ifd and use unlimited free mantra token for rendering. With v-ray, we would need to generate .vrscene and render with vray standalone to avoid paying for the engine licenses.

But is everything that houdini can generate supported by vraystandalone?

**Comment by bdancer** [comment]
If you have a full Houdini license you could export scene to a *.vrscene file and render with V-Ray Standalone on your nodes.

> But still it really sucks that we can't just use our V-Ray license to render with V-Ray in Houdini.

Forbidden export for third-party renderers is the limitation of the Indie license, I can't do anything about it.
But I don't see a problem in using your Standalone render nodes with DR though.

**Comment by simonreeves** [comment]
Same procedure for mantra and arnold, you use a limited amount of houdini licences (engine yes is the best way to get more) to export ifd/ass/vrscene files.
Then you render those files with the standalone renderer.
The way to make this practical is keeping the scenes and ifds/ass/vrscenes light! Referencing geo at rendertime. 

Then when when export times are 2sec a frame it is not a problem

Having got used to that with mantra, I want to look into perhaps exporting vrscenes in maya to avoid having to load maya every time when I render on the farm...
I know how to keep those films small in mantra but I havent tested vray enough yet to know how to do it with vrscenes

**Comment by StrobFX** [comment]
Hi Andrei, I think we wrote at the same time, so I will ask again to make sure you didn't skip:
Is everything that houdini can generate supported by vraystandalone?

**Comment by dgsantana** [comment]
You only need the engine for rendering sims. For the rest it's ifd, or
other formats like vrscene. Ifd is like a baked frame from the main scene.

A segunda, 17/07/2017, 13:23, Jocelyn Strob Simard <notifications@github.com>
escreveu:

**Comment by bdancer** [comment]
> Is everything that houdini can generate via a .vrscene supported by vraystandalone?

Yes.
