### ISSUE TITLE
Add Overlay blend mode

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#207]
VRay TexColorMathBasic or VRay TexColor8Mix seem like good candidates, either would be absolutely _fantastic_ for a job we're working on currently.

Side note: I was super excited to add this myself but I couldn't find any of the code for TexColorMathBasic in the repo, just a lot of TEX_DEF stuff but no actual source :\  If someone points me in the right direction I'd love to make a pull request for it.

Colors must be converted from linear to sRGB first, the corresponding vex snippet:
```
a.x = a.x <= .0031308 ? a.x * 12.92 : 1.055 * pow(a.x, 1/2.4) - .055;
a.y = a.y <= .0031308 ? a.y * 12.92 : 1.055 * pow(a.y, 1/2.4) - .055;
a.z = a.z <= .0031308 ? a.z * 12.92 : 1.055 * pow(a.z, 1/2.4) - .055;
```

Then the overlay blend mode can be applied (also vex):
```
a.x = a.x < .5 ? 2 * b.x * a.x : 1 - 2 * (1 - a.x) * (1 - b.x);
a.y = a.y < .5 ? 2 * b.y * a.y : 1 - 2 * (1 - a.y) * (1 - b.y);
a.z = a.z < .5 ? 2 * b.z * a.z : 1 - 2 * (1 - a.z) * (1 - b.z);
```

Finally colors must be converted from sRGB back to linear:
```
a.x = a.x <= .04045 ? a.x / 12.92 : pow((a.x + .055) / 1.055, 2.4);
a.y = a.y <= .04045 ? a.y / 12.92 : pow((a.y + .055) / 1.055, 2.4);
a.z = a.z <= .04045 ? a.z / 12.92 : pow((a.z + .055) / 1.055, 2.4);
```

**Comment by bdancer** [comment]
Have you tried Tex Layered?

**Comment by bdancer** [comment]
> stuff but no actual source :\

There is no source code for the V-Ray Plugins, they are precompiled.
You could find some source code samples in V-Ray for Maya distribution.

**Comment by blented** [comment]
Thanks @bdancer, it seems that TexLayeredMax has overlay but I couldn't get it to output anything but the first texture.  TexLayered has correct output but doesn't have overlay as a blend mode.  Hopefully I'm just missing something?  Here's a test file, also included the mantra equivalent:
https://drive.google.com/open?id=0B-R03L35FWUSYnRvZVJZd0tYLUU

**Comment by bdancer** [comment]
@blented I'll implement TexLayeredMax asap.

**Comment by bdancer** [comment]
Should work now: https://github.com/ChaosGroup/vray-for-houdini/commit/824465e357ce50b82ec708d6864a153d022c1cbd.
![vfh_layered_texture](https://user-images.githubusercontent.com/319784/28533678-abd3c240-70a6-11e7-82dd-92a4112ab5d5.png)
I'll rebuild nightlies.

**Comment by bdancer** [comment]
@blented does it work for u? Closing?

**Comment by blented** [comment]
@bdancer working fantastically, also love that the textures are in the right order in Tex Layered (top is top, not top is bottom like in Maya).

Seems silly but this was literally the last thing we were waiting on before porting this entire setup from Mantra to VRay <3
