### ISSUE TITLE
MAT support

### ISSUE THREAD

**Issue by sepux** [ChaosGroup/vray-for-houdini#208]
Hi Guys, 
I was wondering when the Mat content will be support, I was trying out and I couldnt render from there.
Since the SHOP content is being deprecated, and the Mat content is way better anyways.

**Comment by bdancer** [comment]
It's supported like for a few months already.

**Comment by bdancer** [comment]
Send me your setup.

**Comment by bdancer** [comment]
And make sure you have the material flag set.

**Comment by sepux** [comment]
yeah nvm it was my fault. Thank you!
