### ISSUE TITLE
UDIM Support

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#209]
Maybe this is covered somewhere obvious but I couldn't find it on the wiki, is there UDIM support for textures yet?  I tried Maya's <UDIM> syntax with no luck, hoping it's an easy one :)

**Comment by bdancer** [comment]
Maya syntax should work fine. Could you send me a simple test scene?

**Comment by bdancer** [comment]
Seems to work fine for me:
![vfh_udim_syntax](https://user-images.githubusercontent.com/319784/28612025-8b5a3c50-71f6-11e7-99c1-9dc919862db1.png)

**Comment by blented** [comment]
Working!  Your screenshot showed me what I was missing.  I'd been using VRay User Color with "uv" as the attribute, makes sense that there would be a VRay UVW node.

Worth noting that my UVW node doesn't have all the inputs yours has.. works fine though :)  Nightly from 2 days ago, Windows 10, 16.6.600, QT5

![uvwnode](https://user-images.githubusercontent.com/1403171/28701799-78af1586-730d-11e7-9b08-686558c60d59.jpg)
