### ISSUE TITLE
Per-Polygon Material Assignment

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#210]
Is there currently an available workflow for using Houdini's material nodes at the SOP level to assign materials?  For example, a red ball and a blue box both in the same object, with material nodes assigning different materials to different parts of the tree?

Here's a simple test scene, I tried both mat and shop context materials with no luck:
https://drive.google.com/open?id=0B-R03L35FWUSaTBtZjNHTDdHZWM

**Comment by bdancer** [comment]
This is what I'm getting:
![vfh_per_poly_material](https://user-images.githubusercontent.com/319784/28609847-ee587784-71ee-11e7-8346-193679eef1c1.png)
Isn't it correct?

**Comment by bdancer** [comment]
If you are not getting the same result check the log for error messages.

**Comment by blented** [comment]
Morning!  Downloaded the latest nightly (should have been step 1), the shop-context materials seem to be working now but with the mat-context materials I'm still getting red box red sphere.  They're set up in that test file the same way as the shop mats are, just turn off "objects_shop" and turn on "objects_mats".

**Comment by bdancer** [comment]
I'll need your new file, because both contexts are working for me as expected.

**Comment by blented** [comment]
Rebuilt the scene from scratch with the latest nightly, working fine now.  Maybe something held over from the older version I was using.  Apologies for the noise!
