### ISSUE TITLE
Packed or custom attributes cannot be used for UVs

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#211]
The boxes on the left are unpacked, the boxes on the right are packed.  "uv" is set as a point attribute on the source grid.

![customuvs](https://user-images.githubusercontent.com/1403171/28702254-a05ffe30-7310-11e7-9a6a-9ddee1a3a0c2.png)

This is the shader:
![uvshaders](https://user-images.githubusercontent.com/1403171/28702253-a05defa0-7310-11e7-9745-5216b02c2f44.JPG)

Here's a link to the file:
https://drive.google.com/open?id=0B-R03L35FWUSdWZOeWg2TktJQ3c

Houdini 16.0.600, nightly from 2 nights ago.

"uv" is basically the only custom attribute you can use in the uvwgen input of an image texture.  VRay doesn't seem to read packed attributes or custom attributes with a different name.

Examples:
- unpacked boxes, "uv" set on points and copied to boxes, works file
- unpacked boxes, "customUVs" set on points and copied to boxes, doesn't read UVs
- packed boxes, "uv" set on points and copied to bxoes, doesn't read UVs

Thanks!

**Comment by bdancer** [comment]
TexUser* can't be used as uvwgen input, but I got your idea and will find a solution for that.

**Comment by blented** [comment]
Workaround / solution is to use UVW Gen Explicit, set up like this:

![image](https://user-images.githubusercontent.com/1403171/28844047-2e69364c-76b8-11e7-84fa-773434ea723d.png)

Color to float multiplies each channel by 1/3 so you need to pre-mult the channel you need by 3 and leave the rest to 0.  

Result works with packed geo with custom attributes and any sort of math.

Packed boxes using a custom attr to sample a texture:

![image](https://user-images.githubusercontent.com/1403171/28844127-79cfee14-76b8-11e7-82cb-e1860e884f3b.png)
