### ISSUE TITLE
Nodes UI refactoring

### ISSUE THREAD

**Issue by bdancer** [ChaosGroup/vray-for-houdini#214]
As you may noticed we're working on some nodes UI reorganization.
I'm preparing a new merge that'll most probably break all existing node connections.
I'll let you know in advance when it'll actually happen.

**Comment by Eiken** [comment]
Any ETA when this will be merged?

**Comment by bdancer** [comment]
@Eiken this month for sure.

**Comment by bdancer** [comment]
There will be no nightly builds for a while. I'm merging the UI changes as well as updating AppSDK / SDK.

**Comment by Dentzz1** [comment]
Not sure if this is relevant but when you update the AppSDK/SDK will V4H be able to use the online license or still need the usb dongle as the SDK has nothing to do with licensing?

**Comment by bdancer** [comment]
@Dentzz1 it could use both way even now.

**Comment by Dentzz1** [comment]
Oh how long was that running I had needed the dongle to run vray in houdini awhile ago? So what if anything will I need to ask for when the current thing runs out at the end of the month?

**Comment by bdancer** [comment]
@Dentzz1 I'm not dealing with licensing usually; if you have any issues, please, write to support@chaosgroup.com.

**Comment by Dentzz1** [comment]
@bdancer I'm not having any issues at the moment but I got vray with modo and never had a dongle license. When I asked to get on the Houdini beta chaosgroup had to send a usb dongle. Every so often I get a notice on the license server that the DONGLE LICENSES EXPIRE SOON. So wasn't sure if I still have to contact them before or after Dec 31.

**Comment by dominik2608** [comment]
@Dentzz1 afaik your dongle is recognized by the online license service and you can use it in conjunction. Thats how we run it over here.

**Comment by Dentzz1** [comment]
@dominik2608 the dongle is recognized by the online license but at least in the past v4h did not see the online licenses only the dongle.

**Comment by dominik2608** [comment]
Ah ok

**Comment by Dentzz1** [comment]
@dominik2608 Or at least that was something I think was true back when chaosgroup told me they had to send me a usb dongle.

**Comment by bdancer** [comment]
This is taking more time that I've expected. Hope to finish this month.

**Comment by Dentzz1** [comment]
Oof, good luck. Is this SDK upgrade the new Vray next/4?

**Comment by bdancer** [comment]
@Dentzz1 that too.
