### ISSUE TITLE
SOP-level mats aren't working via command line

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#215]
Materials assigned at the SOP level don't render via command line, I get the following error:
![image](https://user-images.githubusercontent.com/1403171/28858216-e5febc32-7703-11e7-9d13-9ec9579a120a.png)

Render from within Houdini:
![image](https://user-images.githubusercontent.com/1403171/28858244-13f4445e-7704-11e7-843f-72299fb5bc4a.png)

Render from command line:
![image](https://user-images.githubusercontent.com/1403171/28858281-615c1c4e-7704-11e7-89d7-f4cf1b7ef8f0.png)

Test scene:
https://drive.google.com/open?id=0B-R03L35FWUSblIwekNuUFYwLTQ

Example command line:
```
"C:/Program Files/Autodesk/Maya2016/vray/bin/vray.exe" -sceneFile c:/temp/render.vrscene -imgFile c:/temp/test.0001.exr -frames 10-10 -autoClose 1 -progressUpdateFreq 1000 -progressUseCR 0
```

Are we supposed to be using Maya's vray.exe to render via command line?  I couldn't find one bundled with the Houdini download.. maybe that's the issue?

**Comment by bdancer** [comment]
This means that your Maya installation doesn't have this plugin. Try more recent Maya's nightly build.

**Comment by blented** [comment]
Unfortunately the latest nightly that I see,  vray_adv_36001_maya2017_x64_27563.rar, still fails to create "TexExtMaterialID".  Is there another build available somewhere?  I tried the Nuke nightly as well, same deal.

**Comment by bdancer** [comment]
@blented yeh, seems like those plugins are not yet available in the nightlies, we'll try to resolve it this / maximum next week.

**Comment by blented** [comment]
Fantastic, very much appreciated!

**Comment by sepux** [comment]
did this get fix? I download the latest vray nightly and still isnt working?

**Comment by bdancer** [comment]
I've taken a build from https://nightlies.chaosgroup.com/main#/dworkin/stable/stable_3.6/20170818 and the plugins are there.
