### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by jonmoore1** [ChaosGroup/vray-for-houdini#218]
I have an active render node license on my workstation but I'm getting a render node license error. Any advice on this? Or should I contact Chaos Group support?

Many thanks in advance

jm

![Console Error](http://d.pr/i/zLgbUc.png "Console Error")
![License Server](http://d.pr/i/phCatt.png "License server")

**Comment by tinyhawkus** [comment]
Do you have an AppSDK license? Vray for Houdini requires the AppSDK license to run.

**Comment by jonmoore1** [comment]
No I don't. I have the Formz and Render Node licenses. How do I get the
AppSDK license?

jm

**Comment by jonmoore1** [comment]
Apologies, I thought the response here came from Chaos Group directly when I saw the alert email. I'm speaking to them to sort out the licensing issue.
