### ISSUE TITLE
VRay ROP?

### ISSUE THREAD

**Issue by tinyhawkus** [ChaosGroup/vray-for-houdini#219]
I noticed in the most recent build there's now a Vray ROP node.
I see that it has the option to render to MPlay, and has incoming connection on the node, for 
wiring dependencies I'm assuming.

If I kick off via Render to Disk or Render to MPlay, I can see the process running in the render
scheduler(thanks for adding this BTW!), but no frame buffer pops up. 

Is this a WIP node, or am I doing something wrong?

Cheers

Lewie

**Comment by bdancer** [comment]
V-Ray ROP is ONLY for IPR. Nothing else work for it.
