### ISSUE TITLE
Can I export my Houdini scene as a .vrscene?

### ISSUE THREAD

**Issue by sepux** [ChaosGroup/vray-for-houdini#220]
Does the Vary ROP works for exporting a .vrscene? I'm trying to take some simple from Houdini to Maya

**Comment by blented** [comment]
You can use the VRay Renderer node to export a .vrscene, just switch the mode from Render to Export and specify a path :)

**Comment by sepux** [comment]
Yeah I tried that, but didnt work. I'll dig a little more

**Comment by bdancer** [comment]
@sepux export works only with "normal" Houdini license. If you use Indie then it won't work, it's a license restriction for third-party renderers.

**Comment by sepux** [comment]
Yeah I kinda figured, Im not using the indie version, but still isnt working for me. Here is the .hip

https://drive.google.com/open?id=0B6eO2VWNirUTaFpneXFGWGhlb28

**Comment by bdancer** [comment]
![vfh_export](https://user-images.githubusercontent.com/319784/29524742-53f1c7bc-8699-11e7-871e-50ba28ceb213.png)
