### ISSUE TITLE
CreateProcess failed for 'vfh_ipr -C'

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#221]
Hi,
maybe I am doing something wrong, but I can't figure out how to use IPR with the new 
vray-renderer node.
I do not find any IPR buttons to fire a render and using it in the Houdini render view gives me the message from above.

Thx for clearing me up
Cheers
Dominik

**Comment by bdancer** [comment]
Works fine for me. Try installing 2015 redist.
Also, which Houdini is this? Version? Qt version?

**Comment by dominik2608** [comment]
Houdini 16.0.671 - QT5 - vfh-f029580

**Comment by dominik2608** [comment]
2015 redist is installed - from 12/2016

**Comment by bdancer** [comment]
Can't reproduce. Using 16.0.671 / QT5 / vfh-1c30807.

**Comment by dominik2608** [comment]
Ok- i'll try that build. Hmmm. I am dropping the vray digital asset, right? 
classic VFB renering via the vray_renderer node works...

**Comment by bdancer** [comment]
vfh-f029580 also works fine for me. You could try using "Dependency Walker" to check may be some other libraries missing for vfh_ipr.exe, it's located under `vfh_home/bin`.

**Comment by dominik2608** [comment]
![dependency](https://user-images.githubusercontent.com/18614866/29627462-6fc2c3ac-8832-11e7-9d54-699c226f0b1b.jpg)
This is what I get...

**Comment by bdancer** [comment]
I've googled a bit for "missing DCOMP.DLL GPSVC.DLL IESHIMS.DLL", there are some topics about this; try installing x86 redist in addition to x64.

**Comment by dominik2608** [comment]
Hm. Just tried to test it at home with my Houdini Indie - now it says in Render View: "output driver not supported in Houdini Indie"

**Comment by bdancer** [comment]
Well if Houdini restricts it then I can't do much about it.

**Comment by dominik2608** [comment]
Ok, regarding the inital "CreateProcess failed for 'vfh_ipr -C'" it was totally my fault:
I used older start.bats with missing system variables.... Damn!

**Comment by bdancer** [comment]
> So thats solved ;-)

Great!

> I thought 3rd party rendering is open in Indie - how can we solve that? Is it on SESI side?

Need to ask @rafalSFX about this.

**Comment by dominik2608** [comment]
Thx!

**Comment by rafalSFX** [comment]
If I understand correctly, V-Ray does not usually go thru SOHO to do the rendering, hence most of the time there is no issue like that, when doing a regular render.

I suspect, that for IPR, V-Ray does use some SOHO functionality, and since SOHO does not recognize the renderer, it blocks it.

**Comment by dominik2608** [comment]
Thx rafalSFX for solving the IPR issue!

**Comment by rafalSFX** [comment]
You're welcome :) I haven't fully tested it, so let me know if there is still something wrong with IPR in Indie.
