### ISSUE TITLE
IPR update 

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#222]
Me again... 
Could it be that IPR does not update with for example color changes in diffuse color on a VR mtl?
Thx
Dominik

**Comment by bdancer** [comment]
We haven't yet implemented all the update events through Python/SOHO.
However there is a workaround for that. I'll add a menu to activate it.
I could suggest using "Render RT" toolbar button for now - it's almost the same as IPR just using V-Ray Frame Buffer.

**Comment by bdancer** [comment]
After 233ce854cd61d3fe989e2004d07d30647a91a845 a "Callback" parameter will appear on the IPR ROP, setting it to "Install Callbacks" should enable shading updates.
