### ISSUE TITLE
H16.0.713 - Enabled V-Ray IPR in Houdini Indie.

### ISSUE THREAD

**Issue by jonmoore1** [ChaosGroup/vray-for-houdini#225]
Happy news for those testing on Indie.

**Comment by galagast** [comment]
Cool! Will wait for it to be on the nightlies. Thanks!

**Comment by bdancer** [comment]
@galagast try this one [vfh-1746-8bd9f81-hfs16.0.736-qt5-windows.zip](https://nightlies.chaosgroup.com/download?location=/vray4houdini/nightly/20171024/vfh-1746-8bd9f81-hfs16.0.736-qt5-windows.zip).

**Comment by galagast** [comment]
Thanks Andrei! Downloading now :)

**Comment by dgsantana** [comment]
Weird, lost access to the Houdini section on the nightlies site :(. Any
reason in particular?

Jefferson Lim <notifications@github.com> escreveu no dia terça, 24/10/2017
às 13:35:

**Comment by bdancer** [comment]
@dgsantana please write to support@chaosgroup.com about this.
