### ISSUE TITLE
Vray IPR - Camera Crop Issue

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#226]
Hi,
after having IPR working in Indie with .713 (which is great) I think there is a bug with different camera resolutions than the standard ones.
See example scene attached. 

cam2 seems to get cropped compared to the scene view. cam1 renders fine.
Thanks for looking into it!
Cheers
Dominik
[cam_crop_vray_ipr.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1261605/cam_crop_vray_ipr.zip)

**Comment by dominik2608** [comment]
Hi Andrei,
any news on that? 
Thx!

**Comment by bravehamster** [comment]
Hey Dominik, would you mind posting a screenshot showing what the problem is. Things seem to work on my end.
![screenshot](https://user-images.githubusercontent.com/20627168/29918985-265708ee-8e50-11e7-9c2f-ae851ed7e04c.png)

**Comment by dominik2608** [comment]
Sure, wait a second

**Comment by dominik2608** [comment]
![screen](https://user-images.githubusercontent.com/18614866/29919914-7c851698-8e4b-11e7-814c-bb84b1286d95.jpg)

**Comment by dominik2608** [comment]
But maybe the issue is between my own ears - I didn't use the vray_ipr ROP

**Comment by dominik2608** [comment]
Nope ! Same with the IPR ROP

**Comment by dominik2608** [comment]
Hm, for some reason I even can't get "production renderer" to render... Is it me ;-)?

**Comment by bdancer** [comment]
> Hm, for some reason I even can't get "production renderer" to render

What does this mean?

**Comment by dominik2608** [comment]
If I press "render to disk" - nothing happens - shouldn't open VFB?
Here some log:
[2017/Aug/31:13:57:24]VFH|     Info| Loading Phoenix cache loader plugins from "R:\HOUDINI_VRAY\16.0\vfh-f46a200\\vfh_home\libs"...
[2017/Aug/31:13:57:25]VFH|     Info| Build f46a200 from Aug 28 2017, 04:17:18
[2017/Aug/31:13:57:38]VFH|     Info| Parse plugin description data...
[2017/Aug/31:13:57:42]VFH|    Debug| (#1124) Initialize SOHO...
[2017/Aug/31:13:57:42]VFH|    Debug| (#1124) Processing Mode: "default"

nothing happens after 5min waiting - just a grid and alight, see above

**Comment by bravehamster** [comment]
@dominik2608 - good catch, it's indeed an issue. 

Regarding rendering -  are you using the V-Ray IPR Renderer or just the V-Ray Renderer node ?

**Comment by bdancer** [comment]
@dominik2608 IPR node **only** for IPR for now.

**Comment by dominik2608** [comment]
@bdancer @bravehamster 
Regardless which node I am using (got it for IPR!) the VFB isn't showing up anymore...

**Comment by bdancer** [comment]
* V-Ray Renderer - for "normal" rendering.
* V-Ray Renderer IPR - for IPR / viewport region.

**Comment by dominik2608** [comment]
Thx for clarifying :-)

**Comment by dominik2608** [comment]
Btw:  viewport region is not working in Houdini renderview

**Comment by bdancer** [comment]
@dominik2608 good to know...

**Comment by bdancer** [comment]
@dominik2608 pls, try a new build, both issues should be resolved.

**Comment by dominik2608** [comment]
@bdancer:
I tried it this weekend and both worked! Thanks
