### ISSUE TITLE
IPR Region - Outside dissapears

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#229]
Hi,
it would be cool, that after drawing a region in the render view, already rendered parts would stay. Like in Maya.

Is it possible?
Thanks
Dominik

**Comment by bdancer** [comment]
It's possible for sure.

**Comment by dominik2608** [comment]
Great! When? ;-)

**Comment by bdancer** [comment]
Not sure it's a "show stopper"...

**Comment by dominik2608** [comment]
Haha, it's of course not 😊 just a convenient feature! But sure... Would be cool to have it soon 😉

**Comment by galagast** [comment]
Hey @dominik2608, by any chance, did regions work for you in Render View?
Judging from your original post, it seems that it was working for you, with just the issue that the previous rendered images were not retained?

_mine currently is not working - #254_
