### ISSUE TITLE
IPR - "Enable/Disabling" in light not updating

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#231]
Hi,

I just faced this issue.

Cheers
Dominik

**Comment by bdancer** [comment]
I've tried V-Ray Dome Light - working fine for me. Could you upload your scene, please?

**Comment by dominik2608** [comment]
Andrei, you are right. In a fresh scene it works. 
Maybe it's because I changed versions in the scene where I had the issue?

Cheers

**Comment by bdancer** [comment]
@dominik2608 not sure, but if you'll catch it again, pls, upload a scene.

**Comment by dominik2608** [comment]
Alright
