### ISSUE TITLE
Nightly for 16.0.705

### ISSUE THREAD

**Issue by Eiken** [ChaosGroup/vray-for-houdini#232]
Would be great to get a nightly build for the latest H16 Production build

**Comment by bdancer** [comment]
Builds for 705 are uploaded.

**Comment by Eiken** [comment]
Getting errors trying to use this version:

Houdini DSO error on '/internalpath/linux/16.0/vfh-9303f4b/vfh_home/dso/vray_for_houdini.so'
	/internalpath/linux/16.0/vfh-9303f4b/vfh_home/dso/vray_for_houdini.so: undefined symbol: _ZN6PHXGUI6GenWnd4ShowEi

**Comment by poseidon4o** [comment]
@Eiken this error should be resolved with latest nightly builds for linux.

**Comment by Eiken** [comment]
Works now! Thanks
