### ISSUE TITLE
VrayMtl: Fog not working

### ISSUE THREAD

**Issue by postcontrol** [ChaosGroup/vray-for-houdini#233]
Hi, 

it seems that VrayMtl fog is broken.
This is from 3dsmax 2016, vray 3.60.03.
![3dsmax_mtl_settings](https://user-images.githubusercontent.com/18567683/31212716-c9971880-a9aa-11e7-96de-83a4ca731ad3.jpg)

This is from Houdini FX 16.0.736, vfh-1554-dff1772-hfs16.0.705-qt5-windows, standalone x64 vc14 3.60.03 installed. Windows 10. In houdini I'm using OCIO, AcesCG (1.0.3) with sRGB rrt in render view, so that's why overall render looks different than 3dsmax. I also tested to scale sphere 100x in sops level and it didn't make any difference for fog. Also checked on/off  (Fog multiplier in Centimeters^-1).
![vray4houdini_mtl_settings](https://user-images.githubusercontent.com/18567683/31212754-017b4898-a9ab-11e7-8a4a-1011b7653185.jpg)

Cheers,
Matti Kaihola

**Comment by bdancer** [comment]
Could you upload both scenes?

**Comment by postcontrol** [comment]
Here you go! Scene ain't exactly same but same thing happens (hdr is different).

[vray_fog_bug.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1368583/vray_fog_bug.zip)

Cheers,
Matti Kaihola

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/plugins_desc/commit/5d055b20e7c32842450b9c34aece9c67f6350988. Should work in next build.

**Comment by postcontrol** [comment]
Thank you!
