### ISSUE TITLE
V-Ray Subdivsion at Rendertime

### ISSUE THREAD

**Issue by Dentzz1** [ChaosGroup/vray-for-houdini#235]
Is there a way to subdivide Geo at rendertime with either V-Ray dynamic Subdivision or Static OpenSubdiv(what it is called in modo)? Would think this would be editing the parameter interface on the geo at the object level and adding the vray property but not sure????

**Comment by bdancer** [comment]
I'm rewriting this part currently, but for now there is a button the V-Ray shelf called "Displacement", it adds properties on the object. Then you could select there the subdivision mode.

**Comment by Dentzz1** [comment]
Thank you, was able to get it working with the the shelf button on displacement. Look forward to seeing it when it is rewritten.

I looked at the displacement scene file and displacements worked on the geo that had the displacement spare parameters node(type set to smoothed) but not the one that was using From Shop Net.  Wasn't sure why.
