### ISSUE TITLE
Camera - Screen Window X/Y

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#236]
Hi,

it seems that the above parameter in "View" is kinda weirdly transferred/added. 
See screenshot.
Build: vfh-f398357 | H 16.0.736

Thanks
Dominik
![screen_x_y](https://user-images.githubusercontent.com/18614866/31437834-f45bf834-ae86-11e7-9d13-bc445250e752.jpg)

**Comment by bravehamster** [comment]
Hey @dominik2608 , would you mind uploading the scene ? 
Thanks

**Comment by dominik2608** [comment]
Of course , here you go
[camera_x_y_issue.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1375542/camera_x_y_issue.zip)

**Comment by dominik2608** [comment]
Any news on this? Would really need to have film offset possibility...

**Comment by dominik2608** [comment]
Sorry for being unpatient and annoyingly asking, but it seems that it becomes a little showstopper for me ... 
Is there any chance to get it working very soon :-) ???
Thanks guys!

**Comment by bravehamster** [comment]
Hey there, sorry for the late reply. 
Is it possible that the Vertical Shift parameter in the Distortion tab of the Physical camera could substitute that functionality ?

**Comment by dominik2608** [comment]
Hi, no problem ;-) 
I waned to avoid using the physical cam, but I think that could be a workaround no other solution comes up. I'll give it a try!

**Comment by bravehamster** [comment]
The issue is logged, I can't speak for the devs but in general, requests for new features / improvements are always considered. 

All the best.

**Comment by dominik2608** [comment]
Thx - The problem with physical cam is that it doesn't give you any feedback in the viewport for the offset...
So finding exact values is a difficult process

**Comment by dominik2608** [comment]
Update: Distortion shift is not working at all in the physical camera

**Comment by ultra-sonic** [comment]
+1 from me for supporting houdinis view transforms instead of using physical cam.

**Comment by dominik2608** [comment]
Andrei, any chance to get this fixed? I am walking on a thin line ;-) ...

**Comment by bdancer** [comment]
@dominik2608 try today's build.

**Comment by bdancer** [comment]
@dominik2608 also if you're using Physical Camera you'll have to recreate it's attributes, you could do it by pressing the "Physical Camera" button on a toolbar with camera selected.

**Comment by dominik2608** [comment]
Thx Andrei, its working so far! One minor bug (see attached sample scene): if you dial in some numbers on Y axis
[screenWindow.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1398212/screenWindow.zip)
 and render with IPR, everything works BUT if you switch back to 0, the sphere renders darker ?!

**Comment by bdancer** [comment]
@dominik2608 I've uploaded new builds.
