### ISSUE TITLE
BlendMtl - Usage

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#237]
Hi,
![capture](https://user-images.githubusercontent.com/18614866/31453385-4fbd916c-aeb2-11e7-9d8e-6c4d5b107a55.JPG)

I don't get it... how to use the layered brdf?

Thanks for a pointer
Dominik

**Comment by bdancer** [comment]
This node will be removed, use "Blender (BRDF)" node.

**Comment by ultra-sonic** [comment]
Finally we have Blender in VRay (pun intended)
