### ISSUE TITLE
Vray Light Rectangular  - Tex not working anymore

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#238]
Hi,

somehow I can't get to work textures rect lights. Its todays build. 
Do I miss something?

![light1](https://user-images.githubusercontent.com/18614866/31493409-699f03f2-af4f-11e7-9309-244a986c409d.jpg)
![light2](https://user-images.githubusercontent.com/18614866/31493412-6c1843aa-af4f-11e7-80bd-2f19f997d7b7.jpg)

**Comment by bdancer** [comment]
So, should it start with "op:" or not?

**Comment by dominik2608** [comment]
Ah, wait a sec

**Comment by dominik2608** [comment]
Seems to work with op...
I was confused, because I thought in Area lights file texture aren't supported yet? And with older builds it worked with the standard path like in the screenshot...

**Comment by bdancer** [comment]
> Seems to work with op...
Great!

Try new build https://nightlies.chaosgroup.com/main#/vray4houdini/nightly/20171012 , file path should work for Rectangle light also.

**Comment by dominik2608** [comment]
This is the build I am already using / I'll try!

**Comment by bdancer** [comment]
@dominik2608 I've updated it an hour ago or so.

**Comment by dominik2608** [comment]
Ok thx
