### ISSUE TITLE
Matte Objects / Wrapper / Object Properties

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#239]
Sorry to warm that up - Is this working? Because I can't figure out how to connect the WrapperMtl. Putting the wrapper Render Parms on the geo seems not to work.
Thanks for helping me out
Dominik

**Comment by dominik2608** [comment]
Ah - Force Matte seems to work in the vray renderer - cool - first problem solved. :-)
But how would I generally use the maya equivalent vray object properties?

**Comment by bdancer** [comment]
> But how would I generally use the maya equivalent vray object properties?

Not yet there...

> Because I can't figure out how to connect the WrapperMtl.

This should work:
![10-13-2017-16_38](https://user-images.githubusercontent.com/319784/31548843-ee8f88e4-b034-11e7-9991-6803826982b4.png)

**Comment by dominik2608** [comment]
thx!

**Comment by dominik2608** [comment]
Hi,
I get this error with todays build vfh-e977a24
![wrapper](https://user-images.githubusercontent.com/18614866/31780603-77d4f9f2-b4f6-11e7-899e-4dac14c77fa6.jpg)

**Comment by bdancer** [comment]
@dominik2608 yeh, this happens sometimes, shouldn't affect the render though.

**Comment by bdancer** [comment]
Hope https://github.com/ChaosGroup/vray-for-houdini/commit/c8152f4fa3c37751d98b1c243f87c076da85863c will finally fix such errors.
