### ISSUE TITLE
Render mask not updating selection

### ISSUE THREAD

**Issue by postcontrol** [ChaosGroup/vray-for-houdini#243]
Hi,

It seems that render mask ain't updating selection. First time it works fine when selecting by object or object id, but after that if I change object name or id it still renders old selection even if there reads other object name/id in "Object Ids" field.

Win10 64bit, Houdini 16.0.736, vfh-1636-43c248b-hfs16.0.705-qt5-windows

.m

**Comment by postcontrol** [comment]
I can't upload it here, because its client job in production and it's quite huge :). I can try if I can reproduce it with simpler scene and upload it here.

.m

**Comment by bravehamster** [comment]
A box and a sphere would be more than enough. I'd like to check the exported .vrscene. I get empty renders on my machine so it's interesting that the Render mask (somewhat) works for you. 
Thanks.

**Comment by postcontrol** [comment]
Hmmm.. I can't reproduce it with new scene. One note thou. That object which works with render mask, was taken from old project which was made in the spring. Was made with vfh-749-c326ff3-hfs16.0.600-qt5-windows. I just copy pasted obj/shop nodes from old scene to new scene.

.m
