### ISSUE TITLE
ROP Vray Renderer Node Input

### ISSUE THREAD

**Issue by Dentzz1** [ChaosGroup/vray-for-houdini#244]
This post is as a feature request hoping that whatever the final vray render node/nodes will be has an input, so that in ROPS you are able to chain actions together caching multiple nodes. I'm not sure what the plans are on final vray render nodes will be but wanted to get this idea posted.

**Comment by postcontrol** [comment]
+1, Currently I have 15 vray render nodes in scene and if I want to render all render layers I need to go all render nodes one by one pressing render :). It's also handy if doing simulation you could chain simulation rop first and then put vray to render sim.

.m

**Comment by dominik2608** [comment]
+1

**Comment by Dentzz1** [comment]
For the Renderlayers I think the approach that they are going with is you have the render elements node which can attach the different render passes and that gets put on the vray renderer. But if you need multiple your example 15 different vray renderer nodes as you want to have separate renders for various reasons this can chain them so you set it up and it just processes them all with one render click.

**Comment by postcontrol** [comment]
Dentzz1: Yeah, I'm currently making print for client and they want all objects as separated elements so they can move those invidually in photoshop. That's why I need many render nodes. Thinking if doing this same job with 3dsmax would just be a horrible mess! :). Maybe I should write python script to chain renderings hmmmm....

.m

**Comment by postcontrol** [comment]
Does Post-Render Script work with vray?

.m

**Comment by Dentzz1** [comment]
@postcontrol yeah I was pretty sure we were talking about the same thing, but I wanted to write just to make sure as sometimes AOVs, Image planes, Render layers, passes can all mean the same thing or refer to different things. That what this is asking for a vray render and then later a separate render happens after the first. As opposed to I would want a velocity pass, a position pass, a separate pass for each piece of geometry, a denoised pass  which would be something separate as layers or separate files happening in a single render.

I don't know if post-render script works with vray.

**Comment by postcontrol** [comment]
Post-Render script not working at least the way it should. Once render starts it runs script, so it won't wait that rendering is finished.

.m

**Comment by bravehamster** [comment]
Maybe I'm misunderstanding something but have you guys tried putting a Merge node in /out and hitting render on it ? It works for me.

[Here's a link](https://chaossw-my.sharepoint.com/personal/gosho_genchev_chaosgroup_com/_layouts/15/guestaccess.aspx?docid=09061acf8ffaf4c129f3b326f25fab1f2&authkey=AcuNsY1bq8it-TzQWSOZ83w)

**Comment by postcontrol** [comment]
Hmmm.. last time when I tried it, it was trying to render all nodes same time. It didn't wait first to finish. Going to test it once more..

.m

**Comment by galagast** [comment]
The [Batch ROP](http://www.sidefx.com/docs/houdini/nodes/out/batch) might also help in this case?
Or, under the Merge ROP's controls, maybe set the Order to Node by Node?
![image](https://user-images.githubusercontent.com/16534677/31821694-8c9efa3a-b5d8-11e7-998c-4c2b25717556.png)

_I cannot test it right now as I don't have access the VFH any longer._

**Comment by postcontrol** [comment]
Same thing. It starts to render another render even vray is still calculating light cache. 

.m

**Comment by Dentzz1** [comment]
Also the advantage of and reason I was asking for the input on the vray render is that it allows the user to visually see the order things are performed. If it is just a bunch of render nodes order might not matter, but if I am using rop geo to render say a particle sim that impacts a dynamic sim and want all of those to be cached before vray renders a merge doesn't allow that easy visual check on what order things are happening.  You have to go into the merge and I assume start playing around with the arrows inside the node and even then I'm not sure you can be certain that it would always perform top to bottom instead of bottom to top.

**Comment by Dentzz1** [comment]
@bravehamster I edited your scene with mantra in the out context for kind of what I was hoping as the vray feature request.
 https://1drv.ms/u/s!Ah00a54dc4xBaaTP1gs7q5vD6sU using skydrive hopefully the file can be downloaded let me know if it doesn't work.

 For a sphere and box they are not going to need caching but imagine the ball is a character (maybe has deformation or muscle sim as well as cloth that is being calculated each frame) and the box could be a pyro sim and I want to cache out a high res sim and see the render results leaving the computer running overnight.

**Comment by bdancer** [comment]
Should be better after https://github.com/ChaosGroup/vray-for-houdini/commit/abfd1f12d3224ba283129cb30ffb57bdf9882c6d, https://github.com/ChaosGroup/vray-for-houdini/commit/a81f1459582b28d7f3b3ad9ad4bd658de19bf063.

**Comment by Dentzz1** [comment]
Great, adfd1f1 added the inputs to the vray render.  Caching out files before rendering worked for me. Assume that a81f145 is related but not sure exactly what it is doing to see if it is working.

**Comment by bdancer** [comment]
@Dentzz1 closing this or there is smth else?
