### ISSUE TITLE
V-Ray Render Channels - typo

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#245]
Hi,
there is a typo on V-Ray Render Channels (it says: V-Ray Render Channles - has to be  **Channels** )
Cheers
Dominik

**Comment by bdancer** [comment]
Tnx, fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/ba7b043840bceff32a60de01f6b4b77b17e7579d.
