### ISSUE TITLE
Render Element - Sample Rate

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#247]
Hi Andrei,

the sample rate render element does not work, right?

Cheers
Dominik

**Comment by bravehamster** [comment]
Hey, not Andrei but yes, the Sample Rate element seems not to work !

**Comment by dominik2608** [comment]
Hey :-) 
thx (I mostly writing with Andrei, hehe,, but yeah, there are more devs!! )

**Comment by bdancer** [comment]
Enable "Filtering" option.

**Comment by bdancer** [comment]
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/6ac339b7d4d55378e1f7053485e4de346ac0481e.
