### ISSUE TITLE
Vray ROP - Render with Take not working

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#248]
Hi,
Actual build. Render with Take seems not to work. (which is not good for me actually)
Cheers!
Dominik

**Comment by bravehamster** [comment]
Hey @dominik2608 , could you please be a bit more specific ? I just tried doing some edits to a take in the scene - the V-Ray plugin exported the geometry and materials correctly.

**Comment by dominik2608** [comment]
Hm,
just tried it (it was controlling  a switch node in the mat context) and now it worked...
Sorry for confusing, myabe it was just me ...

**Comment by bravehamster** [comment]
No worries. If anything like that happens again, please save the scene and upload it here if possible. It helps a lot !
Cheers.

**Comment by dominik2608** [comment]
I know, I would normally build a test scene and upload immediately, but atm no time :-) Facing a deadline

**Comment by dominik2608** [comment]
Could be closed - works like a charm, my fault!
