### ISSUE TITLE
Domelight texture not working anymore

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#250]
Hi,

for some reason texture in the dome light do not work anymore. Just comes black or white. Shouldn't it work simply by grabbing a file? 
See attached scene.
[noDomeTex.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1407469/noDomeTex.zip)

Thx
Dominik

**Comment by bravehamster** [comment]
C:/Program Files/Side Effects Software/Houdini 16.0.736/houdini/pic/DOSCH_SKIESV2_01SN_lowres.rat

I don't think V-Ray supports .rat files. IIRC those are native to Mantra.

**Comment by dominik2608** [comment]
was just a example - in my scene I use exr's

**Comment by bravehamster** [comment]
Just checked - works with today's nightly and your scene when using a .hdr file. Please try it out.

If the problem is still there, could you copy the log from the console and paste it here ?

**Comment by dominik2608** [comment]
Hm, then it might cause problems, if I continuously switching nightlies maybe?

**Comment by dominik2608** [comment]
Seems that was the issue. 
Can be closed!
Thx

**Comment by bravehamster** [comment]
Switching nightlies should not be a problem but because a lot of things are changing fast at the moment, it's probably best to stick to a single one when working on a project. That's my two cents :}

**Comment by dominik2608** [comment]
Yeah, I would like to, but there were a lot of features/issues I needed/I needed to have fixed...
But its ok, I knew that it could be a bumpy road with an alpha, no problem! The project is robust enough to handle that 
;-)
