### ISSUE TITLE
IPR - Cannot Use Default Camera

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#253]
In the attached scene, I have 2 cameras:
cam1 - has Vray Physical Camera properties
cam2 - default Houdini Camera

**Render View Tab:**
![render_view_cam](https://user-images.githubusercontent.com/16534677/31956545-504c53ea-b91e-11e7-83b9-fed767503690.gif)
1. Render cam1 - OK
2. Render cam2 - **NOT OK**
3. Render Scene View 1 - OK
4. Render Scene View 2 - OK
* It's only when I render using the cam2 (default Houdini Camera) where it fails.

How come Scene View works? Does VFH apply an automatic Physical Camera property to it?

H16.0.736 Indie - [ipr_test.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1411698/ipr_test.zip)

vfh 1746 8bd9f81 hfs16.0.736

**Comment by bdancer** [comment]
Works fine for me, could you pls test with the latest build?

**Comment by galagast** [comment]
I can confirm here on the latest build:
vfh 1774 35047d3 hfs16.0.736 (Oct 27)
Working as expected now, thanks!
