### ISSUE TITLE
IPR - Render View - Regions not working

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#254]
Using regions in Render View is not working.
Although I can see portions of the console updating with these:
```
[2017/Oct/25:01:02:48] VFH [Debug] Processing Mode: "update"
[2017/Oct/25:01:02:48] VFH [Debug] exportView()
[2017/Oct/25:01:02:48] VFH [Debug] Res: [1280, 720]
[2017/Oct/25:01:02:48] VFH [Debug] Crop: 442-194 194 x 228
[2017/Oct/25:01:02:52] VFH [Info] V-Ray: Noise threshold lowered to 0.142857 with 0.2 percent active pixels.
[2017/Oct/25:01:02:52] VFH [Info] V-Ray: Noise threshold lowered to 0.090909 with 0.4 percent active pixels.
```
Where it does some cropping.

Here's a capture showing regions not working.
![render_view_no_region](https://user-images.githubusercontent.com/16534677/31957242-b81702d4-b920-11e7-9a61-886beecdc882.gif)
I'm setting colors for the box, but when I pick a region, then update the material.. the whole frame re-renders.

vfh 1746 8bd9f81 hfs16.0.736

**Comment by dominik2608** [comment]
+1 for me

**Comment by dominik2608** [comment]
Hm, I am not using the RenderView atm, only VFB. But a quick test showed, thats not rendering at all in the render view...

**Comment by dominik2608** [comment]
ok, did a quick test and: not rendering at all in my render view...
everything fine btw in the VFB...
Here is my little scene (same build as galagast

[renderView_vs_VFB.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1412018/renderView_vs_VFB.zip)

**Comment by galagast** [comment]
Hi, there are two things you currently need for it to work:

1. Use **Vray Renderer IPR**, instead if the usual Vray Renderer ROP.
![image](https://user-images.githubusercontent.com/16534677/31961550-99533216-b92d-11e7-89fb-5267a41c9cb8.png)
This variant is the ROP that works with the Render View.
_I'm assuming that this is just temporary, hopefully the functionality will be merged to a single Vray Renderer ROP soon._
2. Add **Vray Physical Camera** Properties to to your camera object.
Select you camera and click the shelf tool to add the properties:
![image](https://user-images.githubusercontent.com/16534677/31961662-f38f46b6-b92d-11e7-94da-a62383996547.png)

You'll now see you scene rendered in the Render View:
![image](https://user-images.githubusercontent.com/16534677/31961780-57cbfa0c-b92e-11e7-9674-c1628619e907.png)
_Using the proper ROP, and the updated camera properties._

**Comment by dominik2608** [comment]
Hey, thx. I used the right ROP, but missed the info that i should use Vray Physical Cam. 
Hope that this is temporary too.

+1 for merging the functionality of the two ROPS into a single one

**Comment by bdancer** [comment]
> but missed the info that I should use Vray Physical Cam.

You don't have to, it's a bug.

**Comment by bdancer** [comment]
Both should work better https://github.com/ChaosGroup/vray-for-houdini/commit/6d11af4d948518e5d4307046fc3023e0bd5afc1c.

> +1 for merging the functionality of the two ROPS into a single one

That's planned for sure.

**Comment by bdancer** [comment]
@galagast this should also be resolved now, could you pls test?

**Comment by galagast** [comment]
Hi Andrei,
I tested it out in the latest build:
vfh 1774 35047d3 hfs16.0.736 (Oct 27)

The regions are now working, but would it be possible retain the previous image?
![render_view_region_refresh](https://user-images.githubusercontent.com/16534677/32115554-ddfcc050-bb79-11e7-9a34-b9db2d824b2a.gif)

**Comment by galagast** [comment]
Oops, I accidentally closed the issue.. reopened it again.

**Comment by dominik2608** [comment]
@galagast 
Should be my rquest here:  #229

**Comment by galagast** [comment]
@dominik2608 ah yes! I forgot about that! Thanks for referencing the thread here. 👍

**Comment by blented** [comment]
This seems broken again, selecting a region to render causes the whole image to start rendering again.

Tumbling the camera with a region active renders the whole image not the region.
