### ISSUE TITLE
IPR - Scene View Region - Resized

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#255]
When using the IPR for a Region Render over a Scene Viewport, it works quite well.

But maybe it should disregard the renderer's `Override Camera Resolution` toggle.
The resizing is reflected on the viewport, as shown below:
![scene_view_region_resize](https://user-images.githubusercontent.com/16534677/31957610-e8914f0e-b921-11e7-86e9-7d93d045e489.gif)

vfh 1746 8bd9f81 hfs16.0.736

**Comment by Dentzz1** [comment]
Is this working with Vray? I didn't even think to try but I have had no luck if I set the Render region to vray IPR. Are there other things that need to be set besides putting the render region to a vray ipr render?

**Comment by bdancer** [comment]
@galagast is a bug, camera resolution should not be used at all in this case.

**Comment by bdancer** [comment]
@Dentzz1 as you can see - it is =)

**Comment by bdancer** [comment]
@galagast I can't reproduce this, could you try with the latest build?

**Comment by Dentzz1** [comment]
@bdancer I can't, Render Region isn't working for me. Is there something else that needs to be done besides creating a vray ipr node and selecting that when drawing out the render region?

**Comment by bdancer** [comment]
@Dentzz1 nop, the only thing is that it only works for Qt5 builds.

**Comment by Dentzz1** [comment]
@bdancer I'm on a windows Qt5 705 build but get <unknown> shown on the render region when I try and nothing happnes.  If I first use a render region with mantra then use vray_ipr it has C and shows what was in the mantra render region.

**Comment by Dentzz1** [comment]
Could it not work on Houdini Indie?

**Comment by bdancer** [comment]
@Dentzz1 yet, it could, check https://github.com/ChaosGroup/vray-for-houdini/issues/225, V-Ray IPR is enabled by SideFX after build .713, so should work in .736.

**Comment by Dentzz1** [comment]
@bdancer going to .736 worked

**Comment by bdancer** [comment]
@Dentzz1 is this issue reproducible for u?

**Comment by Dentzz1** [comment]
@bdancer Not for me. Clicking Override Camera Resolution doesn't seem to make any changes to the render region viewport.

**Comment by galagast** [comment]
@bdancer I tested this on the newer version:
vfh 1764 fcbb7ad hfs16.0.736 (Oct 26)
It's now fixed!

I checked it again on the last version:
vfh 1746 8bd9f81 hfs16.0.736 (Oct 24)
The bug was there.

Closing this now :)
