### ISSUE TITLE
Vray LightRectangle - Use tex is checked initially

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#256]
Hi,

Build: vfh-8bd9f81
Is this intended? Should maybe be off?

Cheers

**Comment by bravehamster** [comment]
The texture parameter works as a multiplier on the overall Color and Intensity of the light.
If you keep the field empty, it seems that the assumed default value is 1 so there is no effect. 

Do you think it should be disabled by default ?

**Comment by bdancer** [comment]
> Is this intended? Should maybe be off?

Yes, it's intended. If texture is not set nothing will be exported anyway and the "Color" will be used.
