### ISSUE TITLE
Vray Lightdome - On create error

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#257]
Hi 

I get this on creation - should I be concerned ?
![lightdome](https://user-images.githubusercontent.com/18614866/31989470-a1e8c36a-b972-11e7-8d57-a0221c65d82d.jpg)

**Comment by bravehamster** [comment]
hey, if you rename the lights in your scene instead of leaving them with their default naming you wont get this error

**Comment by dominik2608** [comment]
Ah - cool!

**Comment by bdancer** [comment]
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/003981acfc2290231c83a8170064329b5e03e4b9.
