### ISSUE TITLE
V-Ray Renderer - Camera Settings Not Working

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#261]
The **`V-Ray Renderer -> Camera Tab`** settings/parameters does not seem to be working.
![image](https://user-images.githubusercontent.com/16534677/32121919-2c0e3208-bb91-11e7-9694-4406a189ef5e.png)

- The only time it seemed to work is if I use a regular Houdini Camera, then enable Override FOV on the renderer.
- All the other parameters doesn't seem to be working (like Spherical Camera Type, or Override Dof).
- Right now, if I want some DOF, the Physical Camera seems to be working, but currently has some issues #217.

vfh 1774 35047d3 hfs16.0.736

**Comment by bdancer** [comment]
Should work better after https://github.com/ChaosGroup/vray-for-houdini/commit/eeb452ea5d23af6ac052b2dafde987b888664b35. Anyway, if Physical Camera is enabled DOF and MB settings on ROP will be ignored.

**Comment by galagast** [comment]
Thanks Andrei, I just tested the camera settings with the new version, so far the parameters that I tested seems to be working great.

Build vfh 1798 128450b hfs16.0.736 qt5 2017-10-31
