### ISSUE TITLE
Vray Mtl - Fog not working as expected

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#262]
Hi,

the refraction fog is not working as expected. The color either stays unchanged or dissapears when zero is reached. Same for saturation in the color and the bias. Even very small nnumbers make no difference.

![fog](https://user-images.githubusercontent.com/18614866/32126623-eaad35ee-bb71-11e7-95e5-d4f1c2a431f3.gif)

vfh 1774 35047d3 hfs16.0.736

Is there a chance to get this working soon?

thanks & cheers!
Dominik

**Comment by bdancer** [comment]
> Is there a chance to get this working soon?

Fog effect is dependent on scene units. Probably in your case you need to use smaller values.

What app are you comparing with? 3ds max?
If I use meters/meters units in 3dsmax and make a sphere with radius 1.0 I'm getting exactly the same results as 1.0 Houdini sphere.

**Comment by dominik2608** [comment]
Hi Andrei,
unfortunately even with really low numbers I can't see any differences. At the moment I can't compare to 3dsmax/Maya.. 
I attached my scene.
Cheers
Dominik

[glass.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1427739/glass.zip)

**Comment by bdancer** [comment]
@dominik2608 make the color "lighter" itself.

**Comment by dominik2608** [comment]
Got it - thanks.  Didn't remember that...

**Comment by dominik2608** [comment]
Can be closed
