### ISSUE TITLE
Cryptomatte - Node Name

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#263]
I'm testing out the cryptomatte render element.

If I render out using `ID Type: Node Name`, it does not give me SEPARATE access to each node, it selects the whole scene instead.
This is what I'm getting in nuke after picking:
![image](https://user-images.githubusercontent.com/16534677/32223756-a47b07d0-be79-11e7-9515-e0bc53f3069a.png)
Also, from the docs, it should show the node name, not a float number.

So, I tried `ID Type: Material Name`.
This one is working in nuke, I'm able to pick mattes in the image.
But it still does not show me the names (of the materials).
![image](https://user-images.githubusercontent.com/16534677/32223873-1f02c2d6-be7a-11e7-979b-43c1fdf59894.png)

Usnig `ID Type: Node Name Hierarchy`, it also does not work. The output looks the same as `Node Name`.

Attached is a sample scene setup that I'm using:
H16.0.736 Indie - [crypto.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1430673/crypto.zip)

**Comment by bravehamster** [comment]
Hey there, Node Name and Material work for me. It seems that the issue is related specifically to your scene setup. I need to investigate further. 

As to the Node Hierarchy and the Matte List names - both of those are indeed an issue. Thanks for reporting them!

**Comment by galagast** [comment]
Thanks for the tip @bravehamster. I'm using the [online docs](https://docs.chaosgroup.com/display/VRAY3MAX/Cryptomatte+%7C+VRayCryptomatte) as reference for the Cryptomatte. There's a highlight there similar to what you've mentioned:
![image](https://user-images.githubusercontent.com/16534677/32274757-5da30284-bf43-11e7-8336-14a357e8780e.png)
I did used the exported image from the render folder instead 😄
