### ISSUE TITLE
Prefiltering LC - Log writes out even after stopping render

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#265]
Hi,

1. fire a render to disk with the attached scene 
2. after the light cache is build **and** prefiltering starts - hit stop
3. the log continues writing the percentage of prefiltering and has to complete until any new render can be executed

This is no problem with smaller renders, but not with heavy scenes. Also the prefilteing log could be shrinked in step size I suggest.

[prefiltering.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1435688/prefiltering.zip)

Thanks for looking into it!

Cheers!
Dominik

**Comment by galagast** [comment]
I can confirm this.
[prefilter_bug.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1436095/prefilter_bug.zip)
In the attached MOV file, I hit the stop button (at around 8secs), yet prefiltering continues.

**Comment by bdancer** [comment]
Should print stuff fast again https://github.com/ChaosGroup/vray-for-houdini/commit/0cc4de773ade022a3d1029253279ad6ec4c5ed9b.

**Comment by galagast** [comment]
I can confirm that this is now fixed 👍 
Hitting the stop button would now end pre-filtering.

**Comment by dominik2608** [comment]
Sorry for the delayed answer - I can confirm too
