### ISSUE TITLE
Yeti Procedural support

### ISSUE THREAD

**Issue by Eiken** [ChaosGroup/vray-for-houdini#266]
Are you planning to add something to make it possible to use the yeti procedural when rendering?

Similar to https://docs.chaosgroup.com/display/VFK/Setup+for+rendering+Yeti+caches

**Comment by Eiken** [comment]
I hacked togheter my own preview node for the caches but I have no idea how to make em render :)

**Comment by bravehamster** [comment]
Hey @Eiken , iirc Yeti is not available in Houdini so you're essentially asking for a node to load the Yeti cache files in your Houdini scene and render them, correct ?

**Comment by bdancer** [comment]
You could export Yeti to the *.vrscene file and then use VRayScene node to load it. However, I'll need to make some additions to make it possible to re-shade it (if this is needed).

**Comment by Eiken** [comment]
@bravehamster more like just taking the path and translating it to correct vrscene syntax when rendering like the katana translator. I'm pretty sure the stand alone procedural should render it then.

@bdancer that could work for us. It would just have some default shading initially so being able to assign a new material would be needed.

**Comment by Eiken** [comment]
Tried loading a vrscene with Yeti and got 

Crash report from erjo; Houdini Core Version 16.0.705 [linux-x86_64-gcc4.8]
Uptime 114 seconds
Thu Nov  2 13:04:11 2017
Caught signal 11

Traceback from 3414 ThreadId=0x7f4d4c48cb80
AP_Interface::coreDumpChaser(UTsignalHandlerArg) <libHoudiniUI.so>
AP_Interface::si_CrashHandler::chaser(UTsignalHandlerArg) <libHoudiniUI.so>
signalCallback(UTsignalHandlerArg) <libHoudiniUT.so>
UT_Signal::UT_ComboSignalHandler::operator()(int, siginfo*, void*) const <libHoudiniUT.so>
UT_Signal::processSignal(int, siginfo*, void*) <libHoudiniUT.so>
_L_unlock_13 <libpthread.so.0>
GA_Topology::linkVertex(long, long) <libHoudiniGEO.so>
GA_Topology::wireVertexPoint(long, long) <libHoudiniGEO.so>
VRayForHoudini::VRaySceneRef::getPackedDetail(GU_PackedContext*) const <vray_for_houdini.so>
GT_GEOPrimPacked::getPackedDetail() const <libHoudiniGEO.so>
GT_GEOPrimPacked::getFullGeometry(GT_RefineParms const*, bool&) const <libHoudiniGEO.so>
GT_GEOPrimPacked::refine(GT_Refine&, GT_RefineParms const*) const <libHoudiniGEO.so>
GT_Primitive::refinePrimitive(UT_IntrusivePtr<GT_Primitive> const&, GT_RefineParms const*) <libHoudiniGEO.so>
GUI_GeoRender::processPrim(GU_ConstDetailHandle const&, UT_IntrusivePtr<GT_Primitive>&, GT_RefineParms&, int&, GR_DisplayOption const&, GR_UpdateReason, char const*, UT_Array<UT_IntrusivePtr<GT_Primitive> >&, bool, int&) <libHoudiniAPPS3.so>
GUI_GeoRender::processPrim(GU_ConstDetailHandle const&, UT_IntrusivePtr<GT_Primitive>&, GT_RefineParms&, int&, GR_DisplayOption const&, GR_UpdateReason, char const*, UT_Array<UT_IntrusivePtr<GT_Primitive> >&, bool, int&) <libHoudiniAPPS3.so>
GUI_GeoRender::processPrimitives(GU_ConstDetailHandle const&, UT_IntrusivePtr<GT_Primitive>&, GT_RefineParms&, int&, GR_DisplayOption const&, GR_UpdateReason, char const*, UT_Array<UT_IntrusivePtr<GT_Primitive> >&) <libHoudiniAPPS3.so>
GUI_GeoRender::update(RE_Render*, GR_DisplayOption*, GUI_SetupResult, GR_DecorationOverride, char const*, bool&, UT_Array<UT_Pair<UT_Matrix4T<double>, UT_Vector2T<int> > > const&) <libHoudiniAPPS3.so>
GUI_DetailLook::updateForRender(RE_Render*, GUI_DisplayOption&, RE_LightList*, GR_DecorationOverride, char const*, UT_Array<UT_Pair<UT_Matrix4T<double>, UT_Vector2T<int> > > const&, bool&, bool, GR_UpdateReason) <libHoudiniAPPS3.so>
DM_VPortAgent::setupGeometry(RE_Render*) <libHoudiniAPPS3.so>
DM_VPortAgent::renderViewport(RE_Render*, int, int) <libHoudiniAPPS3.so>
DM_VPortAgent::doRender(RE_Render*, int, int) <libHoudiniAPPS3.so>
DM_Viewport::doRender(RE_Render*, int, int) <libHoudiniAPPS3.so>
UI_Feel::renderMe(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRenderKids(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRender(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::renderMe(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRenderKids(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRender(RE_Render*, int, int) <libHoudiniUI.so>
UI_Viewport::reRender(RE_Render*, bool) <libHoudiniUI.so>
UI_Window::renderChildViews(RE_Render*) <libHoudiniUI.so>
UI_Window::doRedrawSubclass() <libHoudiniUI.so>
dm_ViewLayoutWindow::doRedrawSubclass() <libHoudiniAPPS3.so>
UI_Window::doRedraw() <libHoudiniUI.so>
UI_Queue::doWindowRedraws() <libHoudiniUI.so>
UI_Timer::handleEvent(UI_Event*) <libHoudiniUI.so>
UI_Manager::handleEvent(UI_Event*) <libHoudiniUI.so>
UI_Queue::processNextEvent() <libHoudiniUI.so>
UI_Queue::drain() <libHoudiniUI.so>
UI_Queue::eventLoop() <libHoudiniUI.so>
main <libHoudiniUI.so>
__libc_start_main <libc.so.6>
OPUI_MainApp::precreateApplication(int&, char const**) <houdinicore-bin>

**Comment by Eiken** [comment]
I can share the vrscene file by email

**Comment by bdancer** [comment]
@Eiken yes, will be helpful.

**Comment by Eiken** [comment]
You have mail at your chaosgroup mail

**Comment by bdancer** [comment]
While we're fixing the preview mesh generation crash, here is what I came up with for material overrides.
Implemented the same way as for Max/Maya with the override snippet:
![vfh_vrayscene_overrides_yeti](https://user-images.githubusercontent.com/319784/32332534-68cf5792-bfee-11e7-9514-7054481df8d2.png)

**Comment by bdancer** [comment]
@Eiken please try the new build.

**Comment by Eiken** [comment]
Not crashing any more!
Thanks!

However when I add libvray_pgYetiVRay.so to the VRAY_PLUGINS_x64 it still can't find the procedural.

[2017/Nov/7:11:33:53] VFH | Warning| V-Ray: Failed to create object of type "pgYetiVRay"

Is there some other environment variable that I might need to set?
Current variables:

VRAY_APPSDK=/network/storage/V-RayHoudini/linux/16.0/vfh-ee84971/appsdk
VRAY_AUTH_CLIENT_FILE_PATH=/mnt/home/erjo/git/resources/vray/regularlicense
VRAY_FOR_HOUDINI_AURA_LOADERS=/network/storage/V-RayHoudini/linux/16.0/vfh-ee84971/vfh_home/libs
VRAY_PLUGINS_x64=/network/storage/Yeti/Yeti-v2.1.15_Maya2017-linux64/bin
VRAY_PLUGIN_DESC_PATH=/network/storage/V-RayHoudini/linux/16.0/vfh-ee84971/plugins_desc
VRAY_UI_DS_PATH=/network/storage/V-RayHoudini/linux/16.0/vfh-ee84971/ui
VRAY_VFB_ALWAYS_ON_TOP=1

**Comment by Eiken** [comment]
appsdk/bin/plugins/
This is where other plugins live but I don't see any environment variable that configures that. Just the base path of APPSDK.

Katana seems to have a VRAY_FOR_KATANA_PLUGINS_x64 variable to use

**Comment by Eiken** [comment]
I made a symlink to libvray_pgYetiVRay.so in appsdk/bin/plugins/ and it renders :)

Now I just need an environment variable for it instead.

**Comment by bdancer** [comment]
> Is there some other environment variable that I might need to set?

Added https://github.com/ChaosGroup/vray-for-houdini/commit/1b15cff0c1693e90eb9efb273d5cb8691f433301.

**Comment by Eiken** [comment]
Great!

So now I have some kind of base and know that the procedural works. It would be swell if it worked directly with .fur files as the Katana workflow but this is a big step forward.

For future development do you think it would be possible to create like a "VRayProcedural" node?
It could have a text paramter for procedural name and a key, value parameter for the additional attributes.

Then at rendertime it would convert it to:
```
pgYetiVRay nodeName@geometry285 {
  density=1;
  length=1;
  width=1;
  sampleGenerator=ListFloatHex("ZIPC040000000C000000eAFjcKhyAQAB/AD/"); # i'll have to check with colin about this paramter
  verbosity=1;
  threads=0;
  file="/path/to/stuff.1001.fur";
  imageSearchPath="";
  dynamicHairTesselation=1;
  segmentLength=4;
}

```

**Comment by bdancer** [comment]
@Eiken since we have a VRayScene node I'm not sure we need to have any additional nodes.

**Comment by Eiken** [comment]
If it was implemented like this I could also combine it more easily with my "preview" otl to make a pretty good "Yeti for VRayHoudini" full solution.

**Comment by bdancer** [comment]
@Eiken that's exactly one of the reasons of having this project open source. Contributions are very welcome =)

**Comment by Eiken** [comment]
I'd be happy to contribute the otl and python code but my c++ is very rusty. 

Another reason for not using vrscene is that the export procedure in maya is very tedious. You can't just select something and export it. You have to do all kinds of hacks to get a vrscene of your selection exported like setting "Render Selection" in the maya native render view. It's overall very not pipeline friendly.

**Comment by bdancer** [comment]
@Eiken yeh, makes sense, write me a email pls.

**Comment by bdancer** [comment]
Let's see how it'll work https://github.com/ChaosGroup/vray-for-houdini/commit/677cc2fa27d7a492769a5b5145f10681ec20e504.

**Comment by Eiken** [comment]
Awesome! Seems latest nightly build got stuck at 44c79ab so i'll wait until tomorrows.

**Comment by bdancer** [comment]
@Eiken I've uploaded some new ones. Linux builds will be a bit later...

**Comment by Eiken** [comment]
Unfortunately i'm on linux but i'll check the nightlies page for when a linux build shows up.

**Comment by Eiken** [comment]
`[2017/Nov/9:18:36:39] VFH |   Debug| VRayPgYeti::cookMySop()
[2017/Nov/9:18:36:53] VFH |   Debug| Initialize SOHO...
[2017/Nov/9:18:36:53] VFH |   Debug| Processing Mode: "generate"
[2017/Nov/9:18:36:53] VFH |   Debug| IPR Port: 43501
[2017/Nov/9:18:36:53] VFH |   Debug| Driver: /out/vray_ipr
[2017/Nov/9:18:36:53] VFH |   Debug| Camera: /obj/cam1
[2017/Nov/9:18:36:53] VFH |   Debug| Now: 41.696
[2017/Nov/9:18:36:53] VFH |   Debug| Res: [1280, 720]
[2017/Nov/9:18:36:53] VFH |   Debug| Crop: 0-0 1280 x 720
[2017/Nov/9:18:36:53] VFH |   Debug| Camera: /obj/cam1
[2017/Nov/9:18:36:53] VFH |   Debug| vfhInit()
[2017/Nov/9:18:36:53] VFH |   Debug| Trying to stop LnxProcessCheck with thread [(nil)]
[2017/Nov/9:18:36:53] VFH |   Debug| Starting LnxProcessCheck from pid 18178
[2017/Nov/9:18:36:53] VFH |   Debug| Child vfh_ipr is running with pid 18259
[2017/Nov/9:18:36:53] VFH |   Debug| Starting thread monitoring child pid
[2017/Nov/9:18:36:53] VFH |   Debug| VRayPluginRenderer()
[2017/Nov/9:18:36:53] VFH |   Debug| VRayExporter()
[2017/Nov/9:18:36:53] VFH |   Debug| Proc wait thread started
[2017/Nov/9:18:36:53] VFH |   Debug| newVRayInit()
[2017/Nov/9:18:36:53] VFH |   Debug| InstancesStorage: "VRayInstances18178"
[2017/Nov/9:18:36:53] VFH |    Info| Using V-Ray AppSDK 1.22.00 c397ae6 [ houdini] Aug 22 2017 13:50:32
[2017/Nov/9:18:36:53] VFH |   Debug| newVRayRenderer()
[Thu Nov  9 18:37:07 2017] Yeti 2.1.15: Yeti v2.1.15, built on Jul 17 2017 at 19:10:07
[Thu Nov  9 18:37:07 2017] Yeti 2.1.15: (c) 2010-Present Peregrine Labs a division of Peregrine Visual Storytelling Ltd. All rights reserved.
[2017/Nov/9:18:37:08] VFH |    Info| Using V-Ray 3.60.03 0a6d227 Aug 22 2017 13:50:32
[2017/Nov/9:18:37:08] VFH |   Debug| newVRayRenderer()
[2017/Nov/9:18:37:11] VFH |   Debug| VRayExporter::setAnimation(0)
[2017/Nov/9:18:37:11] VFH |   Debug| Time: 41.6957
[2017/Nov/9:18:37:11] VFH |   Debug| Frame: 960
[2017/Nov/9:18:37:11] VFH |   Debug| V-Ray time: 41.6957
[2017/Nov/9:18:37:11] VFH |   Debug| V-Ray frame: 0
[2017/Nov/9:18:37:11] VFH |   Debug| VRayExporter::exportView: Resetting view...
[2017/Nov/9:18:37:11] VFH |    Info| VRayExporter::setRenderSize(1280, 720)
[2017/Nov/9:18:37:11] VFH |   Debug| VRayExporter::exportScene()
[2017/Nov/9:18:37:11] VFH |   Debug| addOpInterest(geo1)
[2017/Nov/9:18:37:11] VFH |   Debug| addOpInterest(VRayNodeVRayPgYeti1)
[2017/Nov/9:18:37:11] VFH |   Error| Node "VRayNodeVRayPgYeti1": Plugin "" description is not found!
[2017/Nov/9:18:37:11] VFH |   Debug| [] PluginDesc.pluginID is not set!
`
Error log

**Comment by bdancer** [comment]
@Eiken sry, I've forgot to push new file https://github.com/bdancer/plugins_desc/commit/16e49144809be594d79a960e19ed36de11266951.
You could download it and copy to "plugins_desc" directory.

**Comment by Eiken** [comment]
Now I don't get errors when I toggle parameters on the node anymore but no fur when rendering. Log is:
```
2017/Nov/10:10:10:08] VFH |   Debug| newVRayRenderer()
[Fri Nov 10 10:10:22 2017] Yeti 2.1.15: Yeti v2.1.15, built on Jul 17 2017 at 19:10:07
[Fri Nov 10 10:10:22 2017] Yeti 2.1.15: (c) 2010-Present Peregrine Labs a division of Peregrine Visual Storytelling Ltd. All rights reserved.
[2017/Nov/10:10:10:22] VFH |    Info| Using V-Ray 3.60.03 0a6d227 Aug 22 2017 13:50:32
[2017/Nov/10:10:10:22] VFH |   Debug| newVRayRenderer()
[2017/Nov/10:10:10:26] VFH |   Debug| VRayExporter::setAnimation(0)
[2017/Nov/10:10:10:26] VFH |   Debug| Time: 41.6957
[2017/Nov/10:10:10:26] VFH |   Debug| Frame: 960
[2017/Nov/10:10:10:26] VFH |   Debug| V-Ray time: 41.6957
[2017/Nov/10:10:10:26] VFH |   Debug| V-Ray frame: 0
[2017/Nov/10:10:10:26] VFH |   Debug| VRayExporter::exportView: Resetting view...
[2017/Nov/10:10:10:26] VFH |    Info| VRayExporter::setRenderSize(1280, 720)
[2017/Nov/10:10:10:26] VFH |   Debug| VRayExporter::exportScene()
[2017/Nov/10:10:10:26] VFH |   Debug| addOpInterest(geo1)
[2017/Nov/10:10:10:26] VFH |   Debug| addOpInterest(VRayNodeVRayPgYeti1)
[2017/Nov/10:10:10:26] VFH |   Error| Node "VRayNodeVRayPgYeti1": Plugin "" description is not found!
[2017/Nov/10:10:10:26] VFH |   Debug| [] PluginDesc.pluginID is not set!
[2017/Nov/10:10:10:26] VFH |   Debug| addOpInterest(vrayLightDome)
[2017/Nov/10:10:10:26] VFH |   Debug| VRayExporter::renderFrame(960.000)
[2017/Nov/10:10:10:26] VFH |    Info| Starting render for frame 0 [41.696]...

```

**Comment by bdancer** [comment]
@Eiken ok I got it, my bad, I a workaround connect it to Transfrom node.

**Comment by Eiken** [comment]
[](url)
![screenshot from 2017-11-10 11-36-46](https://user-images.githubusercontent.com/2283953/32654442-8aec6284-c60b-11e7-96ba-3ba2c6ac5ccc.png)

All parameters works as well. Adjusting of density,length and width.
Shader changes can be done without having to regenerate the fur.

Very nice!

**Comment by bdancer** [comment]
@Eiken I'm going to update the AppSDK/V-Ray versions and Yeti won't work anymore (well until Yeti guys  update their plugin for new V-Ray SDK).

**Comment by Eiken** [comment]
No problem. Waiting for the node restructure before we kick off a live project in houdini

**Comment by mdelosrios** [comment]
I'm jumping in to ask what the status for this is?

Are there any instructions for a windows environment on rendering yeti caches?

I see that there is a node called V-Ray VrayPgYeti that allows you to load yeti caches, however when I try to render it errors complaining about "Invalid plugin class name error"

I have pointed out the env variable VRAY_PLUGINS_x64 to where the vray_pgYetiVRay.dll lives (from my maya plugin), but it seems to error saying the specify procedure could not be found.

Using V-Ray AppSDK 2.00.00 aa392fbf 
Using V-Ray 4.01.03 aa392fbf 

Cheers

**Comment by bdancer** [comment]
@mdelosrios you should ask Yeti is they support V-Ray Next.

> I have pointed out the env variable VRAY_PLUGINS_x64 to where the vray_pgYetiVRay.dll lives
You have to use VRAY_FOR_HOUDINI_PLUGINS variable for Houdini.

> but it seems to error saying the specify procedure could not be found.

Mean this versions is not V-Ray 4.x compatible.

**Comment by bdancer** [comment]
Yeti guys are working on Next support so you should be able to render soon.

**Comment by mdelosrios** [comment]
Perfect! Thanks for the heads up!

**Comment by bdancer** [comment]
So the primitive for Yeti is there, once Yeti will support V-Ray Next (may be they already do) you'll be able to render Yeti cache files directly.
