### ISSUE TITLE
UV RE

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#267]
Hi,
I would like to get UVs  in my RE. So I piped from a sampler node uv to an extr tex. But no luck. Is it not yet supported?

**Comment by bdancer** [comment]
Not sure it'll work this way. Try "meshvertexchannel" and set the name to the name of your uv attribute.

**Comment by dominik2608** [comment]
Works great!!! Never thought of that node, hehe! Thanks!!

**Comment by dominik2608** [comment]
Can be closed
