### ISSUE TITLE
Domelight | Rotation not affected

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#268]
Hi,

I can't rotate my domelight through the transform parameters.

Is this broken?
vfh-184096b

**Comment by bravehamster** [comment]
Hey there, the transformation parameters on the dome light node don't work at the moment. 
You could create a simple setup that allows you to transform the texture [like this](https://chaossw-my.sharepoint.com/personal/gosho_genchev_chaosgroup_com/_layouts/15/guestaccess.aspx?docid=06a42869a0ab84fa493c3a1ec804011ae&authkey=AdM1A3GQcvh4YjhS5X_cu6U&e=8430368af53d40478ac0a1b28af0cb48)

**Comment by blented** [comment]
@bravehamster it seems the example file you posted no longer works in the latest builds, could we perhaps get an update?  Though a better solve would definitely be to just implement the transform on the light dome.

**Comment by bravehamster** [comment]
Yup, it was fixed at one point and broke during the transition. It's already logged.
Cheers!
