### ISSUE TITLE
Softbox Texture not working

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#269]
Hi,

it seems that the softbox texture does not work at all - or I am doing something wrong....
vfh-184096b

Cheers
Dominik

**Comment by bdancer** [comment]
Yeh, smth got broken, anyway it'll be "broken" even more after https://github.com/ChaosGroup/vray-for-houdini/issues/214, so I'll check this after implementing https://github.com/ChaosGroup/vray-for-houdini/issues/214.
