### ISSUE TITLE
Render with take not working with RT

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#270]
Hi, 

I have an override on a switch in /mat. driving a color
With Render To Disk everything is fine, but ignored in RT. Only if I switch the take to the desired one in the top right corner from the take list.

Cheers
Dominik

**Comment by bdancer** [comment]
In RT ("Render RT" button) or IPR ("Render View")?

**Comment by dominik2608** [comment]
In RT ("Render RT" button) Vray Frame Buffer

**Comment by dominik2608** [comment]
Here is a scene:
[takeRT.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1440978/takeRT.zip)

**Comment by bdancer** [comment]
@dominik2608 this appears to be pretty tricky, won't be implemented very fast.

**Comment by dominik2608** [comment]
Hi Andrei,

what do think how long it will take to get it implemented, some more days or longer?
It would be amazing to have it in my particular case, because I have to light a lot different objects where I really would like to take the advantage to switch takes in RT.

Thanks and cheers
Dominik

**Comment by bdancer** [comment]
@dominik2608 would you need to switch takes during the RT session running?

**Comment by dominik2608** [comment]
Hm, would be super cool - but - if it would take too long to implement I would also be fine with per session

**Comment by bdancer** [comment]
Hope this https://github.com/ChaosGroup/vray-for-houdini/commit/824993825c310f65220f3089e528c5db18613ae2 will work.

**Comment by dominik2608** [comment]
Cool - is it in the download section already?

**Comment by bdancer** [comment]
@dominik2608 not yet, tomorrow.

**Comment by dominik2608** [comment]
ok - thx

**Comment by dominik2608** [comment]
Works as described! Thx! For those interested : just be aware that changes made in the RT session in the particular take are temporary and are gone after stopping RT.

**Comment by bdancer** [comment]
> For those interested: just be aware that changes made in the RT session in the particular take are temporary and are gone after stopping RT.

Could you give more details? Should this be fixed?

**Comment by dominik2608** [comment]
Hi Andrei. 

I  think it should be fixed, because normally I would want to have even changes made during a RT session  be permanent, right?

I also encountered several crashes in the past couple of days with my scenes using the RT take feature. But unfortunately still not found something reproduceable....

**Comment by bdancer** [comment]
@dominik2608 I'm really not sure why it discards the changes, I'm not doing it myself =) Ok, I'll figure it out.
