### ISSUE TITLE
Vray Rect light - no alpha option for texture

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#271]
Hi,

I am missing the option to use an alpha for a texture. Like in maya e.g.
Without you always face edges when using textures like gradients for example...

Thanks 
Dominik

**Comment by dominik2608** [comment]
Hi,
any news on that topic? 
Thx
Dominik

**Comment by bdancer** [comment]
@dominik2608 have you tried it? I've added a few options.

**Comment by dominik2608** [comment]
Sorry - Had no time, I have delivery phase at the moment. Could not implement the feature in the current show, was to toght to the deadline. I'll report as soon as possible

**Comment by dominik2608** [comment]
Hi Andrei,
so I  now found some time to test it. For textures with own aplpha channels it seems to work as expected, but I miss the options from Maya, where I can put the red channel of my texture to the alpha input of the Vray Rect Light. That would be great for textures not carrying any alpha and avoiding creating one.

Would that be possible?
Cheers
Dominik

**Comment by bdancer** [comment]
@dominik2608 how do you want this to be implemented? A texture network?

**Comment by dominik2608** [comment]
Hm... I am not the expert in Houdini to decide that... or I have to use a COP Network ...

**Comment by bdancer** [comment]
You could do smth like this:
![vfh_combine_alpha](https://user-images.githubusercontent.com/319784/33270692-9234f1de-d38d-11e7-9f65-89206a421ba7.png)
 and then specify texture as "op:/mat/output" in the light.

**Comment by Dentzz1** [comment]
Would you need to place a channel_named node to map the bitmap image and checker texture? I think I have to do this with other vray materials but would it not be needed for lights? Also this be piped into texture or does it need to be put into intensity or color?

**Comment by bdancer** [comment]
1. This setup works without any additional mappings.
2. To "Texture".

**Comment by dominik2608** [comment]
I'll give it a try as soon I have a little more time... deadlines still in front of me ;-)
