### ISSUE TITLE
OSL Support

### ISSUE THREAD

**Issue by Pirminus** [ChaosGroup/vray-for-houdini#272]
Hey!

I would like to use the OSL - Thin Film Shader in Houdini. unfortunately I can't find a way to create an OSL - Shader ? Will this feature be implementend ?

Best regards
Pirmin

**Comment by bdancer** [comment]
Yes, it will be implemented.

**Comment by bdancer** [comment]
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/c0e7ed5929f8794a9b05f142db96f96c0b4372aa. Will be available in the next nightly build.
