### ISSUE TITLE
Change VRay-Renderer for VFB

### ISSUE THREAD

**Issue by Pirminus** [ChaosGroup/vray-for-houdini#275]
Hey!

I would like to have a direct comparison between different VRay-render Rops, but as soon as I select another VRay-Renderer and Press "Render" from the Shelve it opens a second VFB. May it be possible to use just one Framebuffer or to change the VRay-Renderer within the Framebuffer itself ?

Best regards
Pirmin

**Comment by bdancer** [comment]
No, this is not possible, every node is a separate V-Ray instance.
