### ISSUE TITLE
Displacement with SHOP-Noise

### ISSUE THREAD

**Issue by Pirminus** [ChaosGroup/vray-for-houdini#277]
Hey!

I wanted to Displace a Grid with the Maya Noise within a VRay-Material, but it does not seem to work.
What I did:

![screenshot from 2017-11-10 14-41-44](https://user-images.githubusercontent.com/32384165/32661032-8950af7e-c625-11e7-910f-184e8f074c87.png)
![screenshot from 2017-11-10 14-42-57](https://user-images.githubusercontent.com/32384165/32661037-8d1a1cbc-c625-11e7-9b10-4e4d2838c1cc.png)

I saw at the VRay for Blender Documentation that you have to wire an Object-Node to the Displacements Mesh Input, but it looks like there is nothing similar in vfh...

Is there a workaround to use procedural noise with displacement, or did I something wrong ?

Best Regards
Pirmin

**Comment by bdancer** [comment]
Look like a bug https://github.com/ChaosGroup/vray-for-houdini/commit/8c4429cc8fcd6ba3a6ee10132b979bb8d6f9deb9.
