### ISSUE TITLE
GPU or Hybrid rendering status

### ISSUE THREAD

**Issue by Dentzz1** [ChaosGroup/vray-for-houdini#278]
What is the status or version of Vray GPU rendering in Houdini? Was curious where it is on things such as hybrid rendering, support for different material and features which I think are available for older versions of vray or at least can confirm work when I try it on vray for modo. Not sure if Houdini is running an older vray version GPU isn't being focused on or these are bugs.

**Comment by bdancer** [comment]
Use ocldeviceselect.exe to select GPU/CPU.
GPU support status is not yet exposed in UI.

**Comment by Dentzz1** [comment]
Okay was able to get that. With ocldeviceselect.exe it says successfully parsed environment variable  OpenCL platforms. Is the cpu operating as a CUDA device like it says for 3.6 and the environment variable is just labeled open cl or is the cpu running as an Opel CL device?

Is low thread priority not exposed as well?

When using GPU are the controls under RT or are they somewhere else? Setting max noise in RT seems to have no impact when using GPU in "IPR area" with Render RT or using Render to disk.

**Comment by bdancer** [comment]
Should be better https://github.com/ChaosGroup/vray-for-houdini/commit/4601f1f409c532af50ef8b2845e80f2ab8480050.
