### ISSUE TITLE
Mesh Light

### ISSUE THREAD

**Issue by Pirminus** [ChaosGroup/vray-for-houdini#279]
Hey!

I have an issue using the VRay-Mesh-Light. Just a simple Sphere as Vray Mesh-Light. I attached a scene and a crashlog. 

[Mesh_Light_Crash.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1473755/Mesh_Light_Crash.zip)

Best Regards
Pirmin

**Comment by bravehamster** [comment]
Hey there, the crash is not present in the latest nightly but the Mesh Light doesn't produce any illumination. It's a known issue that will be resolved soon.
