### ISSUE TITLE
Houdini Locks on Rendering

### ISSUE THREAD

**Issue by Dentzz1** [ChaosGroup/vray-for-houdini#280]
Using today's nightly 4601f1f when clicking the Render to Disk button Houdini locks so that nothing can be moved or changed in the interface. Stopping the render with the vray frame buffer returns the program back to normal.  Using the IPR/Render RT vray and houdini interface works normally while rendering. Anyone else having this issue?

**Comment by postcontrol** [comment]
I think this is deliberately made.  I think this is also "feature" which allows piping render nodes in chain, correct me if I'm wrong!? When pressing rendering to disk, also mantra locks houdini interface. In mantra and vray there's "render to disk in background" which does not lock houdini's interface when rendering to disk. I have not tried background rendering with vray, so I don't know if it works. 

Cheers,
.m

**Comment by Dentzz1** [comment]
Pretty sure it didn't lock on the previous vray nightly build and this is not how mantra works when rendering a single frame. This locking does happen when rendering a frame range (probably to avoid changes not to the current frame being rendered but later frames) which is good. You are correct that you can render in the background which you save a file and it runs the rendering as a separate process that can keep running/rendering while you operate Houdini or even close the application (also good). 

So probably there is a new line of code that was added
(maybe int interactive{0};(I don't code so I don't really know))
which locks the interface that was added when new additions were made to the GPU code. 

I found this frustrating when I tried it and kind of hope that this locking would not happen on single frame render or render in background but only on render frame range. However there might be reasons this isn't possible or that it is only happening on my machine.

**Comment by bdancer** [comment]
@Dentzz1 As @postcontrol already wrote this was done to allow ROP chaining. If I'll find a way to detect such cases I'll remove the lock, but currently this is how it works.

**Comment by Dentzz1** [comment]
@postcontrol @bdancer That makes sense, and it is definitely more important to have and keep ROP chaining. When you do render with a chain you get or need to go into the Controls... where you are given a choice of just a single node "Only this Node" or "This Node and all Inputs" which also locks the interface. Since Vray renders out to the vray frame buffer I figure that in operation it is very similar to the "Render to MPlay" which does not lock the interface on a current frame render.

**Comment by Dentzz1** [comment]
@bdancer @postcontrol Just a thought but maybe creating a window in Houdini like a progress bar would also help so that you can know it is rendering and not that the program froze?
