### ISSUE TITLE
Vray displacement: mat context

### ISSUE THREAD

**Issue by postcontrol** [ChaosGroup/vray-for-houdini#281]
Hi,

Is there anyway to get material specific displacement from mat context? Just curious.
I have rbd sim which varies couple of objects and only few should has displacement. Material has been assigned in SOP level and displacement should be bound to material not object.
I think now only way is to split result of rbd sim to objects and do displacement in object level.
I'm also using same objects elsewhere which are not included in rbd sim so I need to copy all displacement values in multiple places where I use those objects. 

Of course there's option to use "From SHOP" but I have already created all materials + textures in mat context :). 

Cheers,
.m

**Comment by bdancer** [comment]
I've pushed some changes a while ago, now you could use "V-Ray Material Output" node in MAT context and simply assign it as the material.

**Comment by dominik2608** [comment]
Hi,

Could anybody describe the workflow a little bit more in detail? I don't get it... 
Cheers and thx

Dominik

**Comment by bdancer** [comment]
@dominik2608 [vfh_displacement.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1513496/vfh_displacement.zip)

**Comment by dominik2608** [comment]
Thx Andrei!
