### ISSUE TITLE
Vray IPR: Cancel only cancels updating render view

### ISSUE THREAD

**Issue by postcontrol** [ChaosGroup/vray-for-houdini#283]
Hi,

It seems that vray ipr only cancel updating render view but remains rendering in background, when using ipr in render view. Even if I cancel render with (X) button houdini console still loweres noise threshold and CPU usage remains 100%: 
Qt Error: QWindowsPipeWriter::write failed. ()
[2017/Nov/20:12:29:51] VFH [Info] V-Ray: Noise threshold lowered to 0.142857 with 12.8 percent active pixels.
[2017/Nov/20:12:30:00] VFH [Info] V-Ray: Noise threshold lowered to 0.090909 with 9.2 percent active pixels.

Win10, vfh-2010-4601f1f-hfs16.5.268-qt5-windows, H16.5.268, Vray IPR with CPU mode.

Cheers,
.m

**Comment by bdancer** [comment]
To make this work correctly we'll have to drop 16.0 support, because 16.5 contains API fixes that we need. So, I'll fix this a bit later.
