### ISSUE TITLE
Crash after moving light in RT with VFB

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#286]
Hi,

I have attached a scene file. If I fire a RT render and then rotate the RectLight - Houdini crashes.
[vrayRectLight_Caustics.zip](https://github.com/ChaosGroup/vray-for-houdini/files/1506052/vrayRectLight_Caustics.zip)

Cheers
Dominik

**Comment by bdancer** [comment]
@bravehamster could you reproduce this?

**Comment by bravehamster** [comment]
@bdancer , it appears that the issues is related to the Render Region in the Frame buffer rather than the RectLight itself. 

If you 1) start RT then 2) draw a render region and 3) try to transform anything in the scene, Houdini will crash. 
I'll open a ticket. 

@dominik2608 , good catch, thanks !

**Comment by dominik2608** [comment]
Glad to help!

**Comment by dominik2608** [comment]
> @bdancer , it appears that the issues is related to the Render Region in the Frame buffer rather than the RectLight itself.

I just had the case without region rendering. I rotated the light and houdini freezes (no crash)

**Comment by bdancer** [comment]
Strange, can't reproduce this...
