### ISSUE TITLE
Render Elements Node does not save

### ISSUE THREAD

**Issue by Dentzz1** [ChaosGroup/vray-for-houdini#288]
If I create a render elements node in rop add some channels and link to the render elements network under the image folder it will render out fine. If I save the Houdini file and then reopen that file the render elements node disappears(or is deleted?) but the file path stays in the Render Elements Network so I know it was at some point created in that saved file.

Is this happening to anyone else?

**Comment by bravehamster** [comment]
@Dentzz1 , can you give me a Houdini and nightly build versions to check this ?

**Comment by Dentzz1** [comment]
@bravehamster 
I'm running Houdini 16.5.268
I think I am using 
vfh-2177-d989ffa-hfs16.5.268-qt5-windows

**Comment by dominik2608** [comment]
Hi,

I can't confirm, I am successfully using the above described workflow.
Hm, seems to be something strange 

Maybe Andrei will figure it out 

Cheers
Dominik

**Comment by postcontrol** [comment]
Hi,

I can confirm that same happens here. For me render element node where it will disappears is locating in obj -> subnet -> rop network -> render elements.

Win10,  vfh-2177-d989ffa-hfs16.5.268-qt5-windows, H16.5

Cheers,
.m

**Comment by dominik2608** [comment]
As info:
mine is living directly in /out beside the render ROP.

**Comment by Dentzz1** [comment]
After seeing @postcontrol post I tried it again. If I create the render element in the "out/render_element" it is able to save and be re opened. If it is created in "obj/ropnet1/render_element" it disappears after re-opening a save file.

**Comment by bdancer** [comment]
Reproduced, investigating...

**Comment by bdancer** [comment]
Seems to work now. At least with recent 16.5.
