### ISSUE TITLE
Drive shader parameters via custom attributes

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#289]
Hi,

I tried to set some attributes to drive a switcher in mat context via the 'Mesh Vertex Channel' Node, but had no luck.
Are there currently any limitations? 
Thx
Dominik

**Comment by bdancer** [comment]
Switcher is a Houdini node, it's queried only at export time.
What effect are you trying to achieve?

**Comment by dominik2608** [comment]
I have several user color nodes which are piped in different switches and these are going into different base materials
These switches should be driven on rendertime on different objects

**Comment by bdancer** [comment]
And who drives those switches?

**Comment by bdancer** [comment]
You could try using "user float" texture to drive "multi id" material. For textures I'll need to add "tex multi id".

**Comment by dominik2608** [comment]
![switches](https://user-images.githubusercontent.com/18614866/33776457-b5689ba8-dc41-11e7-9d69-9ae6880184d6.jpg)

**Comment by bdancer** [comment]
@dominik2608 yes, TexMulti + TexUserInteger should work just fine in this case, but I can't add them right now. I'll add them after https://github.com/ChaosGroup/vray-for-houdini/issues/214.

**Comment by dominik2608** [comment]
Ok! Basically when having object with the same shader requesting together always the same color, I used takes to drive the switches. But now I had the case that I had to put together object with the same shader but different colors. So having that opportunity would be awesome to get my scene cleaner💪😊

Thx Andrei!

**Comment by bdancer** [comment]
@dominik2608 could you pls send me this scene (or a simplified similar one)?

**Comment by dominik2608** [comment]
Hi Andrei,

I am on holidays already, so I would pass it over after 08.01.2018. 


Merry Christmas to you all out there and a happy new year!!!!

Dominik

**Comment by bdancer** [comment]
@dominik2608 tnx, man =) Happy holidays for u too!

**Comment by dominik2608** [comment]
you got mail!

**Comment by bdancer** [comment]
@dominik2608 this should work now, but you'll have to use V-Ray textures. There is a "User Integer" texture that you could along with:
1.  Multi material to drive material selection.
2.  Mutli texture to drive texture selection.
