### ISSUE TITLE
Binary to use for rendering generated vrscene files?

### ISSUE THREAD

**Issue by Eiken** [ChaosGroup/vray-for-houdini#291]
Im setting up our houdini pipeline to support rendering vray houdini on the farm.

I can generate vrscene files but after that what is the correct binary to use for rendering the vrscene files? With vray for maya we got vray.bin that can be used standalone but can't find any similar in the houdini package.

**Comment by bdancer** [comment]
You need V-Ray Standalone (Render Node).
Binary is vray.exe on Windows or "vray" shell wrapper for Linux.
Currently we're not shipping it with V-Ray for Houdini builds.

**Comment by Eiken** [comment]
Makes sense. So using the vray shell wrapper from a recent vray for maya should work fine? No custom shaders and stuff coming from houdini that is also needed?

**Comment by blented** [comment]
@Eiken as long as you're using a recent nightly of Maya it will have everything you need.  We've been using it without issue to render Houdini on the farm.
