### ISSUE TITLE
Is vray4houdini on hold? Noticed no new nightlies since December 4th

### ISSUE THREAD

**Issue by jonmoore1** [ChaosGroup/vray-for-houdini#292]
Just wondering what the status is? Schedule was stacked recently so first time checking in for a while.

**Comment by dominik2608** [comment]
> This is taking more time that I've expected. Hope to finish this month.

Andrei is rewriting a lot of stuff - so little patience is required
#214

**Comment by jonmoore1** [comment]
All good. Just wondered the state of things as I hadn't checked up on the development in a while.
Thanks for the update Dominik.

**Comment by Eiken** [comment]
Add me to the club of eager to play around with new version :)

**Comment by Dentzz1** [comment]
Yeah me too. Looking forward to seeing some new nightlies especially after 16.5.378 added a supplementary license. Is it vray next that they were showing DR with GPU rendering or is that something that already exists?

**Comment by bdancer** [comment]
> Is it vray next that they were showing DR with GPU rendering or is that something that already exists?

AFAIR, DR works with GPU from the beginning.

**Comment by jonmoore1** [comment]
Correct me if I'm wrong, but isn't one of the easiest ways to utilise GPU DR via the command line using the V-Ray Standalone. I know this was the way of things with Maya until RT was enabled as a production rendering option via the interface. There's very clear documentation on this in the V-Ray for Modo doc pages as Modo doesn't currently allow for RT animations via the interface.

**Comment by jonmoore1** [comment]
@bdancer - hadn't realised that you were active again. Just checked the nightlies and there's new stuff to play with. My SDK license is about to end. How much longer do you expect this process to be until V-Ray for Houdini is considered out of beta (I just want to be sure I ask for an appropriate extension)?

**Comment by bdancer** [comment]
@jonmoore1 there are drop down menus on V-Ray ROP to enable GPU device (for RT/IPR and production). Of course you could also render *.vrscene via Standalone enabling GPU with the command line switch.

> How much longer do you expect this process to be until V-Ray for Houdini is considered out of beta

First, we'll re-enable nightlies based on V-Ray 4.x, then we'll see...

**Comment by Dentzz1** [comment]
@bdancer @jonmoore1 Oh cool. A few months ago Blago or Vlado had posted a video with DR working with RT and the adaptive image sampler. Thought it only worked with the bucket sampler and didn't know that the feature had been implemented for awhile.

**Comment by Eiken** [comment]
Any more news?

**Comment by jonmoore1** [comment]
As far as I know, they're waiting for things to firm up ref V-Ray 4 (Next). Once things are stable, they'll recommence integration work based on VR4.

**Comment by bdancer** [comment]
Very sorry for such a huge delay, still fixing compatibility issues.
Will post some builds asap.

**Comment by bdancer** [comment]
Some libraries we are using at the project are not yet ready for V-Ray 4.x, but we are working on it...

**Comment by vinyvince** [comment]
Vray 4.x? Isn't the latest release 3.6

**Comment by StrobFX** [comment]
Hi Andrei, do you have any idea of how much time we have to wait (minimum) to be able to try V-Ray 4 in Houdini? I check here everyday ;)

**Comment by vinyvince** [comment]
Yeah good point to ask and hopefully it will be stable enough

**Comment by ronald-a** [comment]
@bdancer _Does this mean there are new nightlies for V-ray for Houdini (4.x)? If so, I suppose I have to ask for access, because the are not in the current houdini vray folder.

**Comment by bdancer** [comment]
I've uploaded one nightly build, it'll require 4.x licenses both for V-Ray Render Node and V-Ray Application SDK. Some stuff is still broken (some Phoenix related), but hope it'll be useful.

**Comment by Dentzz1** [comment]
@bdancer How do we get a 4.x license? I think I was asked about testing the beta for V-Ray Next for Maya should I email back about that?

**Comment by bdancer** [comment]
@Dentzz1 just write to support, they'll figure it out.

**Comment by bravehamster** [comment]
@ronald-a , try the User Color VOP instead. 

As a side note as you may stumble upon this - if you're adding a stylesheet and you want to override a parameter on a material (let's say reflect), you need to plug a userColor node into the reflect slot of the material, and rename the Attribute on the userColor node to "reflect". This is done intentionally to speed up the rendering of very heavy scenes.

**Comment by bdancer** [comment]
@ronald-a there is "V-Ray Material" node under SHOP. Also "mesh vertex" works fine for me (scene + a separate issue is much appreciated).

**Comment by ronald-a** [comment]
@bdancer sorry, my bad. I meant for MAT context (and I meant exactly that node). I'm trying to stay away from SHOPs as they will be deprecated at some point. 

@bravehamster User Color VOP did the trick - I could swear I tried that before and it didn't work.... didn't that use to work with meshvertexchannel at some point... hmmm, too much mantra lately

Nice, I didn't know that stylesheets work with vray.

**Comment by bravehamster** [comment]
Yup, I've confirmed that there's an issue with the VertexColorChannel on my end. It defaults to reading the UV set so we've missed it.

**Comment by bdancer** [comment]
@ronald-a I think I'll remove "meshvertexchannel", "User Color" covers much more cases. Ok, I'll add "V-Ray Material" to MAT.
