### ISSUE TITLE
VRay Light // Texture Colorspace Settings

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#293]
When specifying an HDRI for a VRay light, there should be controls for the colorspace of the HDRI.

It seems to be defaulting to sRGB currently (guessing), as the same HDRI in Houdini renders super bright and very differently from Maya.

Comparison:
![comparison](https://user-images.githubusercontent.com/1403171/36554398-0787dffe-17b4-11e8-858b-d59de79973e2.jpg)

Zip including Houdini and Maya scenes + HDRI:
https://drive.google.com/file/d/1HQ5LEHq28t61yvtS6JRW74cEEOLm6wgL/view?usp=sharing

Windows 10, Houdini 16.5.323, VRay vfh-2270-9874c9d-hfs16.5.323-qt5-windows

**Comment by bdancer** [comment]
There is a "Color Space" control added. Works only when file path is selected. If node is selected (with op:/) then settings from that node will be used.
