### ISSUE TITLE
Total Chaos -- #noissue

### ISSUE THREAD

**Issue by dominik2608** [ChaosGroup/vray-for-houdini#294]
Hi all,

anybody attending Total Chaos in May?
Andrei, are you there?

Cheers
Dominik

**Comment by bdancer** [comment]
@dominik2608 I'll be there for sure =)

**Comment by dominik2608** [comment]
Hey cool, let's meet then! I am there too

**Comment by bdancer** [comment]
@dominik2608 perfect! See u!
