### ISSUE TITLE
packed prim issue

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#295]
while looking at the new vray4 build and testing it with stuff I made with mantra I came across and issue with packed prims. see the attached scene. in the graspatch object go down to the red pack node and render the last null (RENDER) with the pack node turned on/off. there is something off with the translation.

On the same note: what is the recommended workflow with packed primitives / instances. Can we use everything as we do with mantra or do we need to involve vray proxies?

Cheers,

Ronny

**Comment by ronald-a** [comment]
oh, and here is the scene
[vray_packedprim_issue.zip](https://github.com/ChaosGroup/vray-for-houdini/files/2008198/vray_packedprim_issue.zip)

**Comment by bravehamster** [comment]
Hi, appears that the transforms are applied cumulatively for each level of the packed hierarchy. 
Thanks for reporting!

**Comment by ronald-a** [comment]
yes, I know. this is just me having some spare time doing some vray for houdini testing, so no worries.

also concerning my other question, is there a recommended workflow for packed prims and duplication. I am in the middle of doing some test with the scene i sent you duplicating that patch a couple of 1000 times. right now it seems that it does work a lot better with proxies but not nearly as smooth as what mantra does with packed disk prims. there is a certain amount of copies that vray starts to slow down drastically while preparing to render. this is actually a similar problem I noticed in maya when instancing using xgen. not sure if this is related to vray core or the vray connection to houdini. once I have a conclusive test, I can send something over.

**Comment by ronald-a** [comment]
@bravehamster yes, I know. this is just me having some spare time doing some vray for houdini testing, so no worries.

also concerning my other question, is there a recommended workflow for packed prims and duplication. I am in the middle of doing some test with the scene i sent you duplicating that patch a couple of 1000 times. right now it seems that it does work a lot better with proxies but not nearly as smooth as what mantra does with packed disk prims. there is a certain amount of copies that vray starts to slow down drastically while preparing to render. this is actually a similar problem I noticed in maya when instancing using xgen. not sure if this is related to vray core or the vray connection to houdini. once I have a conclusive test, I can send something over.

**Comment by bravehamster** [comment]
Hopefully Andrei can chime in on this one as I can't speak for the dev team. 

We haven't done any benchmarks yet to be able to suggest proxies over packed geometry, or alembics, or the instancer. It goes straight on my to-do list, though. Thanks !

**Comment by ronald-a** [comment]
@bravehamster from a user standpoint I can say that everything that is as native as possible - meaning works like with mantra - is preferred. I think that even with vray for houdini being released at some point, people will still also be using mantra for a lot of things because of the tight integration and strengths of mantra (I know we will). so keeping workflows similar would be a great advantage.

**Comment by bravehamster** [comment]
Yup, we've been trying to stick to a Houdini workflow. If you notice anything out of the ordinary or got any suggestions - feedback is more than welcome.

**Comment by blented** [comment]
Big +1 for supporting native packed prim workflows.  Packed prims are literally the best part of Houdini, and like Ronald said you want to be able to pop a Mantra scene open, switch to VRay, and have it "just work".

**Comment by dominik2608** [comment]
So for me: +1!!!

**Comment by bdancer** [comment]
That was a bug that's already fixed, I'll upload new build asap.
