### ISSUE TITLE
UV texture data

### ISSUE THREAD

**Issue by Dentzz1** [ChaosGroup/vray-for-houdini#296]
Did the way of passing UV data from houdini to vray change? I don't see any mapping outputs on something like channel_named which I think existed on the pre 4.x version. Not sure if I did something wrong, this is being worked on to make a better system or there is a different way to do this.

**Comment by bdancer** [comment]
Make sure you don't have env. variables pointing to the old plugin data (especially VRAY_UI_DS_PATH pointing to .ds files).

**Comment by bravehamster** [comment]
Just to expand on this: 

We added a new node called Image FIle that is basically a (Bitmap File + Bitmap Image + UVWGen Channel Named). 

The UV nodes are still there under the tab menu -> V-Ray -> Mapping

**Comment by Dentzz1** [comment]
@bdancer for the env variables I don't think I have it pointed to the old data but I easily could or have written something wrong in the environment variable.
 I do get some warnings like
C:/Vray4Houdini/ui/plugins/SettingsEnvironment.ds Error(1): Expecting open brace for script
 VFH [Error] Error parsing file: "C:/Vray4Houdini/ui/plugins/SettingsEnvironment.ds"!


@bravehamster The imageFile at least looks like it works and has both inputs and outputs. unlike the older channel named.
![uvtex](https://user-images.githubusercontent.com/22080153/40307270-c8794c38-5ccf-11e8-8953-17e0049539ce.jpg)
I'm not sure what is able to plug into the image file as the uvwgen doesn't have any outputs for me(which might be the env file I messed up on?) Would this be plugging something like the triplaner into uvwgen?So what would the order or setup be for something like a vray procedural texture or doing something with UDIMs?

**Comment by bdancer** [comment]
This file "ui/plugins/SettingsEnvironment.ds" is now located in another place, so you probably have a lot of old files. Just remove the whole old plugin directly ("C:/Vray4Houdini") and unpack the archive again.

**Comment by Dentzz1** [comment]
Deleting all of the vray files and reinstalling seems to have cleared and fixed some things. Nodes look different so I assume they are now correct. Saying that, I'm now not exactly sure how or the order nodes are supposed to be put together.
