### ISSUE TITLE
GPU not rendering materials

### ISSUE THREAD

**Issue by Dentzz1** [ChaosGroup/vray-for-houdini#297]
When trying to map a checker texture or use fastsss materials would show up with CPU rendering but not using the GPU render. Is there work being done with the GPU render and this might not be working for awhile or is this just some bugs? Looking at the max  documentation sounds like there was a lot of overhaul  on GPU rendering and change of UI.

**Comment by bravehamster** [comment]
The Checkered texture works with CUDA and OpenCL for me when applied to a V-Ray Material's diffuse - any chance you forgot to 
1. add UVs to your geometry, 
2. apply the material or 
3. add UV Mapping to the Checkered texture's uvwgen slot at the bottom?

Regarding the SSS material - I'm actually getting a crash, possibly related to the drivers but will definitely investigate further and get back to you.

**Comment by Dentzz1** [comment]
Clearing out and reinstalling vray fixed some of the issues. However if I don't have a uvw(channel named) applied on the cpu it renders out correctly. 
![cpunouvgen](https://user-images.githubusercontent.com/22080153/40320154-ab081138-5cf8-11e8-8fa1-415c3923d7ae.jpg)
With the GPU it looks correct when doing a light cache but the final render doesn't work. 
![gpunouvgen](https://user-images.githubusercontent.com/22080153/40320176-be93ffe6-5cf8-11e8-815a-60c80847a28c.jpg)

If I do map uvwgen to the checker I get the same result with both cpu and gpu.
![cpuuvgen](https://user-images.githubusercontent.com/22080153/40320204-d49a36d4-5cf8-11e8-9152-30fe5815e68d.jpg)
![gpuuvgen](https://user-images.githubusercontent.com/22080153/40320205-d4acab02-5cf8-11e8-9386-01913985ef4f.jpg)

Also what would I need to set to have channel named correctly follow the uv channel I created and then use the sliders to alter the uv output?

**Comment by bdancer** [comment]
@Dentzz1 channel named + checker works fine for me both for CPU and GPU. Could you attach your scene?

**Comment by Dentzz1** [comment]
@bdancer [Checker.zip](https://github.com/ChaosGroup/vray-for-houdini/files/2023771/Checker.zip)

**Comment by bdancer** [comment]
@Dentzz1 works fine for me, ok, I'll update build asap.

**Comment by Dentzz1** [comment]
@bdancer Cool look forward to the new builds and posting the nightlies, so I'm not commenting on things that have already been fixed.

**Comment by Dentzz1** [comment]
Using the latest build "channel_named" uvwgen I think works for both CPU and GPU and can use that to change size and repetitions on the pattern :-). If uvwgen isn't mapped I'm not sure at all what is being generated by the CPU or GPU but looks like it has the same results as before. Not sure what each render engine is using to generate procedural texture in space and why there is a difference between CPU and GPU.

**Comment by bdancer** [comment]
@Dentzz1 we'll merge Houdini specific textures GPU support soon, stay tuned.
