### ISSUE TITLE
Linux Builds

### ISSUE THREAD

**Issue by Eiken** [ChaosGroup/vray-for-houdini#298]
Adding an issue here instead of mailing support.

Is there any eta when linux builds might be available? We don't run houdini on windows.

**Comment by bravehamster** [comment]
Hey, Eiken, 
the dev team is fixing a few issues with volumetric rendering and also adding extra support for Alembics. 
Once that's done, Andrei will get the Linux builds going again. 
Sorry for the delay!

**Comment by Eiken** [comment]
Awesome, looking forward to it :)

**Comment by dominik2608** [comment]
+1 for me!!

**Comment by Eiken** [comment]
Saw a build yesterday but seems to always crash on render. I'll keep a look on new once showing up.

**Comment by dominik2608** [comment]
+1, immedate crash with IPR or Production

**Comment by bdancer** [comment]
@Eiken @dominik2608 sry for that, checking...

**Comment by bdancer** [comment]
@Eiken @dominik2608 what's your Houdini version? Does it match the one in the archive version?

**Comment by Eiken** [comment]
Yeah I downloaded and installed just to test

**Comment by bdancer** [comment]
@Eiken there is a new build uploaded. I've tested some simple scenes - seems to not crash.

**Comment by dominik2608** [comment]
thx Andrei, I'll test little later today!

**Comment by Eiken** [comment]
Could reproduce it so made a seperate issue.
