### ISSUE TITLE
IPR update issues

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#302]
Not sure what the current status on the IPR is, but there is a lot of stuff not updating (for example pretty much everything shader related). Moving the camera, transforming objects, seems to work. changing parameter inside SOPs also seems to fail. the sop things did have issues from the beginning, because one could not add more SOP and vray would update accordingly (just like mantra does). But now it seems even changing parameters on existing nodes doesn't update anymore.

BTW. a bit unrelated but still: really great to have a vray material builder node in MAT. Not only is everything much tidier now, it's also a lot easier to create vray shading networks because inside the builder node only vray nodes are shown so tab-type makes a lot more sense. Really awesome!

**Comment by bravehamster** [comment]
Darn, IPR issues are so hard to track down as you need to sit there and test everything bit by bit. Time to go for another run I guess. 
Thank you for reporting this, we'll look into it !

**Comment by bdancer** [comment]
@ronald-a shader updated (https://github.com/ChaosGroup/vray-for-houdini/commit/d0ca3d3cf19a4d62ad039891b2f38b85e229a003) and SOP updates (https://github.com/ChaosGroup/vray-for-houdini/commit/66248a03f72f7d1c40a070f90dfb1810bcbd2e31) should work now.

**Comment by ronald-a** [comment]
@bdancer I suppose that this will be in tomorrow's build

**Comment by bdancer** [comment]
@ronald-a I've uploaded new ones.

**Comment by ronald-a** [comment]
@bdancer Shaders work, SOP updates still don't I'm afraid

**Comment by bdancer** [comment]
@ronald-a well this works for my scenes, could you post yours? May be some particular dependencies should be added... SOHO thing is very tricky...

**Comment by ronald-a** [comment]
@bdancer well nothing special here. created a torus. added a light/camera. hit ipr. changed the "rows" on the torus sop -> no update

**Comment by bdancer** [comment]
@ronald-a 
![vfh_ipr_sop](https://user-images.githubusercontent.com/319784/41353543-269130f8-6f25-11e8-8972-067356f50e8f.gif)

**Comment by ronald-a** [comment]
@bdancer hmmm... ok. this does not work here... also I am rendering with the vray vfb not in the houdini renderview (not sure if that does make a difference). How did you get vray to output into there?

**Comment by ronald-a** [comment]
@bdancer Wait, got I got it. So what happend was that I always push the RenderRT Button in the shelf which does not create a vray ipr node but a normal vray render rop. This will also not show up in the dropdown in the renderview. with the vray ipr rop rendering in the renderview, SOP updates work (so there is still some sort of issue when using the "normal" vray render rop with the vfb but I can live with that)

**Comment by bdancer** [comment]
@ronald-a IPR and "Render RT" are completely separate modes. I'll check "Render RT".

**Comment by ronald-a** [comment]
@bdancer may I ask what the reason for the two different nodes is? from a user standpoint this doesn't seem to make sense especially when knowing that with mantra ipr/final renders can come from the same rop (and I use that fact when working with mantra all the time).

**Comment by bdancer** [comment]
@ronald-a we are still investigating with @rafalSFX how to make my custom ROP_Node (VRayRenderer) to work with SOHO IPR. Once we'll figure it out there will be only one node. The issue comes from the fact the SOHO IPR is implemented through Python.

**Comment by ronald-a** [comment]
@bdancer I understand. Please let me/us know when these changes have been made. meanwhile I will test other areas of vray4houdini to see if I can break something there ;-)

**Comment by bdancer** [comment]
@ronald-a Actually I'm thinking of leaving IPR ("Render View") only and remove RT button...

> Meanwhile I will test other areas of vray4houdini to see if I can break something there ;-)

I'm sure you could =)

**Comment by jonmoore1** [comment]
Apologies been stuck in Katana land in recent months so only just got round to getting VR4 set up in H. 

Ref IPR, I like that IPR functions with render regions and in the Render View. Houdini has a lot similar tricks to the VFB and interactive rendering makes most sense in the GL viewport or Render View.

However sometimes it's nice to have the VFB's extra features available even when working in interactive mode. It would be nice to have an 'IPR to VFB' button on the shelf too (similar to the old RT option). Seven times out of ten I'd be likely to fire of IPR renders to the viewport but the VFB has those few extra tricks up it's sleeve that are nice to access if an IPR session is particularly fruitful.
