### ISSUE TITLE
Packed Instancing not always working

### ISSUE THREAD

**Issue by Eiken** [ChaosGroup/vray-for-houdini#303]
1. Pack and instance in copy node. Renders but not as instances.
2. Pack before copy. Works
3. Packed Disk Primitive. Don't render at all

Attaching hip file with examples.
[dev_users_aleand_vrayPacked_aleand_v001.zip](https://github.com/ChaosGroup/vray-for-houdini/files/2093322/dev_users_aleand_vrayPacked_aleand_v001.zip)

**Comment by bravehamster** [comment]
Thanks for reporting those!
I believe Andrei is currently working on the packed disk primitives support. I'll look into the copy sop issues and add test scenes. 

Cheers

**Comment by bdancer** [comment]
1. Should work better now, still a bit slower export then "2", will check it later (https://github.com/ChaosGroup/vray-for-houdini/commit/44e4c1592b0d47c09e7dc290afbebaad87695ff8).

3. Should work now (https://github.com/ChaosGroup/vray-for-houdini/commit/1389087afc429ae5955cce59e9e7e2d6e61e9c23).

**Comment by Eiken** [comment]
Great! Confirmed working here as well
