### ISSUE TITLE
licensing issue

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#304]
hey,

I suddenly have a licensing issue with vray for houdini. it show the following error message once I try to render something:

[2018/Jun/26:17:33:16] VFH [Error] Error initializing VRay::VRayRenderer instance: There are no available licenses of this type on the ChaosGroup License Server.

On the license server I can see that one v-ray next app sdk license is engaged once i hit the renderbutton and the error pops up (and this remains engaged as long is i dont close houdini allthough vray is not rendering).

do I need to renew my license (older versions of vray for houdini which used to work also do not work anymore).

cheers,

Ronny

**Comment by bdancer** [comment]
Current V-Ray for Houdini versions require:
1. V-Ray 4.x (Next) Render Node license
2. V-Ray AppSDK 4.x license

**Comment by ronald-a** [comment]
@bdancer So this is still not working. vray4houdini seems to pick up the AppSDK license but not the rendernode license. it test the licenses with maya and out of process ipr (which uses a rendernode lic) and everything seems to work. I don't recall changing anything on the houdini side (except installing a new dot release, but it doesn seem to work with the old version either). how exactly does vray4houdini know where to look for the licenses? is there any other way i can debug this?

**Comment by bdancer** [comment]
> it test the licenses with maya and out of process ipr (which uses a rendernode lic) and everything seems to work.

V-Ray for Maya Next? 4.x?

**Comment by bdancer** [comment]
@ronald-a  better write to support and they will sort it out.

**Comment by ronald-a** [comment]
@bdancer yep, v-ray for maya next beta. Ill check with support.

**Comment by ronald-a** [comment]
@bdancer fyi: support fixed the problem. it seems that newer builds of vray4houdini need a proper commercial lic and can not be run with a vray4 beta lic.
