### ISSUE TITLE
Vrscenes from Maya

### ISSUE THREAD

**Issue by mdelosrios** [ChaosGroup/vray-for-houdini#305]
Hi,

I am having an issue where I create a vrscene in Maya, I import it in Hou, render it, and it doesn’t look identical to the one from Maya.

Some of the issues are:
- motion blur doesn’t match
- noise doesn’t match
- SSS doesn’t match
- Alpha filtering doesn’t match (if I turn Off filtering the the alphas match to the pixel)

Also I noticed that if I export this as a vrscene the link to the original vrscene is missing. I can see the geometry node, but not the vray_vrayScene inside of it. This makes rendering this file in standalone impossiblr.

Am I missing something?

**Comment by bravehamster** [comment]
No, it's likely a bug. I need to test vrscene import extensively as rendering Maya / Max VRScenes in Houdini is incredibly important to the people we've spoken to. 
Thanks for the feedback, I'll check those ASAP. Sending us the Maya file or the vrscene would be huge help, if possible.

**Comment by bdancer** [comment]
Render settings are never imported from the *.vrscene file.

> motion blur doesn’t match

Are settings the same?

> noise doesn’t match

Are settings the same? Is V-Ray version the same as in Maya (some latest 4.x) ?

> Also I noticed that if I export this as a vrscene the link to the original vrscene is missing. 

That's a bug, VRayScene is not even a geometric node.

**Comment by bdancer** [comment]
> Also I noticed that if I export this as a vrscene the link to the original vrscene is missing.

Exports perfectly fine for me:

```
VRayScene VRayScene|1DB3B72E {
  filepath="F:/test-suite/scenes/houdini/features/vrayscene/vrscene_group_by_scene_name.vrscene";
  transform=TransformHex("CDCCCC3D000000000000000000000000CDCCCC3D000000000000000000000000CDCCCC3D00000000000000000000E0BF0000000000000000000000000000E0BF");
  add_nodes=1;
  add_lights=1;
  anim_override=0;
  anim_speed=1;
  anim_type=0;
  anim_offset=0;
  anim_start=0;
  anim_length=0;
  hidden_objects=ListString(
    "VRayLightRectShape3"
  );
  hidden_objects_inclusive=0;
  flip_axis=0;
  use_overrides=0;
  override_filepath="";
}
```

**Comment by mdelosrios** [comment]
I have made sure the render settinng are identical. We are trying to make sure we can recreate renders down to the pixel from Maya in Houdini.

Also, I tried a new scene exporting the vescene and this time it exported it correctly, so there is something in my scene preventing it from export it.

If you don’t mind, could you email me at mdelosrios@zoicstudios.com so we can prepare a scene to send you. Some of the assets we are using are under NDA so I cannot just uplode it here

**Comment by bdancer** [comment]
@mdelosrios done, you should have an email from me.
