### ISSUE TITLE
Slow export of packed objects

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#306]
First off this has improved a TON compared to older versions, but I'm hoping we can get even faster.

We're looking for similar performance to the VRay Instancer inside of 3dsMax.  There you can instance 100k cars on to particles without breaking a sweat.

This scene is 100k medium poly trees scattered on a terrain.  The scene _does_ export and render, it just takes about 5-7 minutes to generate the scene.  Mantra takes around 10 seconds which is far more ideal.  

It's worth noting that 10k trees works relatively quickly.  We have the same issue when rendering alembics with instanced geometry in Maya, where above 10k or so instances scene generation really takes a hit, perhaps they're related?

Scene file:
https://drive.google.com/file/d/1AgKLsmIyV_-GbW8WGCfg-vSY9-sxt7Li/view?usp=sharing

Thanks as always!

**Comment by ronald-a** [comment]
i second that (also for maya). it does work a lot faster if you feed vrproxies to you copy node (etc.) but that is not a very convenient workflow.

**Comment by bdancer** [comment]
@ronald-a that's a regressing from the recent changes in exporting particles. I'll fix this.

**Comment by bdancer** [comment]
@blented 
* 100K - 3 sec
* 200K - 6 sec
* 1M - 30 sec

I'll upload new builds soon, hope I haven't broken anything else.

The issue comes from the stylesheet support and the possibility to override stuff on the mesh itself so I have to pre-process (and cache) stuff down to poly-level for every packed instance. Not sure if I could make it faster, but may be I'll come with the better idea once =)

**Comment by bdancer** [comment]
@bravehamster could you pls test this?

**Comment by ronald-a** [comment]
superfast!

**Comment by ronald-a** [comment]
I have to revert my previous post. it is a lot faster in simple situations (for example copying a 2500 poly torus onto 300.000 points). but when the instanced geometry gets heavier (I have a tree here with around 3 mil polys) it starts to get really slow again. using the old vrproxy trick is fast though

**Comment by bdancer** [comment]
@ronald-a ok, I've found the issue. Will update builds.

**Comment by blented** [comment]
Lightning fast, so so good <3
