### ISSUE TITLE
Volume Rendering

### ISSUE THREAD

**Issue by derbader** [ChaosGroup/vray-for-houdini#307]
Hi All,

I am sorry if this has been already solved, but what is a good way to render volumes in vray. Not necessarily Pyro. If I follow the tutorial I get the error message 

unsupported VDB file format (expected version 223 or earlier, got version 224)

and no volume renders. Same issue with the example scene. 

Thanks

**Comment by bravehamster** [comment]
Hey @derbader , we have a tutorial on this that's terribly out of date: https://github.com/ChaosGroup/vray-for-houdini/wiki/Phoenix-Shader 

The VDB message is not a problem, ignore it.
The other thing you need to do that diverges from the tutorial is to 
1. drop a V-Ray Material Output node, 
2. connect the Volume Grid Shader to the Simulation input swatch and 
3. assign the Material Output to your Geometry node. 

I'll give you a hip file when I get to the office.

**Comment by derbader** [comment]
Thank you so much! Got it working. Perfect.
