### ISSUE TITLE
pscale attribute interpretation

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#308]
Hey,

I found this a while back and it's still in the current builds so:

it seems that vray interprets the pscale/width attribute as radius rather then diameter (which is what houdini/mantra does) so every point/polyline/hair.... has twice the thickness it should have.

Cheers,

Ronny

**Comment by bdancer** [comment]
Should work fine now.

**Comment by ronald-a** [comment]
@bdancer yes, that works perfectly now, i just figured out that the width in the hair properties is also doing it "the wrong way". 

also on a different note I am wondering why vray is rendering a polylines smooth all the time - and - not smooth when hair properties are applied. I would expect it to be the other way around.
And vray renders open curves with some sort of round cap on one end of the curve (which is i guess good for hair shading). is there a way to have it on both ends and optionally completely off?
