### ISSUE TITLE
vray sun & sky

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#309]
Hi,

I am not sure if I am doing this correctly, but if I want vray sun an sky do I need to creaty a vray sun plus a domelight with a vray sky texture applied to it? In Maya the sky is an environment override, but I can't seem to find these overrides in houdini.

**Comment by bdancer** [comment]
> In Maya the sky is an environment override, but I can't seem to find these overrides in houdini.

There is a node called "V-Ray Environment". Create it and select it in "Environment" in V-Ray ROP.

**Comment by bravehamster** [comment]
hey @ronald-a , 
the environment is in a separate node in /out called V-Ray Environment which you can plug into your V-Ray Renderer ROP (right at the top, below the camera controls)
You can drop a Sky texture there and pipe it in. It should be able to automatically find the sun in your scene and behave according to its orientation but you have the option so specify a sun node manually in case you've got more than one. It even works with the compositing nodes so you can color correct the sky or use multiple sky nodes with multiple sun nodes. It's pretty cool

It's done this way so you can share the same environment node between different rops.

[Here's an example scene](https://drive.google.com/file/d/1p91SHhtTfJ1nHeDRX7_FLvVCSiYgQCHb/view?usp=sharing).

Hope that helps.

**Comment by ronald-a** [comment]
@bravehamster Nice, two suns with two skylight environments - that doesn't work in maya. And while we are at it -  what about environment fog? I tried to put a fog node into the environmet rop node but that didn't anything.

**Comment by bdancer** [comment]
@ronald-a sry, environment fog is not yet implemented.

**Comment by bravehamster** [comment]
Doesn't work yet - I've avoided bugging Andrey about this as it's quite easy to make a large VDB from a box and use the VolumeGrid shader to render it. My thinking was that you can apply noises to a VDB while the Fog is uniform everywhere so it's really not worth investing time into.

As far as I know, the Fog doesn't provide any feature or performance advantages over this method. If you can think of a reason to have it, I'm sure it could be done.

**Comment by ronald-a** [comment]
@bravehamster absolutly. I'm just reporting/asking stuff as I go. and env fog is really at the bottom of my list, so no worries.

talking about features: are there any major features missing now from the implemenation because I would really like to know how far we are away from a shipping product in your opinion.

**Comment by bravehamster** [comment]
Off the top of my head - rendering of native volumes (so you don't have to export to VDB -> bring back with Volume Grid Cache) and support for per-primitive textures.

**Comment by bdancer** [comment]
@ronald-a closing this?

**Comment by ronald-a** [comment]
yep
