### ISSUE TITLE
adaptive domelight renderartifacts

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#310]
Hi,

I just stumbled over this one. Simple scene, (plane, torus) plus a domelight set to adaptive. rendering with default settings gives weird noise, turning min shading rate to 64 shows bucket artefacts (see attached scene.

the "same" setup in maya seems to be fine.

[vray4_adaptive_domelight_issues.zip](https://github.com/ChaosGroup/vray-for-houdini/files/2184837/vray4_adaptive_domelight_issues.zip)

Cheers,

Ronny

**Comment by ronald-a** [comment]
wait, there is the same issue in maya.

**Comment by bdancer** [comment]
@ronald-a could you post the render you're getting? Seems to work fine for me.

**Comment by ronald-a** [comment]
@bdancer sure
![domelight_artifacts_shadow](https://user-images.githubusercontent.com/38972966/42580617-4033d972-852b-11e8-8e5d-72e19ce6252a.jpg)
![domelight_artifacts_beauty](https://user-images.githubusercontent.com/38972966/42580619-408b4a54-852b-11e8-8cc9-1c283e26fe34.jpg)
![domelight_artifacts_gi](https://user-images.githubusercontent.com/38972966/42580622-414feb20-852b-11e8-9c07-b6c84ec4c117.jpg)

**Comment by ronald-a** [comment]
@bdancer btw. the beauty pass has added contrast to see the artifacts better

**Comment by bravehamster** [comment]
I'm not sure this is a bug tbh, I'll ask the dev team and get back to you.

Here's the difference between the Maya and Houdini renders:

![diff](https://user-images.githubusercontent.com/20627168/42581381-4af16d5c-8535-11e8-9b9d-1521d60ff68d.jpg)

It's basically the noise only.

**Comment by ronald-a** [comment]
@bravehamster but the blockiness can't be right, especially because it is not there when adaptive domelight is turned off. I did post this also in the vray for maya beta forum.

**Comment by bravehamster** [comment]
Alrighty, please do.
Since the Adaptive Dome is an optimization, my guess is this is a side effect.
Looking at the Render Elements from Maya, the blockiness comes from the Lighting pass. 

![lgt_element lighting](https://user-images.githubusercontent.com/20627168/42581812-47140266-8536-11e8-903e-d57e43180128.png)

**Comment by bdancer** [comment]
Adaptive Dome is still in WIP.
