### ISSUE TITLE
Dome Light Brightness Difference

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#311]
There's a noticeable difference in brightness between Maya and Houdini for a simple scene w/ a dome light.  (VRay also isn't rendering the alembic correctly, which I'll bug separately)

![houdini](https://user-images.githubusercontent.com/1403171/42585339-2d74eb14-84ea-11e8-9250-d02661a19b92.png)
![maya](https://user-images.githubusercontent.com/1403171/42585342-2e3cb202-84ea-11e8-978d-cce194ab9cae.png)

VRay: vfh-1cd16ad

Example scene w/ houdini and maya scenes + dome and alembic file:
https://drive.google.com/file/d/1E69Hh9heOYj-Qp37H7tRFf3LfnOQ1TzY/view?usp=sharing

**Comment by bravehamster** [comment]
@bdancer , I'll look into this

**Comment by bdancer** [comment]
Also you'll need to match units: Maya's default is "cm" (resulting SetttingsUnitsInfo::meters_scale=0.01), while Houdini is "m" (meters_scale=1.0).
