### ISSUE TITLE
Alembic mismatch between viewport and render

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#312]
VRay isn't rendering a simple Alembic exported from Maya correctly, though it displays correctly in the viewport.

VRay: vfh-1cd16ad

Example file w/ maya + houdini scenes and alembic:
https://drive.google.com/file/d/1E69Hh9heOYj-Qp37H7tRFf3LfnOQ1TzY/view?usp=sharing

**Comment by bravehamster** [comment]
Interesting ... when using the Alembic SOP, everything looks correct. 
Apparently, the Alembic Xform is not taken into account. 
Thanks!

**Comment by bdancer** [comment]
Should work correctly now.
