### ISSUE TITLE
ipr stability

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#314]
Hi,

it seems that the ipr's stability is not at it's best right now. i'm getting a lot of freezes lately. Not sure if it is because it is being worked on, but I just wanted to make you are aware of it.

normal production rendering is fine though.

**Comment by bdancer** [comment]
@ronald-a IPR initialization was completely rewritten and should be much faster now and correctly detect "Stop" action. However, we're still working on better changes tracking.

**Comment by ronald-a** [comment]
@bdancer just had a chance to look at beta 1 (because my nightlies access ran out) and IPR seems to be back to stable! I'll keep playing around with it and see how it behaves.

On a sidenote: is this forum here ending now that beta1 is out? should I get another nightlies access for the sake of giving fast feedback considering the speed at which you are implementing stuff?

**Comment by bdancer** [comment]
> is this forum here ending now that beta1 is out?

Well, I don't wanna remove it, but it's better to keep stuff in one place.

Yes, sure you could request nightlies access back.
