### ISSUE TITLE
vdb rendering, houdini crashes when finished

### ISSUE THREAD

**Issue by simonrainerson** [ChaosGroup/vray-for-houdini#315]
When I render a vdb houdini crashes after the render is complete. The exr is saved and looks fine. In the crash report it looks like libHoudiniUI.so is in trouble. Attaching a crash report and a scene that crashes for us here (tested on two computers). 

CentOS Linux release 7.4.1708 (Core)
Houdini FX 16.5.473
vrayHoudiniVersion: vfh-3228c2b

[crash.simple_density_ball.sira_6289_log.txt](https://github.com/ChaosGroup/vray-for-houdini/files/2205031/crash.simple_density_ball.sira_6289_log.txt)
.

[houdini_vray_vdb_crash.zip](https://github.com/ChaosGroup/vray-for-houdini/files/2205015/houdini_vray_vdb_crash.zip)

**Comment by Eiken** [comment]
> In beta 1, volume rendering on macOS and Linux is not supported yet.

Guess this is the reason

**Comment by bravehamster** [comment]
Hey Erik, we're having troubles with the App SDK on Linux which VFH is based on. Andrei has been looking into possible solutions so this should be fixed soon. Just FYI, the crash is not present when exporting vrscenes or rendering with Standalone.

On 9 Aug 2018 20:41, Erik <notifications@github.com> wrote:

In beta 1, volume rendering on macOS and Linux is not supported yet.

Guess this is the reason
