### ISSUE TITLE
Vray for Houdini Indie on The mac Installation issues

### ISSUE THREAD

**Issue by singhs-apps** [ChaosGroup/vray-for-houdini#316]
Hello, 

Does anybody have a proper step by step for installing and running Vray or Houdini Indie on the mac?

I copied the env text into the houdini.env (for V16.5.473)  file as follows :
```
_RMANTREE="/Applications/Pixar/RenderManProServer-21.7"
PATH=$RMANTREE/bin:$PATH
HOUDINI_DEFAULT_RIB_RENDERER=prman

#OCL
HOUDINI_OCL_DEVICENUMBER = 1

# V-Ray for Houdini Begin
#
VFH_ROOT="/Users/****/Desktop/vray_adv_40303_houdini16.5.473"

VRAY_APPSDK="${VFH_ROOT}/appsdk"
VRAY_UI_DS_PATH="${VFH_ROOT}/ui"
VRAY_FOR_HOUDINI_AURA_LOADERS="${VFH_ROOT}/vfh_home/libs"
VFH_PATH="${VFH_ROOT}/bin;${VRAY_APPSDK}/bin;${VRAY_FOR_HOUDINI_AURA_LOADERS}"
VFH_HOUDINI_PATH="${VFH_ROOT}/vfh_home"

PATH="${VFH_PATH};${PATH}"
HOUDINI_PATH="${VFH_HOUDINI_PATH};${HOUDINI_PATH};&"

# Path pointing to QT platform plugins so V-Ray can load dependencies.
QT_QPA_PLATFORM_PLUGIN_PATH="${HFS}/bin/Qt_plugins/platforms"

HOUDINI13_VOLUME_COMPATIBILITY=1
HDF5_DISABLE_VERSION_CHECK=1
#
# V-Ray for Houdini End_
```

I can see the Vray nodes ( some of them ) 
I cannot see the Light nodes
The Vray tool shelf gives the following errors if  click on any icon :
_AttributeError: 'NoneType' object has no attribute 'instances'_

And so on. 
Thanks for the help in advance.

**Comment by bdancer** [comment]
Elements separator on Mac (and Linux) is ":" not ";".
Try this:
```
VFH_ROOT="${HOME}/Desktop/vray_adv_40303_houdini16.5.473"

VRAY_APPSDK="${VFH_ROOT}/appsdk"
VRAY_UI_DS_PATH="${VFH_ROOT}/ui"
VRAY_FOR_HOUDINI_AURA_LOADERS="${VFH_ROOT}/vfh_home/libs"
VFH_PATH="${VFH_ROOT}/bin:${VRAY_APPSDK}/bin:${VRAY_FOR_HOUDINI_AURA_LOADERS}"
VFH_HOUDINI_PATH="${VFH_ROOT}/vfh_home"

PATH="${VFH_PATH}:${PATH}"
HOUDINI_PATH="${VFH_HOUDINI_PATH}:${HOUDINI_PATH}:&"

HOUDINI13_VOLUME_COMPATIBILITY=1
HDF5_DISABLE_VERSION_CHECK=1
```

**Comment by bdancer** [comment]
I'll fix the example .env file.

**Comment by singhs-apps** [comment]
Hello
I realized that and changed ";"instances in the example env file to ":" but the issue persisted.

Will try again with the new example you posted here.

**Comment by singhs-apps** [comment]
No Luck.

I moved the vray folder to applications and tried again with your example

RMANTREE="/Applications/Pixar/RenderManProServer-21.7"
PATH=$RMANTREE/bin:$PATH
HOUDINI_DEFAULT_RIB_RENDERER=prman

#OCL
HOUDINI_OCL_DEVICENUMBER = 1

# V-Ray for Houdini Begin
#
VFH_ROOT="/Applications/vray_adv_40303_houdini16.5.473"

VRAY_APPSDK="${VFH_ROOT}/appsdk"
VRAY_UI_DS_PATH="${VFH_ROOT}/ui"

VFH_HOUDINI_PATH="${VFH_ROOT}/vfh_home"

VRAY_FOR_HOUDINI_AURA_LOADERS="${VFH_HOUDINI_PATH}/libs"

VFH_PATH="${VFH_HOUDINI_PATH}/bin:${VRAY_APPSDK}/bin:${VRAY_FOR_HOUDINI_AURA_LOADERS}"

PATH="${VFH_PATH}:${PATH}"
HOUDINI_PATH="${VFH_HOUDINI_PATH}:${HOUDINI_PATH}:&"

# Path pointing to QT platform plugins so V-Ray can load dependencies.
QT_QPA_PLATFORM_PLUGIN_PATH="${HFS}/bin/Qt_plugins/platforms"

HOUDINI13_VOLUME_COMPATIBILITY=1
HDF5_DISABLE_VERSION_CHECK=1

**Comment by bdancer** [comment]
@singhs-apps could you drop me an email at andrei.izrantcev@chaosgroup.com?
