### ISSUE TITLE
rop.render() function not updating the frame to render

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#319]
The rop.render() function call for the vray_renderer node doesn't seem to update the frame to render when frameTuple is given as an argument.  To get it working on the farm we had to manually set the frame value for the scene each time a frame is rendered.  

We worked around it, not a big deal at all, just not in line with the other rop nodes in Houdini.

**Comment by bdancer** [comment]
Well, I'm not implementing this function, this is how Houdini is passing parameters to my node. @rafalSFX any ideas?
