### ISSUE TITLE
Lens Distortion from Texture

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#328]
Lens distortion from a texture (our primary workflow) does not work, it seems to render one pixel from the image.

FWIW it would be great if "wrap" was off on this texture by default as well.  We can turn it of in the place node in Maya but there are no options for it in Houdini as it's just a path.

Scene file w/ st map for distortion:
https://drive.google.com/file/d/1D_NYFqrh52F8I76s706VVB1Czvn2-3r1/view?usp=sharing

Same linear exr distortion map works as expected in Maya.

**Comment by bdancer** [comment]
Not sure I got what the issue is:
![image](https://user-images.githubusercontent.com/319784/45288334-15c3b480-b4f3-11e8-84d5-920a65325ef4.png)

**Comment by blented** [comment]
Interesting, I just get a solid grey image:
![image](https://user-images.githubusercontent.com/1403171/45305539-62959400-b4cf-11e8-9205-c7667985350d.png)

Perhaps it's fixed in the last few days?  Nice to know that it's working on your end :)

**Comment by bdancer** [comment]
@blented this code was not touched at all, check all file paths just in case.

**Comment by bravehamster** [comment]
@blented , @bdancer  , I'm also getting a solid gray image. I'll look into this and open an issue if necessary.

**Comment by bravehamster** [comment]
@bdancer , latest Standalone nightly renders the vrscenes correctly while the older one I had previously wasn't handling both the Maya and Houdini exports.

**Comment by bdancer** [comment]
Ok, sounds like V-Ray Core update should solve this. Need to finish one review and we'll update it this week.

**Comment by blented** [comment]
Confirmed fixed, thanks as always @bdancer ❤️
