### ISSUE TITLE
Houdini 17 Builds

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#329]
Any chance we can get builds for Houdini 17?  We're considering using it on an upcoming job but a major factor would be bringing VRay along.

**Comment by simonreeves** [comment]
fyi I just saw this on the forum
> Added support for Houdini 17

I haven't tried it myself
https://forums.chaosgroup.com/forum/v-ray-next-for-houdini-beta/v-ray-next-for-houdini-beta-general/1009620-v-ray-for-houdini-beta-1-weekly-changelog?p=1011506#post1011506

**Comment by bravehamster** [comment]
Hey, Houdini 17 builds are already in the nighlies section. Everyone in the Beta should have access to them by default.

**Comment by ISUther** [comment]
Some how cant access mentioned link. As no username or password but same time i am able to log in to chaos group and i have signed up for vray for houdini beta. Got also installation but only for 16.5 but not 17 ver houdini. 

Any info how can i get vray that works for houdini 17?
