### ISSUE TITLE
Filtering on by default for Light Select render element

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#330]
Without filtering the light select render element is stepped and doesn't "add up" properly in Nuke.

![image](https://user-images.githubusercontent.com/1403171/45440274-b25f9100-b670-11e8-93fe-609871812290.png)

**Comment by bravehamster** [comment]
@bdancer I'll take care of this

**Comment by bravehamster** [comment]
Alright, this should be fixed in tomorrow's nightlies. Cheers!
