### ISSUE TITLE
Materials with Subnet Input Connectors don't work

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#332]
It seems VRay nodes aren't correctly passed through Houdini's Subnet Input Connectors.  This is necessary in order to wrap materials in digital assets and still expose inputs like diffuse color to outside texture networks (ex: a triplanar or a regular texture).

Test file:
https://drive.google.com/file/d/1vqt-Y3ozoWXKW8gz9rks4-sM4B40sHV5/view?usp=sharing

**Comment by bdancer** [comment]
I've added support for "subnetconnector" ("subinput" support was already there, not sure whats the difference between them), other types will need some research...

**Comment by blented** [comment]
That's fantastic!  Should have mentioned, we only need one method to work as they all accomplish the same thing, so subnetconnector is fine for us thanks :)

**Comment by blented** [comment]
@bdancer tested with 16.5.496_42cb348_2799 and couldn't get any of the ways working, can you confirm it's working with the test file on your end?  The rubber toy should be purple as it is if you assigned the bottom layered texture.

![image](https://user-images.githubusercontent.com/1403171/46233093-49da0a80-c326-11e8-8800-b458d5a2ab05.png)

**Comment by bdancer** [comment]
@blented I think I've broken smth with new socket types conversion code... let me check...

**Comment by bdancer** [comment]
@blented this should work now. If still won't work in your case pls share some scenes.

**Comment by blented** [comment]
Working!  Doesn't work w/ HDAs, but I submitted that as a new issues cuz I think it's separate.
https://github.com/ChaosGroup/vray-for-houdini/issues/339
