### ISSUE TITLE
shop_materialpath not being read for packed alembics

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#333]
Materials set at the primitive (polygon) level aren't being read when loaded back in as an alembic.  Once unpacked, the material assignment renders correctly.

Test file:
https://drive.google.com/file/d/1FyByUNhG1Su5ziTb185WPRxGgmz7ebzL/view?usp=sharing

**Comment by blented** [comment]
Copy, good to know, we'll adjust accordingly thanks!

**Comment by bdancer** [comment]
But you may try using it with "V-Ray Proxy" SOP along with "V-Ray Proxy Material".
