### ISSUE TITLE
Negative displacement values not working with texture-based displacement

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#334]
Displacement with negative values doesn't work via texture in the VRay Displacement properties

Test file has two geos, one with a texture plugged in and a second with a path to a vray image node, ex: "op:/obj/matnet1/height"

Test file (includes displacement map):
https://drive.google.com/file/d/1KHEmX9QMAZDhBWrTMeVWZHq8ka1UQd4-/view?usp=sharing

Right is correct, left has only positive displacement.

![image](https://user-images.githubusercontent.com/1403171/46233881-472ce480-c329-11e8-9e3b-ec7d91004c4d.png)

**Comment by bdancer** [comment]
@bravehamster could you check this?

**Comment by bravehamster** [comment]
@bdancer yep I'm on it now

**Comment by bdancer** [comment]
@bravehamster tnx!
@blented will work in the next nightly.
