### ISSUE TITLE
Animation not working on VRay Cloud

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#338]
I've tested an animated alembic and camera thus far
- the alembic doesn't move from the frame you rendered it on
- the camera only moves for the last frame of the sequence

I tried different export settings, $F in the .vrscene output, etc nothing seems to do the trick.

I'm going to see if I can get the command line submit to work in the morning and try exporting a .vrscene per frame then submitting those, though I think they'll all end up in separate jobs..

**Comment by bdancer** [comment]
@blented could you upload some simple setup?

**Comment by blented** [comment]
@bdancer 

Here's a simple test scene w/ a counter and animated camera:
https://drive.google.com/open?id=1G-tvc9t9tD6Qq5r9VMB6PbXcWmZvs3g5

Result is all 5's:
https://vray.cloud/jobs/Bffi6lBXGvyGsowj

![image](https://user-images.githubusercontent.com/1403171/47105479-ec383000-d1f8-11e8-8556-b5e36586dddf.png)

**Comment by bdancer** [comment]
@blented could you try some more recent nightly build? Cause it work fine for me:
![image](https://user-images.githubusercontent.com/319784/47148886-a489d500-d2da-11e8-938c-79f5886d0ded.png)

**Comment by bdancer** [comment]
@blented also try "vcloud update" just in case.
It's located under:
```c:\Users\%USERNAME%\AppData\Roaming\Chaos Group\V-Ray\V-Ray Cloud Client>```

**Comment by blented** [comment]
Confirmed fixed on vray_adv_40304_houdini16.5.496_913ba00_2972, thanks!
