### ISSUE TITLE
VRay Rectangle Lights not working in Houdini 17

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#341]
Rectangle lights work in 16.5 but not in 17, from Oct 24 nightly build.

Inspecting the generated .vrscene the rec light's size is being written out as 0 in 17:
```
  u_size=0;
  v_size=0;
```
vs 16.5:
```
  u_size=0.5;
  v_size=0.5;
```

Example file:
https://drive.google.com/file/d/1rKmp82YxeqcOTjkUb_PrI778fSUxklv6/view?usp=sharing

**Comment by bdancer** [comment]
@bravehamster I've pushed a fix, could you pls check?

**Comment by bravehamster** [comment]
Yup, it's exported correctly now.
I've noticed we export half the value in the UI (so UV Size of 1/1 is exported as 0.5/0.5). 
In Maya the UI value equals the exported value. 
I think that's not a new bug or anything, I just never realized until now. 
Should be do something about this?

@blented  , any thoughts on this?

**Comment by bdancer** [comment]
@bravehamster in Maya it's U/V size (half-width/height):
![image](https://user-images.githubusercontent.com/319784/47723396-1956fa80-dc5d-11e8-8101-ebe14420950e.png)
In Houdini it's total width/height:
![image](https://user-images.githubusercontent.com/319784/47723453-3b507d00-dc5d-11e8-93c0-b93b06ff732e.png)

We could just rename the parameters in Houdini.

**Comment by blented** [comment]
Confirmed working in the latest nightly vray_adv_40304_houdini16.5.496_a0081e0_3006
