### ISSUE TITLE
Referenced and op: params not working

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#342]
Referenced and op: params aren't working in the latest nightly.  Inspecting the .vrscene it seems the params aren't being de-referenced before export.

This should be the path to the alembic instead:
```
GeomMeshFile VRayProxy|CE4536FC {
  file='`chs("../rop_alembic1/filename")`';
```

This was working in Oct 23's nightly so it broke recently.

![image](https://user-images.githubusercontent.com/1403171/47758473-5d033180-dc68-11e8-9120-4ceb8775e258.png)

![image](https://user-images.githubusercontent.com/1403171/47758444-43fa8080-dc68-11e8-97d2-5358c428119d.png)

Scene file:
https://drive.google.com/file/d/1Gk_NanRXHRVCELqFZe3VTfZGQ35oBkuM/view?usp=sharing

**Comment by blented** [comment]
Ah copy, that's good news, thanks Andrei!

**Comment by bdancer** [comment]
@blented I've pushed a temporary fix for proxy, @poseidon4o will finish it tomorrow.
