### ISSUE TITLE
Vray beta in houdini. How to load in UDIM textures and create basic skinn shader?

### ISSUE THREAD

**Issue by ISUther** [ChaosGroup/vray-for-houdini#343]
Hello, 

I am trying to use Vray and test it out how skin shader looks like in Houdini using vray.
Did not want to buy other rendering engine as i do like usually vray results, *those what i have seen
what node to use in order to load in textures i created in Mari?
What file format those textures must be?
i have base color maps, displacement maps and multy channel maps.

**Comment by blented** [comment]
@ISUther the format is:
```
c:/folder/texture.<UDIM>.exr
```

**Comment by ISUther** [comment]
But what nodes to use where to load in the textures?
I am using Vray first time. 
I created vray material builder node in houdini and when i dived inside i have nodes like vray_material_output1
VRayNodeBRDFVRayMtl1
I created vray displacement node and plugged in those displacement maps
but i do not know where to insert other texture files (base color maps as UDIM-s for example). 
Those options i have regarding texture nodes: 
https://i.imgur.com/gWpNdG8.png
When i type in vraytext
I get 2 nodes: 
V-ray Layered Texture and V-ray OSL Texture
https://i.imgur.com/eNAHm9b.png

but on both of those i cant see option where i can insert my texture files (TIF files) from Mari.

**Comment by blented** [comment]
Ah gotcha, the node you're looking for is VRay Image File, you can use that to load in the textures and plug them in to VRayMtl1 @ISUther

**Comment by ISUther** [comment]
What am i doing wrong here?
Does not seem to work. 
https://i.imgur.com/ay1ICQo.png

Here is small video i made where i try to explain the issue. 

https://www.youtube.com/watch?v=FKZ74H-EK1c&feature=youtu.be

**Comment by blented** [comment]
Super close, the texture path should read:
```
Base Color.<UDIM>.tif
```

The syntax for VRay is different than Houdini (ideally they would support Houdini's syntax to avoid confusion but until then you have to change it manually.

![image](https://user-images.githubusercontent.com/1403171/47961305-ecd91080-dfc5-11e8-8515-7818d70524d7.png)

**Comment by ISUther** [comment]
@blented Hey. Thank you it started working. 
Tho now some how displays it bit wrong. 

Here is how it displays. 
https://www.youtube.com/watch?v=WHadJJSbOwY&feature=youtu.be

**Comment by bdancer** [comment]
@ISUther could you send me your scene at andrei.izrantcev@chaosgroup.com to check what's going on?

**Comment by bdancer** [comment]
@ISUther Using `<UDIM>` seems to work fine for me, so yeh, scene will be much appreciated.

Also I've added internal `%(UDIM)d` translation info `<UDIM>`. Will be available in tomorrow nightly.

**Comment by bdancer** [comment]
@ISUther did it work for you? Drop me a scene please if this still not resolved andrei.izrantcev@chaosgroup.com.
