### ISSUE TITLE
VRay Proxy's loose their intrinsic bounds

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#344]
I can upload a test scene later this morning but it's pretty simple:

1. Load in a VRay Proxy, set an alembic as it's file
2. Connect it to an attribute vop or a merge or anything
3. Hit space + g in the viewport

With no bounding box framing the object in the viewport won't work. You can also inspect the primitive intrinsics and observe the bounding box change.

**Comment by bdancer** [comment]
This sounds like a bug, but as I mentioned earlier it's better to use native Alembic node for Alembic files.

**Comment by bdancer** [comment]
And I can't reproduce this. Middle-click also shows correct bbox.
