### ISSUE TITLE
Houdini 17 Windows Build - Warning: Bad operator type when binding handles

### ISSUE THREAD

**Issue by chrisheckey** [ChaosGroup/vray-for-houdini#345]
Greetings,

Currently having an issue trying to use the latest nightlies with Houdini 17 on Windows.  No Lights are available and the following warnings print out to the console:

Warning: Bad operator type when binding handles: Object/VRayNodeSunLight
Warning: Bad operator type when binding handles: Object/VRayNodeLightDirect
Warning: Bad operator type when binding handles: Object/VRayNodeLightAmbient
Warning: Bad operator type when binding handles: Object/VRayNodeLightOmni
Warning: Bad operator type when binding handles: Object/VRayNodeLightSphere
Warning: Bad operator type when binding handles: Object/VRayNodeLightSpot
Warning: Bad operator type when binding handles: Object/VRayNodeLightRectangle
Warning: Bad operator type when binding handles: Object/VRayNodeLightMesh
Warning: Bad operator type when binding handles: Object/VRayNodeLightIES
Warning: Bad operator type when binding handles: Object/VRayNodeLightDome

The same nightlies with 16.5 work just fine.

**Comment by bdancer** [comment]
Have you edited houdini.env for 17.0?

**Comment by bdancer** [comment]
Is this Windows 7 or 8? Should work fine in tomorrow nightly.
For `houdini.env` you'll need to make sure "compat" directly is in path:
```
set PATH=%VRAY_APPSDK%/bin/compat;%PATH%
```

**Comment by chrisheckey** [comment]
@bdancer Turns out it was the dbgcore.dll missing from the PATH.  Seems that the dll was not included in the build I was using.  Latest nightlies have it so all is well. 

Thanks for the help.
