### ISSUE TITLE
Post Translate Script Parameter Missing

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#347]
It seems Houdini's VRay Rop is missing Maya's Post Translate Python Script, as described here:
https://docs.chaosgroup.com/display/VRAY3MAYA/Python+Access+to+the+Translated+V-Ray+Scene

The script slots that are there seem to run in Houdini's normal Rop context.

**Comment by bdancer** [comment]
Python post-translate is available only in Maya...

**Comment by blented** [comment]
@bdancer any chance of I coming to Houdini? We use it for material overrides etc in Maya and it's super handy.
