### ISSUE TITLE
VOPs Middle Click Menus

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#51]
Middle Click an input parameter on a vop.
Notice that it has menus that are mostly for mantra.
If I choose an item, it would pop out a python error.
![vop_middle_click_menus](https://cloud.githubusercontent.com/assets/16534677/14522764/ad81fe26-0262-11e6-8a75-1df0c07e710c.jpg)

For comparison, I enabled RenderMan and created an An RSL Material Shader Builder. It seems to also show similar errors.. So I'm guessing that vray cannot really do anything about it, unless there was a way to disable those middle click items whenever inside the vray vop.

**Comment by bdancer** [comment]
No way to implement this.
