### ISSUE TITLE
Weird results when rendering Displacement with GI off

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#58]
In the attahed file: [vray_disp.zip](https://github.com/ChaosGroup/vray-for-houdini/files/227540/vray_disp.zip)
- It renders fine with the GI turned **ON**.
  ![disp_anomaly_gi_on](https://cloud.githubusercontent.com/assets/16534677/14668734/4173dc4e-0718-11e6-82e5-99575acf331c.jpg)
- But if I turn **OFF** the GI, notice that on the **_upper left corner_**, there seems to be an area that Vray is not rendering.
  ![disp_anomaly_gi_off_2](https://cloud.githubusercontent.com/assets/16534677/14908200/ac68f508-0e06-11e6-974d-79588f0bc24c.jpg)
- Regular geometry seems to be working fine.. so it is something from the displacement.
  ![disp_anomaly_geo](https://cloud.githubusercontent.com/assets/16534677/14668909/066a173e-0719-11e6-8794-50ce5653ce50.jpg)

**Comment by bdancer** [comment]
Well, that's how it works on textures with high contrast... You could try using subdivision mode + higher settings.
