### ISSUE TITLE
MBlur on Changing Topology

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#66]
I did a test for motion blur.
- **LEFT :** Animation at Object Level
- **RIGHT :** Animation at SOP Level, with changing topology.
  ![mblur_changing_topo](https://cloud.githubusercontent.com/assets/16534677/14808270/8429e112-0bb6-11e6-8fa3-ab52305be96c.JPG)

Is it possible to also get motion blur even with changing topology?
I tried adding a `v` attribute using the Trail SOP, but it still does not render with motion blur.

Houdini File: 
[velo_blur.zip](https://github.com/ChaosGroup/vray-for-houdini/files/235988/velo_blur.zip)

**Comment by bdancer** [comment]
Works, but better leave it as Point attr.
