### ISSUE TITLE
Node List?

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#68]
I'm looking for a VOP node that I could use to connect to the Dirt Exclude/Include list.
![dirt_list](https://cloud.githubusercontent.com/assets/16534677/14815870/5aaff842-0be0-11e6-8114-327fe9ea5c4c.JPG)

**Comment by bdancer** [comment]
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/86958cddaa81a3b0ab58e75ada030844a88c453f. LightLinker is already supported. Not sure about LightBank, need to check how it affect light/object parameters.
