### ISSUE TITLE
Custom Attributes Render Passes

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#71]
Is it possible to create our custom render passes based on attributes found on the geometry?
- I suppose this is somewhat similar to Vertex Colors in max.
- It is also how Mantra creates some of its passes.
- The closest implementation currently available right now is the updated support for the "v" attribute in vfh 185. Will it be possible to support any other custom attribute? :smile:
- This way, it would be possible for users to also create our own Multimatte pass.
- I was also supposed to open a separate issue regarding how to setup passes that rely on IDs. But maybe going the custom attributes way is more versatile.
  ![render_ids](https://cloud.githubusercontent.com/assets/16534677/14907595/a85bf39c-0dfd-11e6-94c1-0c8e427b6c0c.JPG)
  .

**Comment by bdancer** [comment]
1. ExtraTex + User color / float / integer.
2. Cryptomatte
3. Object properties has "Object ID" + "vray_objectID" attr on primitives.
