### ISSUE TITLE
Unused Render Params?

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#72]
Since VFH will mainly be reading the output size from the camera, some parameters from the renderer could probably be hidden, notably the **Resolution** params in the image:
![frame_buffer_params_2](https://cloud.githubusercontent.com/assets/16534677/14908081/9a6e3086-0e04-11e6-9e81-c28a1ae7a848.JPG)

Or will it still be usable on some cases?
`Img Width`
`Img Height`
`Bmp Width`
`Bmp Height`
`R Top`
`R Left`
`R Width`
`R Height`
`Rgn Top`
`Rgn Left`
`Rgn Width`
`Rgn Height`
`Film Offset X`
`Film Offset Y`

(Original posted as a reply at #63 )

**Comment by blented** [comment]
Please don't remove the resolution params.  Mantra gives the option to override camera resolution in the render node which is what we prefer to use, makes no sense that it's on the camera.  This allows you to have certain passes at low res and certain at full res all using the same camera.

**Comment by galagast** [comment]
@blented Mantra's Override Camera Resolution toggle is also (and is still is) in the V-Ray ROP. The parameters I mentioned above are part of V-Ray, which does not seem to be affecting the final rendered image.

I just checked with the latest builds, the above parameters are now hidden, and can only be added via the Edit Rendering Parameters. Thanks for the UI update!
