### ISSUE TITLE
Material Parameter Overrides for Float Types

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#73]
Overriding Promoted Vray Material COLOR parameters like Diffuse and Reflect works like a charm.
![mtl_override_colors](https://cloud.githubusercontent.com/assets/16534677/14924363/b62c2e3e-0e74-11e6-9866-75928f955f89.JPG)

But whenever I try to override FLOAT parameters like Opacity or Reflection Glossiness.. it does not seem to be working.
![mtl_override_floats](https://cloud.githubusercontent.com/assets/16534677/14924366/b9c8117a-0e74-11e6-9a18-bb10985d0d51.JPG)

File: [mtl_override_reflect_gloss.zip](https://github.com/ChaosGroup/vray-for-houdini/files/242941/mtl_override_reflect_gloss.zip) (vfh 185)

**Comment by bdancer** [comment]
Use "V-Ray User Float".
