### ISSUE TITLE
Crash with LightDome and ColorTex

### ISSUE THREAD

**Issue by Eiken** [ChaosGroup/vray-for-houdini#83]
Instantly when pressing render Houdini crashes when trying to use a LightDome with a ColorTex.

It might be that I am using it totally wrong.

What should we pick in ColorTex? It seems to wan't a path to a Node and not a file path.

When I get the crash I create a File node in COPS and set that as ColorTex.

// E

**Comment by Dentzz1** [comment]
Could someone add vfh_lightdome.tar.gz to the nightly's scene folder maybe in lights? I had no idea how to attach a HDR to a dome light.
