### ISSUE TITLE
support for Houdini render view?

### ISSUE THREAD

**Issue by ultra-sonic** [ChaosGroup/vray-for-houdini#93]
Hey guys,

since Houdini's render-view is pretty powerful itself (compared to maya or max) I thought I ask if you could add support for that at some point?

Cheers
Oli

**Comment by LukeLetellier** [comment]
Any updates on this? The Vray frame buffer workflow is very tiresome during look development, as the window appears *behind* H every time I hit Render, requiring me to minimize H to see the buffer, hit the stop button, then maximize H again. 

If I use RT, I have to make my H window smaller, and move it to the right (with the buffer moved to the left) just so I can see it live. And every time that I need to stop the render & restart it due to a simple geometry change, I have to minimize H, move the buffer from it's default position in the center back to the spot I had it on the left, then bring my H window back up - though it's still covering only a portion of my screen. 

Am I missing something very obvious, or is this indeed the current render workflow? I'd like to have a docked panel in H for rendering, or at the very least allow the frame buffer to always be visible on top of H, unless specifically minimized.

**Comment by bdancer** [comment]
We won't support Houdini's Render View in near future, but we'll definitely fix the VFB issue, as it should float on top of the Houdini window.

**Comment by LukeLetellier** [comment]
Thank you!

**Comment by galagast** [comment]
I recalled last year, when I first got testing VFH.. Render View / IPR was first on the list of my questions/concerns that I sent to Vlado.
Below is a snippet from my email:
![image](https://cloud.githubusercontent.com/assets/16534677/22820722/fa3cfd9a-efb2-11e6-8d01-809cbc674a3e.png)
Hopefully, it could be one of the first few updates that is lined up after an initial release of VFH.
As for now, +1 to make it work again as a window on top of H. 👍

**Comment by LukeLetellier** [comment]
When animating a sequence, the render buffer will usually superimpose itself over all the current windows when a new frame begins to render. It will also become the primary selected object in Windows, which has a couple undesirable side effects:

- If I'm watching a video full screen during a render, the VFB will appear over the full screen video every time a new frame begins, requiring me to manually minimize the frame buffer with the mouse each time. 
- If I'm typing in a text field and a new frame begins to render, the text field is automatically deselected  - which requires me to manually select the text field with the mouse to begin typing.

If each frame takes less than a minute to render, and I'm rendering a 2000 frame sequence - this gets old rather quickly. With that in mind, it would be helpful if there were a frame buffer priority toggle in the Vray ROP that would allow us to determine the behavior of the buffer. 

- With "High" priority, the buffer would always be visible above the H interface unless intentionally minimized.
- With "Low" priority the buffer would stay in the background unless intentionally called to the front.

Thanks.
Luke

**Comment by LukeLetellier** [comment]
^^It appears that this has been remedied in one of the builds since Feb 9. Or perhaps by adjusting the  Environment variables. Either way, once I minimize Houdini, the frame buffer continues to stay minimized.

(Apologies for all the posts in recent weeks; just trying to figure everything out!)

**Comment by dgsantana** [comment]
Any info on RenderView support? Also, is any python method to get the vfb image as in Maya and 3dsmax?

**Comment by bdancer** [comment]
> Any info on RenderView support?

It's still not planned.

> Also, is any python method to get the vfb image as in Maya and 3dsmax?

No, but this could be added pretty easily I guess.

**Comment by dgsantana** [comment]
Ok, I guess the second could be handy. I also keep closing the vfb with the render still rendering, and the render still continues in the background with no way to stop it, or at least I don't see how. Could there be a way to open the current active renderer vfb, or something similar to solve this?

**Comment by bdancer** [comment]
> Could there be a way to open the current active renderer vfb, or something similar to solve this?

It's doable, @poseidon4o could add such a button to the ROP node.

**Comment by bdancer** [comment]
@dgsantana open VFB button is implemented with https://github.com/ChaosGroup/vray-for-houdini/commit/edc1e9b9381994012aa2cf33194a4f90a1274d9d.

**Comment by dgsantana** [comment]
Awesome.

A terça, 2/05/2017, 16:16, Andrei Izrantcev <notifications@github.com>
escreveu:

**Comment by bdancer** [comment]
Just wanna share some progress on "Render View" support. Not yet in the builds.
![vfh_render_view](https://user-images.githubusercontent.com/319784/28212287-6a58146a-68a9-11e7-8af6-67a6f1a82624.png)

**Comment by StrobFX** [comment]
Nice! Thanks for sharing!!!!

**Comment by LukeLetellier** [comment]
Thank you!

**Comment by dgsantana** [comment]
Thank you very much. Very cool.

LukeLetellier <notifications@github.com> escreveu no dia sexta, 14/07/2017
às 15:12:

**Comment by bdancer** [comment]
Initial support for the "Render View" is enabled in the master. New builds should be uploaded soon (or tomorrow).
It's currently done as a separate node (menu "V-Ray/V-Ray ROP") and it's intended to be used **only** for IPR.
![vfh_soho_ipr](https://user-images.githubusercontent.com/319784/28576014-4ac413f0-715b-11e7-8aad-72268ea35dcd.png)

**Comment by dgsantana** [comment]
Awwesome.

A terça, 25/07/2017, 15:07, Andrei Izrantcev <notifications@github.com>
escreveu:

**Comment by bdancer** [comment]
Ops, nightlies are missing some IPR binaries, I'll update them asap.

**Comment by bdancer** [comment]
Fixed builds are uploaded.

**Comment by poseidon4o** [comment]
@rafalSFX I am chasing a crash on linux connected to our IPR implementation, but sometimes the Houdini's crash handler runs even though I have gdb attached to the process. Is there a way to disable the crash handler.

And also another somewhat related question about imdisplay - can we bypass the executable and write to the socket ourselves? And if yes, where can we check what is the data that the reader expects to receive on the socket?
